sprite mdi-database-alert <svg width="48" height="48"><g transform="scale(2)"><path d="M18 7C18 9.21 14.42 11 10 11S2 9.21 2 7 5.58 3 10 3 18 4.79 18 7M10 18C5.58 18 2 16.21 2 14V17C2 19.21 5.58 21 10 21S18 19.21 18 17V14C18 16.21 14.42 18 10 18M10 13C5.58 13 2 11.21 2 9V12C2 14.21 5.58 16 10 16S18 14.21 18 12V9C18 11.21 14.42 13 10 13M20 17H22V15H20V17M20 7V13H22V7H20Z" /></g></svg>

!define MA_DATABASE_ALERT(_color)                                 SPRITE_PUT(mdi-database-alert, _color)
!define MA_DATABASE_ALERT(_color, _scale)                         SPRITE_PUT(mdi-database-alert, _color, _scale)
!define MA_DATABASE_ALERT(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA DATABASE ALERT, mdi-database-alert, _color, _scale)
!define MA_DATABASE_ALERT(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA DATABASE ALERT, mdi-database-alert, _color, _scale, _shape)
!define MA_DATABASE_ALERT(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA DATABASE ALERT, _label, mdi-database-alert, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA DATABASE ALERT>> White
