sprite mdi-file-export-outline <svg width="48" height="48"><g transform="scale(2)"><path d="M14 2H6C4.9 2 4 2.9 4 4V20C4 21.1 4.9 22 6 22H18C19.1 22 20 21.1 20 20V8L14 2M18 20H6V4H13V9H18V20M16 11V18.1L13.9 16L11.1 18.8L8.3 16L11.1 13.2L8.9 11H16Z" /></g></svg>

!define MA_FILE_EXPORT_OUTLINE(_color)                                 SPRITE_PUT(ma_file_export_outline, _color)
!define MA_FILE_EXPORT_OUTLINE(_color, _scale)                         SPRITE_PUT(ma_file_export_outline, _color, _scale)
!define MA_FILE_EXPORT_OUTLINE(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA FILE EXPORT OUTLINE, ma_file_export_outline, _color, _scale)
!define MA_FILE_EXPORT_OUTLINE(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA FILE EXPORT OUTLINE, ma_file_export_outline, _color, _scale, _shape)
!define MA_FILE_EXPORT_OUTLINE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA FILE EXPORT OUTLINE, _label, ma_file_export_outline, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA FILE EXPORT OUTLINE>> White
