brotli --in raw\archimate-abc.repx --out output\archimate-abx.repx --quality 11 --verbose --force
brotli --in raw\archimate-def.repx --out output\archimate-dex.repx --quality 11 --verbose --force
brotli --in raw\aws-abc.repx --out output\aws-abx.repx --quality 11 --verbose --force
brotli --in raw\aws-def.repx --out output\aws-dex.repx --quality 10 --verbose --force
brotli --in raw\awslib10-abc.repx --out output\awslib10-abx.repx --quality 11 --verbose --force
brotli --in raw\awslib10-def.repx --out output\awslib10-dex.repx --quality 11 --verbose --force
brotli --in raw\awslib14-abc.repx --out output\awslib14-abx.repx --quality 11 --verbose --force
brotli --in raw\awslib14-def.repx --out output\awslib14-dex.repx --quality 11 --verbose --force
brotli --in raw\awslib14-ghi.repx --out output\awslib14-ghx.repx --quality 11 --verbose --force
brotli --in raw\awslib-abc.repx --out output\awslib-abx.repx --quality 11 --verbose --force
brotli --in raw\azure-abc.repx --out output\azure-abx.repx --quality 11 --verbose --force
brotli --in raw\azure-def.repx --out output\azure-dex.repx --quality 11 --verbose --force
brotli --in raw\c4-abc.repx --out output\c4-abx.repx --quality 11 --verbose --force
brotli --in raw\c4-def.repx --out output\c4-dex.repx --quality 11 --verbose --force
brotli --in raw\classy-abc.repx --out output\classy-abx.repx --quality 11 --verbose --force
brotli --in raw\classy-def.repx --out output\classy-dex.repx --quality 11 --verbose --force
brotli --in raw\classy-c4-abc.repx --out output\classy-c4-abx.repx --quality 11 --verbose --force
brotli --in raw\classy-c4-def.repx --out output\classy-c4-dex.repx --quality 11 --verbose --force
brotli --in raw\cloudinsight-abc.repx --out output\cloudinsight-abx.repx --quality 11 --verbose --force
brotli --in raw\cloudinsight-def.repx --out output\cloudinsight-dex.repx --quality 11 --verbose --force
brotli --in raw\cloudogu-abc.repx --out output\cloudogu-abx.repx --quality 11 --verbose --force
brotli --in raw\cloudogu-def.repx --out output\cloudogu-dex.repx --quality 11 --verbose --force
brotli --in raw\domainstory-abc.repx --out output\domainstory-abx.repx --quality 11 --verbose --force
brotli --in raw\domainstory-def.repx --out output\domainstory-dex.repx --quality 11 --verbose --force
brotli --in raw\edgy-abc.repx --out output\edgy-abx.repx --quality 11 --verbose --force
brotli --in raw\edgy-def.repx --out output\edgy-dex.repx --quality 11 --verbose --force
brotli --in raw\elastic-abc.repx --out output\elastic-abx.repx --quality 11 --verbose --force
brotli --in raw\elastic-def.repx --out output\elastic-dex.repx --quality 11 --verbose --force
brotli --in raw\kubernetes-abc.repx --out output\kubernetes-abx.repx --quality 11 --verbose --force
brotli --in raw\kubernetes-def.repx --out output\kubernetes-dex.repx --quality 11 --verbose --force
brotli --in raw\logos-abc.repx --out output\logos-abx.repx --quality 11 --verbose --force
brotli --in raw\logos-def.repx --out output\logos-dex.repx --quality 11 --verbose --force
brotli --in raw\material-abc.repx --out output\material-abx.repx --quality 11 --verbose --force
brotli --in raw\material-def.repx --out output\material-dex.repx --quality 11 --verbose --force
brotli --in raw\office-abc.repx --out output\office-abx.repx --quality 11 --verbose --force
brotli --in raw\office-def.repx --out output\office-dex.repx --quality 11 --verbose --force
brotli --in raw\osa-abc.repx --out output\osa-abx.repx --quality 11 --verbose --force
brotli --in raw\osa-def.repx --out output\osa-dex.repx --quality 11 --verbose --force
brotli --in raw\osa2-abc.repx --out output\osa2-abx.repx --quality 11 --verbose --force
brotli --in raw\osa2-def.repx --out output\osa2-dex.repx --quality 11 --verbose --force
brotli --in raw\tupadr3-abc.repx --out output\tupadr3-abx.repx --quality 11 --verbose --force
brotli --in raw\tupadr3-def.repx --out output\tupadr3-dex.repx --quality 11 --verbose --force
pause