sprite $AzureAzureDDoSProtection [51x70/16z] {
lT454jim48NXvGqellzn6z1KYcjuM_g74jkVaFOogcQXPH4X9U7nod0WqNC1WNS08hPOvSgq6wl5PcuoCsOHKJNtECxTL4IOEU2o5_-IP9bacUJ_8BbFydhx
fMj67f3RVQDR7f7xPdNIJadxwld_bBIhUPi3I9ZTsiyU3Peb9j49i9SX03Bgl4OQIAPbBSkZmTllucdWG-xYMIjSvKUWXpmcmGzvo09f9VAvzXv6uj8tKZda
-p92I9gDIS13lhLbX6z_1CtoFqWharOcxPyG_oOD8FPb4Y6giu08yoGW4aHU94h4Gq24djaGs-I-ckJP47dT8jSSERsJGVAoKKunVTAdm1AYde52QUIGC9ep
J1IDqZg5TpwI8n1CMt7i2gUz5DW6D94p7MRm52FsrMKWISm71QOT21Mo9r3QxWS
}

AzureEntityColoring(AzureAzureDDoSProtection)
!define AzureAzureDDoSProtection(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureAzureDDoSProtection, AzureAzureDDoSProtection)
!define AzureAzureDDoSProtection(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureAzureDDoSProtection, AzureAzureDDoSProtection)
