sprite $database [35x48/16] {
00000000000000000000000000000000000
00000000000000000000000000000000000
00000000001357899AA9976420000000000
000000358AAAAAAAAAAAAAAAAA864100000
000049AAAAAAAAAAAAAAAAAAAAAAAA60000
0007AAAAAAAAAAAAAAAAAAAAAAAAAAA9300
007AAAAAAAAAAAAAAAAAAAAAAAAAAAAA900
009AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
003AAAAAAAAAAAAAAAAAAAAAAAAAAAAA600
00038AAAAAAAAAAAAAAAAAAAAAAAAA96000
0000038AAAAAAAAAAAAAAAAAAAAA9410000
0093000146899AAAAAAAAA9987510002700
00AA851000001122222222110000037AA00
00AAAAA853111000000000011247AAAAA00
00AAAAAAAAA99887777788899AAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
009AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
003AAAAAAAAAAAAAAAAAAAAAAAAAAAAA700
0007AAAAAAAAAAAAAAAAAAAAAAAAAAA9100
00005AAAAAAAAAAAAAAAAAAAAAAAAA71000
00000169AAAAAAAAAAAAAAAAAAAA7100000
000000002457899AAAAA998764310000000
00000000000000000000000000000000000
00000000000000000000000000000000000
}

!define OFF_DATABASE(_alias) ENTITY(rectangle,black,database,_alias,OFF DATABASE)
!define OFF_DATABASE(_alias,_label) ENTITY(rectangle,black,database,_label,_alias,OFF DATABASE)
!define OFF_DATABASE(_alias,_label,_shape) ENTITY(_shape,black,database,_label,_alias,OFF DATABASE)
!define OFF_DATABASE(_alias,_label,_shape,_color) ENTITY(_shape,_color,database,_label,_alias,OFF DATABASE)
