sprite $Error_Reporting [64x64/16z] {
tPS7hiCm34Cz9Vh-1_vJg55MSYe4iyJuyp4EwTNoOMfJ3fhj0f_Gep3FkE92UZ9eYajfYtbvXvSGxuJxqXxWbV18MjFXSOJNZyyFGDxdvJAyV8TAV780Gv6G
Zglmr0Jx_Y92xaxixyDUjignmnRW7S0lxXWqwix36u1UYXd44VOOtq6nGT-yXrVLdMFr3AWxnjV-rTe6JeVLnN-nzV1m3QhJdMuSOum9GEZtr65xVQkgiE84
QvPc1Yz9DUkE-RztRtyXh6cFM7z_eGwjE-RnmB77oBnrgF3uDNwj5z2iekNnq382ljliHploX1Dl1Z4FmfatWvZ7NLvkZh_VpA-8vlhZ2TIGd3yyWUUz-Lkg
9jOFdbHf--3rspkltoTyUjkNbCF-eUuPqCd0sx_uTqzRgxW6UuAxk1fi-R81xz-Ce_7nvHlq09VJyIc5po_6KUdu3izFD0_dEn3nq1sV9qrUNrWzTtrYQVBk
osgvwoDBxjmVkRly5MmKNveEZplCTvVlK4gebkuk7-4aX0qSKVP7rP7u_FW1-WO
}

EntityColoring(Error_Reporting)
!define Error_Reporting(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Error_Reporting, Error_Reporting)
!define Error_Reporting(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Error_Reporting, Error_Reporting)
!define Error_ReportingParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Error_Reporting, Error_Reporting)
!define Error_ReportingParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Error_Reporting, Error_Reporting)
