sprite $AzureDatabaseForPostgreSQL [49x65/16z] {
xPPNefmm34LjwLuLxt_16N2Ufc3cCMbVEJ_KWngj_Nkwg2esL5LwUuS0n0ia86s54gUGsbu0yHxYAM_YU_WW45VWRmXuX0_WYNdkWq6Q-GjcvSrcnXoDaER5
ofBP7ekG6iIfK6CGkmd1Xzi2Bu6Cq7wlrJPXK-Q-elSk_KPxGcqZ9eRUtj6LDed2gT8Mp4IBU6PFMaLaoqf4GTepSOATy5zm0jZt4AA0Ygg8dWakyDp71x7C
T4YC6w6w55p6JyXQmxvmMGbrlkieGkT2ZeBLPNUpZ1a3Hm4n9i7n27tSC1u4hJEcMSY9K8deUCQs47md95KhFrN1jdDHGuv9GwPhZXqn9lVbGQ3VKmgupG2M
6JP6wabRguR4-5guZx5yHBM4Xz9b2jsk2emHDbmNGaqEZqBgI0xbKQWY4hFQCK4cKsmbX3oaL4rETLEk1SsljASreRZOKgZ6gW_pKOZOMgYS1DAHetBg99Gh
WNkbQk6ooHD44knB8IJteKBoNhL4XWbjARW408qnsBw43bKSQYW35guYmdk4Qo-ocdlgXuBZgk1Ju5M1DWNmec2icgy9hXyAqVU-AYyB57CAFlcW0BG5F1NM
e7yejDRz4w6t6xmie4s4bmJqLdJuDmAr7_-8_4GWvFm_Qlx3JO443Z_uFm
}

AzureEntityColoring(AzureDatabaseForPostgreSQL)
!define AzureDatabaseForPostgreSQL(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureDatabaseForPostgreSQL, AzureDatabaseForPostgreSQL)
!define AzureDatabaseForPostgreSQL(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureDatabaseForPostgreSQL, AzureDatabaseForPostgreSQL)
