sprite $AzureIoTCentral [57x65/16z] {
xPT7aWGX30GR3_h_VzUR8bWo4EVLPPogHucHUVQMUtukB7Opwyah2yq-hGMNhjYlrNDP7gOs3b7JBBD3rDZ4lPiTeeOg0Sx_NiCPN5cMQPG3k1eq24QDlq0z
xdvfWU0InxA14n9qu0ToI8eGDxB53-4OrNKYTLS9BWAgxi_Ar2EYcfNjesl0ovfXtyhwcmZfIevqAWpDDYl0mcAhbOrm94WSuY72vIOr-zlQ8fGJu19gjd09
frCUFK9T_k8Gob8wXNh4_C8tAxV2DrIVK2pbIo7iuxyGxoC8VHbWatGnvq0AxvZb98xBl3hIDjuMU15wTDUEwsebkSfN7_LzzbJagLJqunxWe0FY1Yi3AZT2
WCgD4A022JXWzmYeX82e2lUmAMe6E4G5kDkvutxIkP-jxgUvw_dn5G
}

AzureEntityColoring(AzureIoTCentral)
!define AzureIoTCentral(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureIoTCentral, AzureIoTCentral)
!define AzureIoTCentral(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureIoTCentral, AzureIoTCentral)

sprite $AzureIoTEdge [63x65/16z] {
fTQBZgmW48JXRg2hIj__WK-OO9Y3jcQTFzUvV8Csh5bxpcjh4QtLOd-lj9ZLFs8V-DqFb3ZLVj3FtjqNdVXyJgrQRtNevVTV_XzHM-ZChtIDxvfd68X49s7D
RwySkDUe9_xrRVRkD2A_TB2QUGYv1bO-nwngFGX8DJoxTdBCGWImw8pxm00ntX7H8ybdVcWSgpj5K18f4KkMShNZVhejdy583vC_zCUx5R2Qu_YQBpVGBbV7
y3rgtE0Sv2pArJC58v80fIyF0iaFbEi3GjciAJkuDH9EcrLXhOsrCwwSp_KZvpvvwFhirKWyfJAvY7CjNvmADyzsRdHrv-o9nSfn0XrnxKizOObKTo5I36kG
X4lVsg8Xze6uLOe01AC82kOIUvZ5uEku7MCjXOa0FfuI9PxuQRFhyIKr5t3uEZ_wubZvFACgLSSdF9tVLXSEnNZK3EDDwocSorTVESK8SP9WpjtEvuMQqoKD
N0wnY_EXKpfF4xxM4ev7-AZqIMHy3dv4eNY1-DzVx2slHVZolQzBV_0S-pRZnTEsvTpR1Ed3rYFZXaiUVlhNCSuH1iHQgmlEAiMglQ-w5RlBsqt1Kj1kCcvt
xIMskuPEkM7x9TCFUATjLma0d_NMRDklU1_h8_ziEVQNVEnuxAyuR7InEaazt7Yr4RSNJOvNl0tzTkk7BXUZYmWyBO-FzhVxlgkL6jiBFjhtVSlv-oJflPxf
Drtra_u7
}

AzureEntityColoring(AzureIoTEdge)
!define AzureIoTEdge(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureIoTEdge, AzureIoTEdge)
!define AzureIoTEdge(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureIoTEdge, AzureIoTEdge)

sprite $AzureIoTHub [65x65/16z] {
xPQ7ZkmW34N79hZS___Vrn5AMC-T43tLFIfRvyYumUiMYYjnJz2ny1y5skI1G1m0ikqADF4NsnGa1WSJi5pbwGyD2oG0u9m66UXR0J0vYYm_5cmSWGju4bS1
B-EUG9ESW0bUOkC8mWGbgg80V4CmwNKMI9870K2AQV-3486GhSKv0FH71WUWJmIIVpCbicje0280f6qwZ4mMHV3G4C14jd8mgKlQ8_rWAG2GTQskWoFQsj7D
Rzq3_kz3aQYGeby_XXppJ8PRT_3tW5y_TBIcihO1W8DiOINn1UcrODU4a9U7aeTHrdiZ0OHMhPmM6Gx0tYxXmeqnGxOt2md4_DQtje4kmTnxMjef7JS5vu-q
KojnfDabQByJWiJQN0B0RkppHR2MKjeVj9wmUUXPIbdxV1KK0tJW3oQNVvDwcUVNuhOfC0na4HJNWNtjXH516m58_G9S1MkwKilr94Jm4dFlR_ORYO1UTC45
_14x1Ig33qCOgmKBZHdoL5miTFvoC-lw8WBAjs0IkABt13y1
}

AzureEntityColoring(AzureIoTHub)
!define AzureIoTHub(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureIoTHub, AzureIoTHub)
!define AzureIoTHub(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureIoTHub, AzureIoTHub)

sprite $AzureMaps [51x65/16z] {
jTHNijqm20PWK0M9_Qyt7X9DT723Mxvt1j2F3Ry28OmWgeLB4b6262Ag45Bf0158uPAk9GX-XLGEZQLwR2mL6okspAJ56oO9atA7cKGcnPQP8iAXaYQ76La6
HQsI0k-6AFQ7MUKV_pAoi3TCbcMIxpApg7soveXa6Qvbkkmy9KcKUO3aYCGyG754ufyCnHfl9ImdBs4MEUFdCAUSpSSmIQwGSaHY7m2zOwdxC9lSO3fKHoJs
0LulvJoP8nBx0EZTNSr-TPaajvZ6rMycty_4uq07rrYJQVpLJylqkmOBsyjCLnlps7KJvX2Z8q0Q6xjCDGCLKCYcpSsbpBPjIPybwUhZvMmkzMEqSefaLZZ9
Uvjk8bbj3TpVUOza5hX5_zlWYkIkWLreXJb7XZTbrJHjWk2GrcGGeAaoGKJNDWaYwb525I9qeGuno5eIGumGrGg49O2uFm
}

AzureEntityColoring(AzureMaps)
!define AzureMaps(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureMaps, AzureMaps)
!define AzureMaps(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureMaps, AzureMaps)

sprite $AzureTimeSeriesInsights [65x65/16z] {
fLU7akmm23CO9p7w_-zz9UoDvp8hROccNW5BiJ3G6Ap76Dj_Z8XkxJFusAu8VplQOeMDOb48--Jma_QIyyZtaePLU1ZZDJIBNiT8SltLyQxqIH9soSyv6is-
ackQpkBRErWPhl7HtaCyoM0adcUmT-AzYmmNMK_rNtx90_eZuHMvDuPVDsxaQZic2R_43EAV7TaeOebm8g0b87ozA0pY_m0GiYwAWZ477W0swSYY48I09O13
bcPvXts10O1_nHNfpCCJc80rZk8UfBmTc1jGzqkz45p11em0nYiDnXGaqXpOczPWJbpOpnj8p1VlctToYVjfeebi-YAxcJ45bSQRW9anTQL-23Dh77LqBpCh
p7oE-dhsOsPBWfaWsDQdE5r1a3C9x4UAbQyPWwRnCBEBkjGeCvSh-4qAFCoSI1PTJkH8p785SwBhZbvcFe3EQi5aJompMo9fDPurJL5c7iIFPsnbOIWpJr9I
nTwr1WCcCCMR-4h3wVN15LGUNPT8utsXEfCsCmxQcKXl91sIzCRgpihCoRjp8QGR4pkV3_I4KfZeV4BHCr9XJp4ZwIcjC5Pk4I3cpEvgJhm_gTwVbUzFwol3
bHXVI_psnaBmvivqTskxlJVUtrplxywluN5dUo-OHunY4U7yxBy
}

AzureEntityColoring(AzureTimeSeriesInsights)
!define AzureTimeSeriesInsights(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureTimeSeriesInsights, AzureTimeSeriesInsights)
!define AzureTimeSeriesInsights(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureTimeSeriesInsights, AzureTimeSeriesInsights)

