sprite mdiHeadset <svg width="48" height="48"><g transform="scale(2)"><path d="M12,1C7,1 3,5 3,10V17A3,3 0 0,0 6,20H9V12H5V10A7,7 0 0,1 12,3A7,7 0 0,1 19,10V12H15V20H19V21H12V23H18A3,3 0 0,0 21,20V10C21,5 16.97,1 12,1Z" /></g></svg>

!if %function_exists("$MdiSprite")
  !unquoted function $MdiHeadsetImg($color = $MDI_DEFAULT, $scale = "1")
    !return $MdiSprite(mdiAccountAlert, $color, $scale)
  !endfunction

  !unquoted function $MdiHeadset($alias, $label=$MDI_DEFAULT, $shape=$MDI_DEFAULT, $color=$MDI_DEFAULT, $scale=1, $stereo=$MDI_DEFAULT)
    !return $MdiSpriteElement("mdiAccountAlert", $alias, $label, $shape, $color, $scale, $stereo)
  !endfunction
!endif
