sprite mdi-car-windshield <svg width="48" height="48"><g transform="scale(2)"><path d="M22.63 15.5L20.21 5.85A1 1 0 0 0 19.14 5.1C17.8 5.24 14.14 5.5 12 5.5S6.2 5.24 4.86 5.1A1 1 0 0 0 3.79 5.85L1.37 15.5A1.5 1.5 0 0 0 2.55 17.36A61.5 61.5 0 0 0 12 18A61.5 61.5 0 0 0 21.45 17.36A1.5 1.5 0 0 0 22.63 15.5Z" /></g></svg>

!define MA_CAR_WINDSHIELD(_color)                                 SPRITE_PUT(mdi-car-windshield, _color)
!define MA_CAR_WINDSHIELD(_color, _scale)                         SPRITE_PUT(mdi-car-windshield, _color, _scale)
!define MA_CAR_WINDSHIELD(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA CAR WINDSHIELD, mdi-car-windshield, _color, _scale)
!define MA_CAR_WINDSHIELD(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA CAR WINDSHIELD, mdi-car-windshield, _color, _scale, _shape)
!define MA_CAR_WINDSHIELD(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA CAR WINDSHIELD, _label, mdi-car-windshield, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA CAR WINDSHIELD>> White
