sprite $Cloud_Armor [64x64/16z] {
tPU5bWCX54C7UVR_FxpJjDJo67eulbcfSP44w_7FLBjUgDS5BcwNShd6pHSokS0huIohSrv_uNMADy8pMPlWXV1SjclUuFj-yv2L3VF8metiACDLyzQQ_TQ1
RaxIXbGrit1jdjJdq6HX8MTd7GMAoFsn6oq3Ce_egXxXMga6ib2DXdqRT_YfU7k3BEI9htNuoNvLpPV1Uzc6ONluXy9XH4kNGV_Y7pJLSFB16IAx3zuybO7d
36MN5-3LFUMbLftpK7rcnxmEOrLjmfkEx9WFnDFZzhfepYD3uCmxp96mCKJcyLQVy1XQyz1h7ZZnSSEBciSz8vdn3fnuu1Ptl3JWu7luIlrC1FXZXbIF1wGP
JviB9iKxFf0uFn7gF-rl-ebZH0Wmah2iqxvfXV1JXaIBSsCrCL1Zu2D9HLcoloPRdw3Sm4FXXw7xce-L1s2VU16aHzqlwTRVJ_GTRpRsbQ2UGaa7tl4HtgHv
NeBAk1qy-Zuz-nfSUSVFflhq6i4POW9_ubo6ZYy-NThmYN6buvChmDgnbk5U5iTtGmKY5HyJBiUdY7Tzjb1qVGSR6V8De6R7KVln_jAx4StDZmnPGJ1bHnck
fVltHywECrnliRb-v6tp_ixPSOORvYqppBFRjL2EAtLBHVZczqUfnp_J7m
}

EntityColoring(Cloud_Armor)
!define Cloud_Armor(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_Armor, Cloud_Armor)
!define Cloud_Armor(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_Armor, Cloud_Armor)
!define Cloud_ArmorParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_Armor, Cloud_Armor)
!define Cloud_ArmorParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_Armor, Cloud_Armor)

sprite $Cloud_CDN [64x64/16z] {
tPO7ZiCm30HbTlt_mmS6GIgfjSwecIkfmpXSjV5ZaDW28Q1h-9BGjUu1y5K1ye0uzRwTyQtLENM8SwCV7gTmq3pe2_XuX1-WUSWtcDr-XWPyS05IwypdMdWq
-XXygeNgZPu5y3IWJkyB46nUwaHD0JSqy3NrY2mWO1fqLqzvIzqt0Db9wWaDdcM683kAEyHpbQ7MlXLtgmmfEkQ3l1_VK9sTYh25oGERjmTbXknbxddpW6TG
tbGPTlgKDxyfCCHB_Skl2tYZ5tvTeD8vQZ-uA73LjulNpnVxDymtyYi64DNhHlfm_0ILqqSVGpPvFD1w3Qgcxst6FBa_QYQm_7V-ochvcWBNZ-NoET7w5RnU
lkMnVjQ-ZmSKOFrk5fy7khr_X87j4-nVSPpOlhdNTRopkt-VFFjnhGU3yyl-4P1Y0zeuFeBiG8OWko93Z8oQtVCppX1djv-XZHRQpcw_XJfMYBTWFI5Hwr4Q
FyOV
}

EntityColoring(Cloud_CDN)
!define Cloud_CDN(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_CDN, Cloud_CDN)
!define Cloud_CDN(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_CDN, Cloud_CDN)
!define Cloud_CDNParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_CDN, Cloud_CDN)
!define Cloud_CDNParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_CDN, Cloud_CDN)

sprite $Cloud_DNS [64x64/16z] {
tPT50Yin34Dbjkz_u0-5VB0pdMpxDaK5f807NmQhNw2CQopZahHhUUG7mh278pyIZ2r-H-_O8P4t2C4CHTuYZiphX1vq7za9kcsUs5qBUPJ3xcReCSbXTMy0
6dClNhSif8qSwf4tBBJOpv5a-DK-cMVu2zBOMzZDwms0l5cuNVWk6ky6r4tmmFRR89etylkDFlolIgEfWLrs3e0Ux_ILVprdwtE65DqQpGUwrey0e3b3YnRE
wadNEm6WKuRSTjmCDQEIX-naSmgM0R1g6Kgqr6Kx0EuPHcxqbOjwX21z0l78RXg_YdgvHAgcYtXcUOimGsDpOW44Dt0IEuWGcJ5ivyWDa2Gsm9aD6lPRtmoS
SBMdleGCJCIf8CkDtZFRuhMddiZW17OBWMSEyy-GZVyWXXl2m0PXU9OD_YiysgwoX__oz5yqZTcU-L4_1BZDttFb__Ux65OMtx-sIliEzlde3POkzxw1a_0R
7IpKcWvihtv2TbCTRQlNGovZzy2K8IHggTDf6BrkZszTywggJEVncCE2DsS_YQeopLSCNrrVplWNRVlam_LfZCKoevktlxupbEaNBBQ_tHQHdLgdLoEEQh-E
dDMUlVi6vm5yKZvs_BnydRDh6Tv2CHE7vlKCpxCxpz2nXO-pExVGS8N6o2m_VtuqnfVn4m
}

EntityColoring(Cloud_DNS)
!define Cloud_DNS(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_DNS, Cloud_DNS)
!define Cloud_DNS(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_DNS, Cloud_DNS)
!define Cloud_DNSParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_DNS, Cloud_DNS)
!define Cloud_DNSParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_DNS, Cloud_DNS)

sprite $Cloud_External_IP_Addresses [64x64/16z] {
tPT7biCm34DL2UZ-5vwNoYGcNR2SlywFRK2r_3FQi1r6Ez0diGldlWuUWBdtyk0XQBblPtnBzGwU03tHAtWAIE4v6DBZ7LGbF0ScTkST9e_NNs2uBaJeuOaH
pgl-bC9pqCw6P-E5PH5sCATxnjaq-DRnoPU_I0TPT-ExbvjV0Tlu8-xk9ZXFdmitF-nmxlbS3vyFF-Ym1O4rs0Cy_59htVXaYxgx-Tr_kSBylCCE1ZuFVEyG
r7sYZ2EVrbyODxxhgS_rWbl0n5U9VPHI6MAd_5jHoMO2oVSvOD1zM2cDki_cqqVnpQUlv5TVFXH_bWU8vv-pOh-6o-VDB-s7o1_9yjrBoCuneb7mMxPzsGY9
kakspnKHX2TktzwTSz67SFRRpzWWFjuxF4zJZe-E2UV7i3kjmr5Y88GdTEZTIHrQIMaNkbCZd6MFWGs1BjyVPol_Z3y
}

EntityColoring(Cloud_External_IP_Addresses)
!define Cloud_External_IP_Addresses(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_External_IP_Addresses, Cloud_External_IP_Addresses)
!define Cloud_External_IP_Addresses(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_External_IP_Addresses, Cloud_External_IP_Addresses)
!define Cloud_External_IP_AddressesParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_External_IP_Addresses, Cloud_External_IP_Addresses)
!define Cloud_External_IP_AddressesParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_External_IP_Addresses, Cloud_External_IP_Addresses)

sprite $Cloud_Firewall_Rules [64x64/16z] {
tPS5riCm38CJ1-JU_y0_GxNONVJwSD-me8Ba1igBONrUqArSCnoN-BYMmv-0KN8C_XHOhfyx-fdA6tm3j19JuLj0Dez1bq_FeAhcCPXgTd66-Udr2-Xm0VHB
ytGBXweVidaCB3Llz3y6BKsoC2tyTjhWRYUFiyS0dkcFyr8_w01PTdFy0LvQCuopE_uu_p-M3EFi02WPcZ_GletZ6s_VFuoTicEzFTfeWHupRBHwhRLz__pG
tTl7ppY2fWn-0r1sg_ySHg2Fv9CgbfOMLZaPjyImS5S_Rrv_k-bVr6vA3RcvN3zSm4EfNsQ6Zs_VVdvgsFG3liSetmZj1r6v-OpRBvoNY4xDjrn_A7-Okwwt
hFiQM_KxkVkKwxVgtJTdnuXww6E_sECaGtq8Q2vWwl2HcVhuCSzEpx2N6CZcCGrwTdg6iwIOd9rkuIXNT2paSdt-EAoy6Ey
}

EntityColoring(Cloud_Firewall_Rules)
!define Cloud_Firewall_Rules(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_Firewall_Rules, Cloud_Firewall_Rules)
!define Cloud_Firewall_Rules(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_Firewall_Rules, Cloud_Firewall_Rules)
!define Cloud_Firewall_RulesParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_Firewall_Rules, Cloud_Firewall_Rules)
!define Cloud_Firewall_RulesParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_Firewall_Rules, Cloud_Firewall_Rules)

sprite $Cloud_Load_Balancing [64x64/16z] {
tPP7keGm38DDS2np_mE_wc-gCA3b_2kQI28vnJwCuT7WmtfceYLdBqSUWDd81_8GD4E8C_gmFLRa2R0QPq6U0gfv1Lnjli0YcbSWskoK3AjvlGEEl01SDezR
EA_g9pLFjJ2kwwClVBpGJWDmVtf_qMLNBziclCcEwtaVfwYl34UcfiySj-m4_oh3MtOqFxFW-TqoH7OSl4SxxxRjLxyLLC_bS2_CLY-IWVChBF8qk3LxkzZJ
1zVNiFFnWYU07VsB_rmF9-K3X5dyNrcz1wqp12jVhuhRlARdbajTi0AUe7gxwTSjRnTa3LfqVNKBclwsW40RFtQMJo1FuSBopOjyfC0GjwyYrEspMCJjkvZY
x2wWdVrkhCBvfL-WXfITbc4OOO6GdPIX6mU2UKA6j-oq3CDs6HUoKosSrk6WC3bd-8nzvh0Funi
}

EntityColoring(Cloud_Load_Balancing)
!define Cloud_Load_Balancing(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_Load_Balancing, Cloud_Load_Balancing)
!define Cloud_Load_Balancing(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_Load_Balancing, Cloud_Load_Balancing)
!define Cloud_Load_BalancingParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_Load_Balancing, Cloud_Load_Balancing)
!define Cloud_Load_BalancingParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_Load_Balancing, Cloud_Load_Balancing)

sprite $Cloud_NAT [64x64/16z] {
tLS7jWCX25oG8lS_S2g_1f2ihuRqCZwOGNOyFYoGf0Z21Ppc8cWDhuEhv6SZYXAaWvSKFcOhHeRN7bxFabTh0BCT4E6vZ-UsTdqDvHsyzBJhQmZw7buRv2bh
LqE8_uBQr51Yagi5P4cUOgag5etFW_Mv03KIe4WTl6S0rQOQaNQ-ye03a2TN5IWasia1p-hq_YABRO39mYoiKyhEn4GxWGFOp9v_oV6IQ-Ulnca1Jg4k6vti
MQq6lxvgfmDG_lGfUh5HCvB6dEWjlZw3lubscGQKoA_EPBlZjMhqFZxgPWdoTr9VynTxPIlWRsZ0do6g1G9ALp-9gyMT_haNo-Vxbttxfll7jDGCN9Hq_zhm
zCiP7CyFH3OfvaVHLJw_h3U_WXIPsEabMyxFC4VdlXu-zRM_7FycoyidbPu0rjw7SxHHmtjPZjSz_s1Zqx_i-gSj_sRiaBCM2BRygz6cVzxsx_ldX_tpoqaA
RUi0PfEEEe2a2CRZm-8A
}

EntityColoring(Cloud_NAT)
!define Cloud_NAT(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_NAT, Cloud_NAT)
!define Cloud_NAT(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_NAT, Cloud_NAT)
!define Cloud_NATParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_NAT, Cloud_NAT)
!define Cloud_NATParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_NAT, Cloud_NAT)

sprite $Cloud_Network [64x64/16z] {
tPT7TWGX30Kb40ZkVs071cTKycCvjNFuwlOlWaUUZ68Ti29C6uwCnd4V2Ku3YeyKXp-X_oVV9QBkEECrYEkAvpYMb-E6ZyznfVBkAcHtx31_VFu21d6eaClZ
2jaTuoqjBwymByzACQoG5xwjPlDj4BszhchJRM1tUKlTsUF7anqkTpo079O1g3cyGKaNljhiuG3lsntcQK1Txe3QndWV83rmU79dgZQ-iGQesicXHwlED-jR
NOALwCTLymS5Kq7-CEMKxy7xI__xlNOoSExlGzdyzhrJt8BbivJDCQpnEHgLClS0hNC0PMsVS81FjKcFX-qxNKMyOFxXo620YEMNW8-h0Ox7Ptv-LJY-yxnt
MfYywhQx_FgoKg9un-ipH-dwpccoOOUfEt18LFZ_vUBnu93TfGxP7JlCtTqvD3dZj-MnGtR73hayTiZkRYjiGfWJIJp__DYAF1cl
}

EntityColoring(Cloud_Network)
!define Cloud_Network(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_Network, Cloud_Network)
!define Cloud_Network(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_Network, Cloud_Network)
!define Cloud_NetworkParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_Network, Cloud_Network)
!define Cloud_NetworkParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_Network, Cloud_Network)

sprite $Cloud_Router [64x64/16z] {
tPS75iCm24F1mGZkV-3kNIpxfMzMtKCuqVUA_9cQEP4ruUe1gkZSZfW8h413J0Lo2hxYzw5zGom8czHIn990mviBHfkV2yh2MuwGi-CCIVFx3i28dKR8mtCd
4SxPkQYl38CsiikmG2l2A-ot0Zp2ZTXl1UWm87PIWBExsMy564DbzfkyPbYpGu_mtltMW9tVHtJK35jHs28YytQ6oCm8q_XIgzb1nIwlB-cQQCMmPgSYzkut
4QqPuhFcIIgN0j2BSB6BugnFXf_ijYVLUCYABsyC4IE_sBTTB3yAnDWlzc4l_F6httyy_etd1zperNxOP_V1MMD-tnsenVx-4wsU-jRxRpryrIAo63_r0BR5
yJkSGDZyGVu2DdtcQm555dwZqtTwOI-Rhnb6EhL7corVwSpky-KpVMmFNLY-quVsBXJGJGbCzc248TEsl7_XpHE6J6rz-qZPpHboTeGXaKajx0sFC-JiE4CU
7cV8sUsDi0kJOI1cNxz-x4t-J4S
}

EntityColoring(Cloud_Router)
!define Cloud_Router(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_Router, Cloud_Router)
!define Cloud_Router(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_Router, Cloud_Router)
!define Cloud_RouterParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_Router, Cloud_Router)
!define Cloud_RouterParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_Router, Cloud_Router)

sprite $Cloud_Routes [64x64/16z] {
tPTNekim24GH5WpiVy6loK-t3GxwpRabJQJCGTYHDqFD7p2LPopmIDXpEU85CAbHn4kWKkATUfUA2z40bt06eWL6DpmEhF7ovs_0-_NU3g_l4Ao-_mOcuW3C
LdZz2EsqtiuQtsc4VNTwiGZxxbGKzJP0lAwNuV455Evy_6N6ZUbVLiW_739t9fyN-vSceGwDreiJpvCur0XQFx0jLPgLkREzEk9hcnA7n1s0syrSRr-1VvUJ
ZZ84umuyNMH4Hgg8P_m0vRvRkNdQgXi3f3nGbQV_pt0jgDOX2fBBwPFpXt661mUnCrplF_coOkjXNBapVCfF78K_sndcVPlEKGtUFqkUbFspsyIg_hqY6_qh
0_N-YUVzCvQYOl_cNhAPT2Mjjznzk35-3BWUvbVk-VLZ1yt--4vT7idyx7MvYX9t6pivVf31EiwENqGCuWoJhnpMWvw-zBdOwLCVd9_xSdTjXznTts7jxjpX
50uEmoCEZzsTEtGfqMDtvn6QF351uDbpncnyVtmZVWC
}

EntityColoring(Cloud_Routes)
!define Cloud_Routes(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_Routes, Cloud_Routes)
!define Cloud_Routes(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_Routes, Cloud_Routes)
!define Cloud_RoutesParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_Routes, Cloud_Routes)
!define Cloud_RoutesParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_Routes, Cloud_Routes)

sprite $Cloud_VPN [64x64/16z] {
tPT9OaCX34FDOClS_y8jQUO8AhPv-_S76R2nBwDwRF1gUpon9Nsl8_y1lj7hcyv0NVkX-B7K6r80pJW5AO4YX2T4ABrU_u3G_JWD3_47rZK4X0zkom_eszVR
gv_e93pj_Jn2F_MTB7pDPn76kH-aTe9Fjy5L5_E_0bexZlTkLhp7iz-F5dwnDWRzArTzlWzhAc3wxrHMEzr7lDVEho2l0Dn_r12i93qlH3MhmVshqBa_BhfP
QsR1yhioTUBNy5-AOGnOyObH7qdzAsraZiOM7mVdVb2_nQJExm-hCU4-sZg_SSqFyojM-Lc0-k_rupxUbczSGNv0_QPk7-u7tRwwNzZneVlEZY_EeEU7F3T4
-Ap4QrHTRxsRyrCwWWhngpvwC3ze-zJzmjgtxhkzSkY3ZY-wtzZufFkGPr--BoiV7rL2c1-5ECW89j6D8_gGvtTEa-uFUdZgFcIrEu_GRKS7WsRFALsuFtuH
Fm
}

EntityColoring(Cloud_VPN)
!define Cloud_VPN(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_VPN, Cloud_VPN)
!define Cloud_VPN(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_VPN, Cloud_VPN)
!define Cloud_VPNParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_VPN, Cloud_VPN)
!define Cloud_VPNParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_VPN, Cloud_VPN)

sprite $Dedicated_Interconnect [64x64/16z] {
tPP9bWGX24HJH23lV-0UwL4WvDMk_jgV0u7AzMGGIm4Jq9TfYQrQLmFeAdHIWoZblfpuakfJxG2TYJvSHoWe7lGPl1wX0nGF-GAomnc2r_S_W84EIWYA1qku
klu2nKCerSLJ_ejK9PmActHMsq0D-tU-WYEVvpSyGfz1TlStx7wO8SxE_IH3YjBv9FKTykogxXgPxnbEL7nDVCzGhU7l2_dGvuyWjeMRBlp6tFqHTh5jRtTr
yxCkVDINwFlv_Fkd1crhv_MBpytJ_6LhtvPlb6oVHl_YepVt1pZwWR_Yuykb7p9_L7C3FB-Ca-ExUtw66MAVYkiBtnycyFgyVrEr2CumpUwRfgzWzaDCCB_q
Hq2o1WJ6Hu3qvaUGNJj3lcAwypFE46VNpr2k56fdro_XkYfO4w3k42_9MNGz6Qy
}

EntityColoring(Dedicated_Interconnect)
!define Dedicated_Interconnect(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Dedicated_Interconnect, Dedicated_Interconnect)
!define Dedicated_Interconnect(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Dedicated_Interconnect, Dedicated_Interconnect)
!define Dedicated_InterconnectParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Dedicated_Interconnect, Dedicated_Interconnect)
!define Dedicated_InterconnectParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Dedicated_Interconnect, Dedicated_Interconnect)

sprite $Partner_Interconnect [64x64/16z] {
tPU7RWCn34DrEbbK_l-3kriZnyWnKSmyp8oNGNhQY-6H2y9jpIWigR7MKK_0i1uddO7tVkxusUedQWESZNwWje0K7eEGlfx18OV74QwxqpjCnK_I0oM0M8Qd
HpXKVwZXSOHzU8XWq4TuOcE4efy6g0s_sZS5-V63ctdym1qkkhjz4sPn-w7jiE_kst_IeL-V_e5yncTtFBAEwS-dkCE-k-dFfxX3bE1pXw7vbnvmhsT4d2i_
FiYgoPrUqoL_GeNyoy_hxm_jzv-uZDlIykDrK-a_QVXAVlc3wIEEttxfdNx7GSk7v0_x1Ypkh1zrjEU6dVMhebc-rVLpTYZvtczVY60kUgwtpnj1uSdRDtSt
4Nr8Pp_c5Cylpmlo4d3b-CYaVdxikzCx37iCnF2uGxqxlSEq5fUxqoCSjYBmY4RNxu_3xSLu1m
}

EntityColoring(Partner_Interconnect)
!define Partner_Interconnect(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Partner_Interconnect, Partner_Interconnect)
!define Partner_Interconnect(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Partner_Interconnect, Partner_Interconnect)
!define Partner_InterconnectParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Partner_Interconnect, Partner_Interconnect)
!define Partner_InterconnectParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Partner_Interconnect, Partner_Interconnect)

sprite $Premium_Network_Tier [64x64/16z] {
tPTN5kim24HLW87zB_WLarSqbfKSFdE_ZK1ptTI-Z25sG4OxeuuZhkTo-1jmMc30tuB35koJUcjFJFW7OBOz7VuHA8UNGChj4_HgU0diwAxaCDlN1n0gFmEf
XiSHdjq11k3m61p2WyviqeTW4-4vF9jh0pj5EF5uZtSQSViOSBdsgrGCLoV9HPGMU7Gdhud3at0RhNLzSDXtvPhLByBLF88TRjtfjMJuIaIuJ6mS3Wf-MvxZ
TbyPTtVecvinKkUaBS3I7M_UWgklHk9k0dQ8cnI9kyrSrNYtO7TptQIEFgxgZCGu0iYzlSQY8dcrrMcKgj_SRU-mVramFFwCHUM5FfSPopEg9nzplOsnw3Dw
bbxHqHNhJMLO-izbkCwF1_h_1i52mV7gLFZp5UFTPolYa3YiykgzvIFm6jeIbDid4rv12j--_M_4y0AZyEj1Ts9ISzZhd-zqju9gU3M7ip66QljabDpL75hr
_v7TrHnAsuD2U0M7itX-uF0A3ibT9K9j9mGxgBn-VjJHleoV
}

EntityColoring(Premium_Network_Tier)
!define Premium_Network_Tier(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Premium_Network_Tier, Premium_Network_Tier)
!define Premium_Network_Tier(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Premium_Network_Tier, Premium_Network_Tier)
!define Premium_Network_TierParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Premium_Network_Tier, Premium_Network_Tier)
!define Premium_Network_TierParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Premium_Network_Tier, Premium_Network_Tier)

sprite $Standard_Network_Tier [64x64/16z] {
tLU7hkqm22lJvFz_-2bvgo4zt0hjOurEGx0phoy3gnTGlcfOe4HOJKVy05G16F4ZK9JWR_Z-aIw85u1ye1FY5T0GR-DhF_q2g25Uah3ZNVRmJDzlW2Pw3MXR
l2nXxHqSRuO1uva9khYGi1AFPz2f4mB2Naee9nsB6N9fp35FvJ10BYucKzRzYhNk4_3HErjwt5wwhQXuzf3I-raxxGMFbOvF3q_ld7nzqTZXVqN87d8EkdG_
HLMsmwFJEvrl8lIvKupiOKwptlmDJKT2iyD3v1RHJHpTKWxDik3I8xsFFxSJn9RuO-Cdw-KcvrzxvVuzYugZIzdOr5roliKqzEoWCWhA5bpsrjB91pDs1x2h
RsEJAxL_w9u1kdKVJME1itvXcuFmr7tzwBDYgLvF2SfbQxoOnWdH1AWnzIUx9xfykasV3MXZxNlUHd0qm8sjHnhg2qqFgLY-6miukkBrF9HY_zBR0dBBkvw7
tjq_Pkzw7khr33J4QtWepVD35g_XOVAk8w5T5HHFIFJ--T7u-ZBy0W
}

EntityColoring(Standard_Network_Tier)
!define Standard_Network_Tier(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Standard_Network_Tier, Standard_Network_Tier)
!define Standard_Network_Tier(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Standard_Network_Tier, Standard_Network_Tier)
!define Standard_Network_TierParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Standard_Network_Tier, Standard_Network_Tier)
!define Standard_Network_TierParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Standard_Network_Tier, Standard_Network_Tier)

sprite $Traffic_Director [64x57/16z] {
fPTNqYGn28CT0E7x7tXJrxB1rbZrDwzJduC47dNxhsOWQI5c-rn5qnMk-8i59l9Qc9n72WMAcyORmJjIAlGpxohlHtmWnSBGlECUQjuPg8UAUD6CIoY8rtb3
mE_R_xHvg0S8dDlCDGddSVkF1vYNnaUEZmE1M-F_vW5Sng0ZEGzs2NJYdSexQNo4n2V6qJjhjZG-3jvvRss4m9U7E1ofky8dohlDb1vPVAUyjOxzJEFNAQBu
5dmCTk-YsugVtlRYvsByqNhaofz7A9xtCPBLA7uR8sa15Fyii8Y28FoQnVTVVYoRMDlzEpz0yIDQUrpnNF_FqAGBzE8NHhN5V_vlxK_cp_iswwMjmg-dj-tm
XZa4FdDPcrY7DxHhV7gG1yZUlJ-jVOs_vHu0-V37tflAVpVV7rfs68z2v8TxTWaYK0ZPgVRnNO1EifjuVzEpexKWucdP5KQzq_CN5uzBo6kyof_fR_9lUITB
oBtJ9UJU2MD0l2CIwkBn1NJhoVUV7Bo_0m
}

EntityColoring(Traffic_Director)
!define Traffic_Director(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Traffic_Director, Traffic_Director)
!define Traffic_Director(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Traffic_Director, Traffic_Director)
!define Traffic_DirectorParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Traffic_Director, Traffic_Director)
!define Traffic_DirectorParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Traffic_Director, Traffic_Director)

sprite $Virtual_Private_Cloud [64x64/16z] {
tPP7OWCn30Ev92Lm___W51UbGJ8Ktpodn3Qs3DJinV3i2z9jJIiigRQEenw0PdCSzH2uJUbAljkCG0aWZ7EW923Buo3bstDmoF9qXOwIWOktrnyWKHiW9Ncw
mhQRRu8yGI6LXplaNwemGDyjwq9IHmWRW8_l6FdbpomdN-IvpEUakv4_yeAFFE-maJm5j4ElsimFV7J7_U52pFBeepkUl_WxgR_H8SZaY3pC8dfTw16VBYFh
3-3pxd9FdEE_-kpoF4a-KPJy-M2NTs6WzBp0Vhu_bqUW6B8_wo3zXTOVEXc-E-F7oVJHnszrCdstvuyb_fblx7Dz_QXZlETi_RemyvTi-TRzmmPUVFt-oXFH
Fjs-K0ATRfyw1zk-THhhLWVqxASJulb5Fm9wRU32yL7jZdUeTxVVOHe7iZnEOB-x_GwxJV7jxlOLDbkH-8iI7tYsFgUvlHZl
}

EntityColoring(Virtual_Private_Cloud)
!define Virtual_Private_Cloud(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Virtual_Private_Cloud, Virtual_Private_Cloud)
!define Virtual_Private_Cloud(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Virtual_Private_Cloud, Virtual_Private_Cloud)
!define Virtual_Private_CloudParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Virtual_Private_Cloud, Virtual_Private_Cloud)
!define Virtual_Private_CloudParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Virtual_Private_Cloud, Virtual_Private_Cloud)

