sprite $Cloud_External_IP_Addresses [64x64/16z] {
tPT7biCm34DL2UZ-5vwNoYGcNR2SlywFRK2r_3FQi1r6Ez0diGldlWuUWBdtyk0XQBblPtnBzGwU03tHAtWAIE4v6DBZ7LGbF0ScTkST9e_NNs2uBaJeuOaH
pgl-bC9pqCw6P-E5PH5sCATxnjaq-DRnoPU_I0TPT-ExbvjV0Tlu8-xk9ZXFdmitF-nmxlbS3vyFF-Ym1O4rs0Cy_59htVXaYxgx-Tr_kSBylCCE1ZuFVEyG
r7sYZ2EVrbyODxxhgS_rWbl0n5U9VPHI6MAd_5jHoMO2oVSvOD1zM2cDki_cqqVnpQUlv5TVFXH_bWU8vv-pOh-6o-VDB-s7o1_9yjrBoCuneb7mMxPzsGY9
kakspnKHX2TktzwTSz67SFRRpzWWFjuxF4zJZe-E2UV7i3kjmr5Y88GdTEZTIHrQIMaNkbCZd6MFWGs1BjyVPol_Z3y
}

EntityColoring(Cloud_External_IP_Addresses)
!define Cloud_External_IP_Addresses(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_External_IP_Addresses, Cloud_External_IP_Addresses)
!define Cloud_External_IP_Addresses(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_External_IP_Addresses, Cloud_External_IP_Addresses)
!define Cloud_External_IP_AddressesParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_External_IP_Addresses, Cloud_External_IP_Addresses)
!define Cloud_External_IP_AddressesParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_External_IP_Addresses, Cloud_External_IP_Addresses)
