sprite mdi-receipt-text-send <svg width="48" height="48"><g transform="scale(2)"><path d="M4.5 20.5L3 22V2L4.5 3.5L6 2L7.5 3.5L9 2L10.5 3.5L12 2L13.5 3.5L15 2L16.5 3.5L18 2L19.5 3.5L21 2V14.26L18 12.76V11H6V13H12V15H6V17H12V22L10.5 20.5L9 22L7.5 20.5L6 22L4.5 20.5M6 7V9H18V7H6M14 13L24 18L14 23V19L18 18L14 17V13Z" /></g></svg>

!define MA_RECEIPT_TEXT_SEND(_color)                                 SPRITE_PUT(ma_receipt_text_send, _color)
!define MA_RECEIPT_TEXT_SEND(_color, _scale)                         SPRITE_PUT(ma_receipt_text_send, _color, _scale)
!define MA_RECEIPT_TEXT_SEND(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA RECEIPT TEXT SEND, ma_receipt_text_send, _color, _scale)
!define MA_RECEIPT_TEXT_SEND(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA RECEIPT TEXT SEND, ma_receipt_text_send, _color, _scale, _shape)
!define MA_RECEIPT_TEXT_SEND(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA RECEIPT TEXT SEND, _label, ma_receipt_text_send, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA RECEIPT TEXT SEND>> White
