sprite $AzureIoTHub [70x70/16z] {
rPS5bkGm34HLWjBU_y8BJPfuF8vZzz9_rFX5UGRvdx5i81OiaItSiHGo1jYs84ZIzop6Eu4DY_99R5Y2Bqm-uXSiog991a_ir69a8NrmpO9LYxub5x3m9KjR
4jOj4ZMYPKjbasahbaBDb9dSiTHFERPGpl7yiYQr6v09c9cGJQgc_VNQPPl8J9Ljc4cekMsvD9DtOiSJVE4xbi9a4UFPebN087rum4_ZQKSEuu4OIqe3g9b7
C6_moCGA6So6UKibdHrcAtAs6aQ4cG6OxsvPmWp0sgIrVhFprCKmNHjsfK2CViFaWwGCiGZNhzSfCm_RMh0oCsejn_fQLxLbhAvHQH-BqzNridbtcOhUPZQF
UcJJYRYQ3AApdUFgjE-Igc0mRRKREhh4e6rtG8-VvOFHnK5xTg9pbi70OltZZrspQ5lH0qnOjDyNonSSMyOpAaujfV7smq87ba8z7ArwdCia_kt5XaNoPR5F
5iE3Kvq-9PIoVC9FDNcJk8miCRLY66J3KloZ5dcFXM-neDNGv7_c1m
}

AzureEntityColoring(AzureIoTHub)
!define AzureIoTHub(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureIoTHub, AzureIoTHub)
!define AzureIoTHub(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureIoTHub, AzureIoTHub)
