sprite mdi-archive-outline <svg width="48" height="48"><g transform="scale(2)"><path d="M20 21H4V10H6V19H18V10H20V21M3 3H21V9H3V3M9.5 11H14.5C14.78 11 15 11.22 15 11.5V13H9V11.5C9 11.22 9.22 11 9.5 11M5 5V7H19V5H5Z" /></g></svg>

!define MA_ARCHIVE_OUTLINE(_color)                                 SPRITE_PUT(mdi-archive-outline, _color)
!define MA_ARCHIVE_OUTLINE(_color, _scale)                         SPRITE_PUT(mdi-archive-outline, _color, _scale)
!define MA_ARCHIVE_OUTLINE(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA ARCHIVE OUTLINE, mdi-archive-outline, _color, _scale)
!define MA_ARCHIVE_OUTLINE(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA ARCHIVE OUTLINE, mdi-archive-outline, _color, _scale, _shape)
!define MA_ARCHIVE_OUTLINE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ARCHIVE OUTLINE, _label, mdi-archive-outline, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ARCHIVE OUTLINE>> White
