sprite mdi-arrow-u-left-bottom-bold <svg width="48" height="48"><g transform="scale(2)"><path d="M21 10.5C21 14.64 17.64 18 13.5 18H11V22L4 16L11 10V14H13.5C15.43 14 17 12.43 17 10.5S15.43 7 13.5 7H6V3H13.5C17.64 3 21 6.36 21 10.5Z" /></g></svg>

!define MA_ARROW_U_LEFT_BOTTOM_BOLD(_color)                                 SPRITE_PUT(ma_arrow_u_left_bottom_bold, _color)
!define MA_ARROW_U_LEFT_BOTTOM_BOLD(_color, _scale)                         SPRITE_PUT(ma_arrow_u_left_bottom_bold, _color, _scale)
!define MA_ARROW_U_LEFT_BOTTOM_BOLD(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA ARROW U LEFT BOTTOM BOLD, ma_arrow_u_left_bottom_bold, _color, _scale)
!define MA_ARROW_U_LEFT_BOTTOM_BOLD(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA ARROW U LEFT BOTTOM BOLD, ma_arrow_u_left_bottom_bold, _color, _scale, _shape)
!define MA_ARROW_U_LEFT_BOTTOM_BOLD(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ARROW U LEFT BOTTOM BOLD, _label, ma_arrow_u_left_bottom_bold, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ARROW U LEFT BOTTOM BOLD>> White
