sprite mdi-book-open <svg width="48" height="48"><g transform="scale(2)"><path d="M13,12H20V13.5H13M13,9.5H20V11H13M13,14.5H20V16H13M21,4H3A2,2 0 0,0 1,6V19A2,2 0 0,0 3,21H21A2,2 0 0,0 23,19V6A2,2 0 0,0 21,4M21,19H12V6H21" /></g></svg>

!define MA_BOOK_OPEN(_color)                                 SPRITE_PUT(ma_book_open, _color)
!define MA_BOOK_OPEN(_color, _scale)                         SPRITE_PUT(ma_book_open, _color, _scale)
!define MA_BOOK_OPEN(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA BOOK OPEN, ma_book_open, _color, _scale)
!define MA_BOOK_OPEN(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA BOOK OPEN, ma_book_open, _color, _scale, _shape)
!define MA_BOOK_OPEN(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA BOOK OPEN, _label, ma_book_open, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA BOOK OPEN>> White
