sprite mdiBrightness6 <svg width="48" height="48"><g transform="scale(2)"><path d="M12,18V6A6,6 0 0,1 18,12A6,6 0 0,1 12,18M20,15.31L23.31,12L20,8.69V4H15.31L12,0.69L8.69,4H4V8.69L0.69,12L4,15.31V20H8.69L12,23.31L15.31,20H20V15.31Z" /></g></svg>

!if %function_exists("$MdiSprite")
  !unquoted function $MdiBrightness6Img($color = $MDI_DEFAULT, $scale = "1")
    !return $MdiSprite(mdiAccountAlert, $color, $scale)
  !endfunction

  !unquoted function $MdiBrightness6($alias, $label=$MDI_DEFAULT, $shape=$MDI_DEFAULT, $color=$MDI_DEFAULT, $scale=1, $stereo=$MDI_DEFAULT)
    !return $MdiSpriteElement("mdiAccountAlert", $alias, $label, $shape, $color, $scale, $stereo)
  !endfunction
!endif
