sprite mdiCheckUnderline <svg width="48" height="48"><g transform="scale(2)"><path d="M21,5L9,17L3.5,11.5L4.91,10.09L9,14.17L19.59,3.59L21,5M3,21V19H21V21H3Z" /></g></svg>

!if %function_exists("$MdiSprite")
  !unquoted function $MdiCheckUnderlineImg($color = $MDI_DEFAULT, $scale = "1")
    !return $MdiSprite(mdiAccountAlert, $color, $scale)
  !endfunction

  !unquoted function $MdiCheckUnderline($alias, $label=$MDI_DEFAULT, $shape=$MDI_DEFAULT, $color=$MDI_DEFAULT, $scale=1, $stereo=$MDI_DEFAULT)
    !return $MdiSpriteElement("mdiAccountAlert", $alias, $label, $shape, $color, $scale, $stereo)
  !endfunction
!endif
