sprite mdiDiamond <svg width="48" height="48"><g transform="scale(2)"><path d="M6,2L2,8L12,22L22,8L18,2H6Z" /></g></svg>

!if %function_exists("$MdiSprite")
  !unquoted function $MdiDiamondImg($color = $MDI_DEFAULT, $scale = "1")
    !return $MdiSprite(mdiAccountAlert, $color, $scale)
  !endfunction

  !unquoted function $MdiDiamond($alias, $label=$MDI_DEFAULT, $shape=$MDI_DEFAULT, $color=$MDI_DEFAULT, $scale=1, $stereo=$MDI_DEFAULT)
    !return $MdiSpriteElement("mdiAccountAlert", $alias, $label, $shape, $color, $scale, $stereo)
  !endfunction
!endif
