sprite mdiEjectOutline <svg width="48" height="48"><g transform="scale(2)"><path d="M5,17H19V19H5V17M12,5L5.33,15H18.67L12,5M12,8.6L14.93,13H9.07L12,8.6Z" /></g></svg>

!if %function_exists("$MdiSprite")
  !unquoted function $MdiEjectOutlineImg($color = $MDI_DEFAULT, $scale = "1")
    !return $MdiSprite(mdiAccountAlert, $color, $scale)
  !endfunction

  !unquoted function $MdiEjectOutline($alias, $label=$MDI_DEFAULT, $shape=$MDI_DEFAULT, $color=$MDI_DEFAULT, $scale=1, $stereo=$MDI_DEFAULT)
    !return $MdiSpriteElement("mdiAccountAlert", $alias, $label, $shape, $color, $scale, $stereo)
  !endfunction
!endif
