sprite mdi-gender-male-female-variant <svg width="48" height="48"><g transform="scale(2)"><path d="M7 3A5 5 0 0 0 9 7A5 5 0 0 0 7 11A5 5 0 0 0 11 15.9V18H9V20H11V22H13V20H15V18H13V15.9A5 5 0 0 0 17 11A5 5 0 0 0 15 7A5 5 0 0 0 17 3H15A3 3 0 0 1 12 6A3 3 0 0 1 9 3M12 8A3 3 0 0 1 15 11A3 3 0 0 1 12 14A3 3 0 0 1 9 11A3 3 0 0 1 12 8Z" /></g></svg>

!define MA_GENDER_MALE_FEMALE_VARIANT(_color)                                 SPRITE_PUT(mdi-gender-male-female-variant, _color)
!define MA_GENDER_MALE_FEMALE_VARIANT(_color, _scale)                         SPRITE_PUT(mdi-gender-male-female-variant, _color, _scale)
!define MA_GENDER_MALE_FEMALE_VARIANT(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA GENDER MALE FEMALE VARIANT, mdi-gender-male-female-variant, _color, _scale)
!define MA_GENDER_MALE_FEMALE_VARIANT(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA GENDER MALE FEMALE VARIANT, mdi-gender-male-female-variant, _color, _scale, _shape)
!define MA_GENDER_MALE_FEMALE_VARIANT(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA GENDER MALE FEMALE VARIANT, _label, mdi-gender-male-female-variant, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA GENDER MALE FEMALE VARIANT>> White
