sprite mdi-help-circle-outline <svg width="48" height="48"><g transform="scale(2)"><path d="M11,18H13V16H11V18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,6A4,4 0 0,0 8,10H10A2,2 0 0,1 12,8A2,2 0 0,1 14,10C14,12 11,11.75 11,15H13C13,12.75 16,12.5 16,10A4,4 0 0,0 12,6Z" /></g></svg>

!define MA_HELP_CIRCLE_OUTLINE(_color)                                 SPRITE_PUT(mdi-help-circle-outline, _color)
!define MA_HELP_CIRCLE_OUTLINE(_color, _scale)                         SPRITE_PUT(mdi-help-circle-outline, _color, _scale)
!define MA_HELP_CIRCLE_OUTLINE(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA HELP CIRCLE OUTLINE, mdi-help-circle-outline, _color, _scale)
!define MA_HELP_CIRCLE_OUTLINE(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA HELP CIRCLE OUTLINE, mdi-help-circle-outline, _color, _scale, _shape)
!define MA_HELP_CIRCLE_OUTLINE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA HELP CIRCLE OUTLINE, _label, mdi-help-circle-outline, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA HELP CIRCLE OUTLINE>> White
