sprite mdi-inbox-outline <svg width="48" height="48"><g transform="scale(2)"><path d="M19 3H5A2 2 0 0 0 3 5V19A2 2 0 0 0 5 21H19A2 2 0 0 0 21 19V5A2 2 0 0 0 19 3M5 19V17H8.13A4.13 4.13 0 0 0 9.4 19M19 19H14.6A4.13 4.13 0 0 0 15.87 17H19M19 15H14V16A2 2 0 0 1 10 16V15H5V5H19Z" /></g></svg>

!define MA_INBOX_OUTLINE(_color)                                 SPRITE_PUT(mdi-inbox-outline, _color)
!define MA_INBOX_OUTLINE(_color, _scale)                         SPRITE_PUT(mdi-inbox-outline, _color, _scale)
!define MA_INBOX_OUTLINE(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA INBOX OUTLINE, mdi-inbox-outline, _color, _scale)
!define MA_INBOX_OUTLINE(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA INBOX OUTLINE, mdi-inbox-outline, _color, _scale, _shape)
!define MA_INBOX_OUTLINE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA INBOX OUTLINE, _label, mdi-inbox-outline, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA INBOX OUTLINE>> White
