sprite mdi-launch <svg width="48" height="48"><g transform="scale(2)"><path d="M14,3V5H17.59L7.76,14.83L9.17,16.24L19,6.41V10H21V3M19,19H5V5H12V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V12H19V19Z" /></g></svg>

!define MA_LAUNCH(_color)                                 SPRITE_PUT(ma_launch, _color)
!define MA_LAUNCH(_color, _scale)                         SPRITE_PUT(ma_launch, _color, _scale)
!define MA_LAUNCH(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA LAUNCH, ma_launch, _color, _scale)
!define MA_LAUNCH(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA LAUNCH, ma_launch, _color, _scale, _shape)
!define MA_LAUNCH(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA LAUNCH, _label, ma_launch, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA LAUNCH>> White
