sprite mdi-monitor-share <svg width="48" height="48"><g transform="scale(2)"><path d="M23 4V16C23 17.11 22.11 18 21 18H15V16H21V4H3V16H9V18H3C1.9 18 1 17.11 1 16V4C1 2.89 1.89 2 3 2H21C22.1 2 23 2.89 23 4M13 13H16L12 9L8 13H11V20H8V22H16V20H13V13Z" /></g></svg>

!define MA_MONITOR_SHARE(_color)                                 SPRITE_PUT(ma_monitor_share, _color)
!define MA_MONITOR_SHARE(_color, _scale)                         SPRITE_PUT(ma_monitor_share, _color, _scale)
!define MA_MONITOR_SHARE(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA MONITOR SHARE, ma_monitor_share, _color, _scale)
!define MA_MONITOR_SHARE(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA MONITOR SHARE, ma_monitor_share, _color, _scale, _shape)
!define MA_MONITOR_SHARE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA MONITOR SHARE, _label, ma_monitor_share, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA MONITOR SHARE>> White
