sprite mdiStepForward <svg width="48" height="48"><g transform="scale(2)"><path d="M5,5V19H8V5M10,5V19L21,12" /></g></svg>

!if %function_exists("$MdiSprite")
  !unquoted function $MdiStepForwardImg($color = $MDI_DEFAULT, $scale = "1")
    !return $MdiSprite(mdiAccountAlert, $color, $scale)
  !endfunction

  !unquoted function $MdiStepForward($alias, $label=$MDI_DEFAULT, $shape=$MDI_DEFAULT, $color=$MDI_DEFAULT, $scale=1, $stereo=$MDI_DEFAULT)
    !return $MdiSpriteElement("mdiAccountAlert", $alias, $label, $shape, $color, $scale, $stereo)
  !endfunction
!endif
