sprite mdi-calendar-weekend <svg width="48" height="48"><g transform="scale(2)"><path d="M19 19V8H5V19H19M16 1H18V3H19C20.11 3 21 3.9 21 5V19C21 20.11 20.11 21 19 21H5C3.9 21 3 20.11 3 19V5C3 3.9 3.9 3 5 3H6V1H8V3H16V1M7 17V10H9V17H7M15 10H17V17H15V10Z" /></g></svg>

!define MA_CALENDAR_WEEKEND(_color)                                 SPRITE_PUT(mdi-calendar-weekend, _color)
!define MA_CALENDAR_WEEKEND(_color, _scale)                         SPRITE_PUT(mdi-calendar-weekend, _color, _scale)
!define MA_CALENDAR_WEEKEND(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA CALENDAR WEEKEND, mdi-calendar-weekend, _color, _scale)
!define MA_CALENDAR_WEEKEND(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA CALENDAR WEEKEND, mdi-calendar-weekend, _color, _scale, _shape)
!define MA_CALENDAR_WEEKEND(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA CALENDAR WEEKEND, _label, mdi-calendar-weekend, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA CALENDAR WEEKEND>> White
