sprite $AI_Platform [64x64/16z] {
tPTdUiGW34G12Orq_mjdSSo7o-0rV_Ub5xdCOuYJVeoYze2Mz4nrFEBrUHp-1TGqfy2_WfAcs9jvIpC4_W98ucJuAx0G7WEwS7e6yd9uF4BkRiaXF_tw1IXy
0UXYU3p2kJlJVu3-2Ql1FBmU4D1_WqV8mnijXOzcpoCKtEykg-Ostp_B3pM0dsdf8aB_vpK2pL2G6b1txT8aeAMV7o7tiq1dxan4u6NSVt68Y167l7VneHxp
gx517HQ_e1jvdzy-PjrmOddkhW1m1uRg6ZU7pDsEZJmtcCExExdK8gSESyZTEO1pVW2SEWI91Duu-Mk0rS0duKbWv8-G4Gg1p2SBzFmHbcRpnfGsCcvEsFNV
zCa7BVVyYyg7UmSCPF5wllO_Erl1HfPlLRMer_aQfbhP0guWvVTTE7nV3fkzwxpH-fOsqj0-tn1ogNcwVNJWQM1KDga0dnTwUbR1xPiDTLTfy5soOoJ2klkA
HkNxPwUmdKqRxjfeCJDtdVhYxqTCKkOEh_FSNOCxb7D-CYtwnA77oA_Xi_26mnLa-Vc5dvuxv71ttE4pjlxyoDqHXo_GnC52U0p1khjrXvQcb6Ltwn7Mz8I2
C1jV__-nblHZ_04
}

EntityColoring(AI_Platform)
!define AI_Platform(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, AI_Platform, AI_Platform)
!define AI_Platform(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, AI_Platform, AI_Platform)
!define AI_PlatformParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, AI_Platform, AI_Platform)
!define AI_PlatformParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, AI_Platform, AI_Platform)
