sprite $AzureDataBox [65x62/16z] {
xTO5ijmm40JGOThxtpVH3or88pbChyh5tI8JB95uP5Lc62DSnfxrMQOHN29Hp_n21LhDA9vFFx8c7E4KiiqgWk0SpIe2eOF48i9C20FxP1MmHc8UuUCoOLni
fYxZwk6VXIl3UvBr95M49fCN3t-YE6iOqfMUykeJHW2WDHMAztaBdneDLdF1TtbV8G2Ccak1ZzIN306aLXJUi3S40BnM10Rp3dLJIEedCCXo5uPeT-3pMLej
CP3tWhirb8Fu1WDmDhkWstox2QMsomzDWH_asrtCWtpVS93l6wpDxnjIs_o-8RdDxniScmVvCnoaPWJKv_GDmQ3Xxhbu7iaR8J34hHOC06nVuBKoPaZVK60m
o671-bEfNrcGt7rNzWKfzr-swmN9S8VjQe4J39j9X2uAWcU_DPEjcCuWZTU_ACnoZpuNX7uWJ72PDxycnmNoomlqVy6lFKQCgZA4hy0sZ7obsq1mYTIjxjto
OW5gyn8vest-lA7FzxJDdpVq-Pus-JEQVNvFr_bt
}

AzureEntityColoring(AzureDataBox)
!define AzureDataBox(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureDataBox, AzureDataBox)
!define AzureDataBox(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureDataBox, AzureDataBox)
