sprite $AzureStorage [65x55/16z] {
xTK7ZYin30DG5pNo_lVzTRGj7ik_ruUctIG48WsH6VmoaFPAu0inUdk9u1V2-3i3_WS0wMPyCQy2OewBKtCKMeuJBzwn2l3UBiQPuw2sXEWvwjS4z1yVqBxn
AyJedmsZz8lGSXo8aRFzaES0beAUepCy4PvYlmFbo75GLakqBxY254iy3nY0oiL9c8YEBmbmFefU1KncW80B-l8Alho2gtsWYlqn2NuTMzTPtjPPm3NCPHV6
souOx_XH6oVloK503zwBNjTPkAEvH9aNf-Qej3adwbuIn3E-6RbdMMTzVf2kKPsXmGBcVedEYc_BDC7It0IuinRzFW1W3NPVvoC8Wl04Hex18vW4luKry5kW
j-bnAyEBDlHxKHwnxGdtf5MyU91B0qMRIrgKkTHZTy8JKcomrBquOMbYyxjonCeDrdl4MupHpkco1Eaz
}

AzureEntityColoring(AzureStorage)
!define AzureStorage(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureStorage, AzureStorage)
!define AzureStorage(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureStorage, AzureStorage)
