sprite $AzureDataBox [70x70/16z] {
xTK7SYCW38LXIQZ0tl--cqOQOtWof2V_DDTl7gxq8R6KsqHuNoWMJxbkGM8nP5SxxD4xS4fC4ifdCKqfcySYEr-INwC1AeIJW371F62MEi_vc43XCIngPkw1
MX15dpFVUfjOXspZI7eXYpehm90aaqDwKuPfJ7GCCoQZeukiJdC1269w_hodwBgeYnHCGMDw3gQWCRteK_0Ok8OLLzTfFn0e0CEaYGfWBACmKRHLbL88OYI3
GCOI26O28mcc6a9I349IJ1MCO2P8fnKQuudYNO5MMwN4UguGqRdYT5jA-JUlCTqcXuhX7qsiLEgTA8q9CLXfalkJxGfOqjjIWiROhbMgqANKFAcq6YgqJ5vT
UNZQwzcK2IdqfPG_HHyKkMzlnHXlpHX2Mp234SnW13COmGn6S0gHF8CHp3ICu0fzJ3S
}

AzureEntityColoring(AzureDataBox)
!define AzureDataBox(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureDataBox, AzureDataBox)
!define AzureDataBox(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureDataBox, AzureDataBox)
