sprite $AzureDiskStorage [70x59/16z] {
dTTHZkiW38LXm3x7mEn_lvU9IaekU0hzdgjVfZ922MinYIWQNj2eI8enx8cYu09UL5lixuA27enQoKaa9NsOgCHv2luDCnBfqG1F8xoC7ULXX0D4Vn2_madw
ZT1dbfkIiz59N2G4UdAfzUUjbjPo9F4QlJ2ecMlUaDOY2vbdoYfIZMl6xIFLul-OFkj_SAsrP3Dwp1iI7SqsZh_AOB3t7quPu2nYPLe3D6x5tuawT33xFCWL
o7qjiRHncARgiDv-n1_ZOY4_rsglOhabRZM6dhbB-PrQ1tgXgoaqdEzBQsNhQ9USItdjyaE9uIBbvsiLuQPVTYfZ64cknus2k7WOxI1KCzpd4RdKZKB9T1EY
5rXBEQtw6u1S5ez-57q2Nkz8BYKtPYHK1jeaf-6G_sZtxZWDjw8FhnTMZo8wIHyY_Ie1gkj2p_W5sWC9TSJaHMo1UiYMe6TuL87k7ubG1zK7a3r0G5rmXvIN
pUDZUylyI8ETRVVrlQAJsAh0RbWMcir1S7TaOQlHf66zDolpFKF0SwsSY9ze64BFTCGxvQ_YY34qOZCI4vAsq1-bIFkUX5lYzurHWXsZh3ySRHya1aSKSAUW
ANoIHBqMsG8n78Xfs1Zv-yF-7m
}

AzureEntityColoring(AzureDiskStorage)
!define AzureDiskStorage(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureDiskStorage, AzureDiskStorage)
!define AzureDiskStorage(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureDiskStorage, AzureDiskStorage)
