sprite $Cloud_Data_Fusion [64x58/16z] {
dPO7iiCW30L5aPwu_u5_mR-G-8c8x4ocPeUoja6Ug8eDMcMFEdm3NBTwXxy0AZ7L4zJODxpMOQ7Uu0dG8n-U0YMnUUTRMAYUdu3cVMFjg9vlQ2U-7RJh7Ur2
mHlkDwzKkwyHPTCEDW4CZxxeqZ0Q7aqkkeaz-Mtu3wXHkoQBFqBVWlSEalBdEB_OublM1sd7V3C7ZFYTjbi6k_pn_ODCwY2lWJA_zcvkoshhD_t1rz_XYQzp
sENF5twnDZJgpv4Modt-3blRxNsRm2ThGylvOt9_3vk7VePc2P-FFZ6aV9iG7vdnXuNVTtGaneTE_8wMZAzb0lOXxQ2-hlFlqVnDf72_E_xmqA_pxMM-b0K9
V9LlZFY4wTENubs_iwCdxuCUVIYHNiZcaI-GHhwIKFGBs1ZTsERngyTWi7PnciCxI3lrExi-vC7vzOMt8mqJsFdrZRSZ3HEeC73GZj5mskwzXf20YlDsvmrD
GWhEsvs-1arsD3XsDfhiAKrls2_QRvF_1
}

EntityColoring(Cloud_Data_Fusion)
!define Cloud_Data_Fusion(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_Data_Fusion, Cloud_Data_Fusion)
!define Cloud_Data_Fusion(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_Data_Fusion, Cloud_Data_Fusion)
!define Cloud_Data_FusionParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_Data_Fusion, Cloud_Data_Fusion)
!define Cloud_Data_FusionParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_Data_Fusion, Cloud_Data_Fusion)
