' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $bot [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $botIMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAURJREFUeNrtmbERwjAMRR2gpYKGHEMwQnZgF5ghDMIEDJARGIILVRoWMMolFQUxZ1txyPt3qiW/WJElGYMQmrMyBR/2R59WM8bF3G8AAAAAAAAAgHeAv/ZiF7FCbBc55qdYJXYSe6QAoD38XWyj/PEasYMvhBApUI5weNP7LFP4BxQjprC371WAIHLl/sJ+8U0VAAAA4v8DbGLzAK/5ASkAAHqBoHVZ+x3g7Y8UAAAAAAAAANALeKn+6MutYvx1CjegGvEDVikAOJtuQKmtpvftpWWAQF5iV9ONw7di68gHb8fiN7GjSWQsHuvNrtJjUAYBwDzASZq7vxA/ybY8Ou0OM8fDj7H7C1EmB3eHLilQTvDwxjjuDl0AFBNO8cHYXXoB7d1fyPdHHuIGUAYBAAAAAAAAAAAAAAAAAAAAAAAIIfRHegNGEiobTGeeZgAAAABJRU5ErkJggg=={scale="+$scale+"}>"
!endfunction

IBMEntityColoring(bot)
!define bot(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, bot, bot)
!define bot(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, bot, bot)
!define botParticipant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, bot, bot)
!define botParticipant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, bot, bot)
