' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $chartwaterfall [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $chartwaterfallIMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAALdJREFUeNrt2bENgzAQBVCT0KZLA4tSs0zmyDIp07AAXJHSBUiQKNz70jWWJeQnn2WZUkQkc5rK2Lxizmlyyb4DAGQHaH/wza1nzKFnkhYAAAAAAAAAAAAAAAAAAAAAAAAAkCx7vAn+9X8ELQAAAAAAANwDvpqj7wmb7iVaAAAAAAAAAAAAAAAAAAAAAAAAAECy1N7LXlF9ljXXdsAzewsMUe8sANfK2BT1iOqi7lG3k615LCIinyx79gruveivPAAAAABJRU5ErkJggg=={scale="+$scale+"}>"
!endfunction

IBMEntityColoring(chartwaterfall)
!define chartwaterfall(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, chartwaterfall, chartwaterfall)
!define chartwaterfall(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, chartwaterfall, chartwaterfall)
!define chartwaterfallParticipant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, chartwaterfall, chartwaterfall)
!define chartwaterfallParticipant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, chartwaterfall, chartwaterfall)
