' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $cloudlogging [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $cloudloggingIMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAPlJREFUeNrtmsEJwjAUhqP26kW8KO6iO7iLQ3QQJ3CBjuAOUm89uED8QS9CU4KEaPK+D/5LKej7zHtNis4BAACAVWaB6zulVQ7KJvNn+5w1N4Hir8rKwgqYj1xrrRQfErC3PgN8ZK9WuwJMgQDrApo//E5Z9wG0AAKYAcWcT1gBCEAA+4DkM4MWQAAzgH0ALYAAZkDVeN4H0AIIQAACEIAABCAAAQiIOgv0ynZiL10yfcwK6Cr+wbsYASdlqLD44V3bB4uRGx/K2b3+HrdWloUXflcuylG5uamz8S/O4wnu5ymAAAQgAAEIQMB3pHjG+pJroAUQAABgmCdh9hcjwltm0AAAAABJRU5ErkJggg=={scale="+$scale+"}>"
!endfunction

IBMEntityColoring(cloudlogging)
!define cloudlogging(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, cloudlogging, cloudlogging)
!define cloudlogging(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, cloudlogging, cloudlogging)
!define cloudloggingParticipant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, cloudlogging, cloudlogging)
!define cloudloggingParticipant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, cloudlogging, cloudlogging)
