' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $directionright02 [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $directionright02IMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAATlJREFUeNrtmT8OAUEUh9euQiMSHXEOSlRO4C46u524kUqUSodwACdgJFNsFs2a97wx35e8YIvN/j7P/DFZBgAAAKnSCXCPu8A91chT7wAEIAABCEAAAuyx9SVO12j4sva5SqkDNo3wpXQnWBNwdHVrXBOVYE3A2dVKU4LFQVBVgtVZQE2C5XWAioQY9u4zVwdXgzcivp4iiwgEXP3ssHbVq11f+NfTvwsQlRCLADEJocaAiau9f5jRjwS1GhOKQOEvrqau+j/skFadEGIafH7zw5S3w3MjWVr9BEJsh8eKa4vga4KY/hESWRDlKYePRYDoUjhPObx1AeLhLQtQCW9VgFp4iwJUw1sUsNQMb1HALns9FxA9GLF4MlR9eJ+MAJXgMe4FEIAABCAAAQhAAAIQgAAAAACAADwAZR48mT5uC1wAAAAASUVORK5CYII={scale="+$scale+"}>"
!endfunction

IBMEntityColoring(directionright02)
!define directionright02(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, directionright02, directionright02)
!define directionright02(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, directionright02, directionright02)
!define directionright02Participant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, directionright02, directionright02)
!define directionright02Participant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, directionright02, directionright02)
