' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $directionbearright02 [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $directionbearright02IMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAWhJREFUeNrtmDFOAzEQRReSkoqO1FyBko6WGlCQcgXK1LlBjhAJENtQhGvkEOk4AUUkIhhLjhSNSIR27RlLfk+awt7G/+1sYrtpAAAAoFZOCljDj2em09o7AAH8BnRjILWQ+pBqjdd8J/UsNUyRadgx/EtcyH2cawsJb/IJLOJCtAyP8N8eAkLbbw90hHX4Rw8Bod3HhhKOhW89BFhKyBq+799gbgnZw6fYB+SSYBI+1UYotQSz8Cl3gqkkmIZPvRXuK8E8fI6zwCEJtyWGz3UY0hLCeFJi+K5ngf9KaOKbn6iO2OfGM3xOATsJx0Jcxudu4T3vA8KR9U3qfG9uax2+z31AXx6kXtXck9S8hhuhIH32x+cy93gTHgKu4ve/YyM1depEFwF6T/Auta5JwLUaLxtHPASM1HhVm4ALNf6sTcCZGn/VJqAoEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAAAAIBK+AWqAl0NuqFmIwAAAABJRU5ErkJggg=={scale="+$scale+"}>"
!endfunction

IBMEntityColoring(directionbearright02)
!define directionbearright02(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, directionbearright02, directionbearright02)
!define directionbearright02(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, directionbearright02, directionbearright02)
!define directionbearright02Participant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, directionbearright02, directionbearright02)
!define directionbearright02Participant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, directionbearright02, directionbearright02)
