' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $distributeverticalbottom [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $distributeverticalbottomIMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAATZJREFUeNrtmrENwkAMRS9ASwUNiCEYITuwC8wQBmECBrgRGAJBlYYFgpFSUYDis9GFe0/6rXX+uVNs2SEAQMlUTnE3oqOoFq0SY91FUbQXXcdgwCv5i2hhHLcVba1NmDgY0DgkH/qYjXVQDwNqxydrHnvmcMi18TPrPsTO8gaMCgzAAAzAAAwoGY864Pb2v+6MY2d/A6LjB4tjMODQNy7WtH1sU6YOB32ITn0bvBTNDdrhs2jn0Q4DQNlUX/rvv8+ZUhgDAAAAAOgFBmE5/08laX+gUibvMf9PRbU/oCmFmwyTD0G5P6AxoM74SQ8+m2YuYD3/TyVpf4B2GAMwAAMwAAMKRlMHeM7/U7n94gbEjD9o/IUBXvN/i2Zo8P6AZj/Aev5v0Q6zPwAAKtgPoBTGAACAcnkC2k8tz/7AS/0AAAAASUVORK5CYII={scale="+$scale+"}>"
!endfunction

IBMEntityColoring(distributeverticalbottom)
!define distributeverticalbottom(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, distributeverticalbottom, distributeverticalbottom)
!define distributeverticalbottom(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, distributeverticalbottom, distributeverticalbottom)
!define distributeverticalbottomParticipant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, distributeverticalbottom, distributeverticalbottom)
!define distributeverticalbottomParticipant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, distributeverticalbottom, distributeverticalbottom)
