' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $documentmultiple01 [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $documentmultiple01IMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAYZJREFUeNrtmz9OAlEQxncFS60oELiDpa30NGAMhQfwBh6CC8AFJKGiMPR7BRMLLoBWVJYW6/eSpwEKCPtmNu/P9yVfyex7P2ZmmeVtllEUlbJypbhdeAL34Rvh2Bv4GV5JBGsobf4dvoOvFOJfw4/wB7z2EcDMbl5TZt0jCQgXCou7r6l8L+EFPHQJ0qzwmfJEH+kI95nD6/3Yze9CGMNLXzJAW2MLQSQTQgSwlIQQIgBRCM0KNe4bhIVLTwg1A8QyIXQAzhBiAOAEIRYAlSHEBKAShNgAnIIwSAHAMQhTiVmgbn0ezBelQ6xeiBlQaAYPAcALvE0ZgHkEdgvP4S/p4CH0gD8IT0LPE5K4C0Q/DhMAARAAARBAqL8DSuX4OTOAAAjA6x6QMwMIgAAIgAAIgAA4C3AWYAkQAGcBZgABEIB3PSBnBhAAASQjjXo3/+V3PN2vOW/U1c6AwuMvvKijBFTP9Dhoa9e2J42Xpr7hV7gNtzKdN8fOkTlX9AY/2PKkKIr61y/2ukb77GbhEgAAAABJRU5ErkJggg=={scale="+$scale+"}>"
!endfunction

IBMEntityColoring(documentmultiple01)
!define documentmultiple01(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, documentmultiple01, documentmultiple01)
!define documentmultiple01(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, documentmultiple01, documentmultiple01)
!define documentmultiple01Participant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, documentmultiple01, documentmultiple01)
!define documentmultiple01Participant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, documentmultiple01, documentmultiple01)
