' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $ibmclouddirectlink2dedicatedhosting [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $ibmclouddirectlink2dedicatedhostingIMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAT1JREFUeNrtmssNwjAQRBPIlRMc+BRBC1ADvaQI90EFFAAtUARw4kQBYSPlhJSEAOu18RtpTpH8eXHsHStZhhBCKF3lyu2vxE68FS88z+0mPopL8cUCQD35s3hq/JLv4nUbhJFixy6AyWfNGFzbQ00Am4A+9daxFIqdLj3vN6+qOsbiZQVEIQAAAAAAAEDK0qwDclYAAAAQ/X3AkDyfd9TiFnvKW/0XEeR5s0/A/fvk+wBsUtgDCsU8H1odkHMKAAAAXrOAdR3ACgAAALgPYAUAAAD9e0Cl1LZ2HTCk/WvqK+CUMoD6B4nS4hi01te/yFQxnuucAgAAQDBZ4Nd1BPcBAAAAAAAAAAD4qwPqDL1UzPdDdLVYAacY8rwmgLLJ0kHn+W817nj2EO/Fc/FMPDHI8wfxrivPI4QQQp/rCTzPJzjWJXpLAAAAAElFTkSuQmCC{scale="+$scale+"}>"
!endfunction

IBMEntityColoring(ibmclouddirectlink2dedicatedhosting)
!define ibmclouddirectlink2dedicatedhosting(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, ibmclouddirectlink2dedicatedhosting, ibmclouddirectlink2dedicatedhosting)
!define ibmclouddirectlink2dedicatedhosting(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, ibmclouddirectlink2dedicatedhosting, ibmclouddirectlink2dedicatedhosting)
!define ibmclouddirectlink2dedicatedhostingParticipant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, ibmclouddirectlink2dedicatedhosting, ibmclouddirectlink2dedicatedhosting)
!define ibmclouddirectlink2dedicatedhostingParticipant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, ibmclouddirectlink2dedicatedhosting, ibmclouddirectlink2dedicatedhosting)
