' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $number9 [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $number9IMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAOdJREFUeNrt2bsNwjAUhWHzaGkQDYgdGAHmYJD0tB6EOcgI7IBCl4IFzLWSigJsUC5J7v9Jp4uV5MgOTnAOAAAAAAAAtkyUzrOVeMlBsv5w7F1ykRSS2xgKiDd/lSwzx9WSXdclTBUK8F/cvGvH+K4vTqOA/Z/GJpkrFLDJXHbhzdhBzoBeowAKoAAKoAAKoAC7NHaC1cuOLlibAaX1JVC0r7a9NFM4x0Nyds2HkJVkkTn+NPRnQBQ/ahwTjw1jWwL8DFIABVCA6Z3gL0/3yvoMKC0XULe7yNEsgVSqf40BAAAAAADAmicjVhnreAkTFQAAAABJRU5ErkJggg=={scale="+$scale+"}>"
!endfunction

IBMEntityColoring(number9)
!define number9(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, number9, number9)
!define number9(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, number9, number9)
!define number9Participant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, number9, number9)
!define number9Participant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, number9, number9)
