' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $numbersmall9 [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $numbersmall9IMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAANpJREFUeNrt2L0NwkAMhuHjp6VBNCB2YASYg0HSp71BmIOMwA4odClY4DCSq0jhQAgTnd9H+qpYCrHOiUUIAAAAAAAAAAA/Jsb320qi5CBZ967dJGdJJbmW2IDnw18ky0xdJ9lZNWFq2ID4xsMHrYlWP8qyAfsf1X5lbtiATWb80ovaIk7AKNEA7w2wfAe0vdlO3k5A430EKl1yRmVmeK+75KQr8EqyyNTXpb0Dgq63x4FrqfQR4DNIA5zvAZ/Meuv9BDSeG9DpzlDsCAz5y19iAAAAAAAAAABPHkBoGdsSNV1JAAAAAElFTkSuQmCC{scale="+$scale+"}>"
!endfunction

IBMEntityColoring(numbersmall9)
!define numbersmall9(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, numbersmall9, numbersmall9)
!define numbersmall9(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, numbersmall9, numbersmall9)
!define numbersmall9Participant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, numbersmall9, numbersmall9)
!define numbersmall9Participant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, numbersmall9, numbersmall9)
