' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $sidepanelclose [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $sidepanelcloseIMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAX9JREFUeNrtmjFuwkAQRTeBNlUogNwhuUIiGvrchRbc+h45AU2aKFwh3CHQ4CoHMLPCBdrMIkfBzDDzv/QlYy3Ff95dz8KEAEEQBEGQV91k7j+QS/ILeXTlGbfkT/KM/N0GQAz/Rb439rAr8lMK4ZYZWBoMH5pMZXqTA/BseMn/ytZnBo1b7hM51f/8/rlVn8jGzgBXAgAAAAAAAAAA0Kt5487UVx5+cfS58DQD0vCL5jTnAkAaPmpHfvcAIBd+Ql5bB3Dx8JoAiITXAkAsvAYAouGlAYiHlyyEuPBRg3D4QdZ0KZwLj7OAFwCFphkgtQcURzV+15tgrXUJcDMhboIf5Ecve4A4BA2boCgELW8BMQiaXoMiELTVAReHoLEQykGYeqoEUwjxurRUCP2lWEqv3QDoNDgOQwAAAAAAAAAAAGwPX2wlHRvNuwmHVuCTM2Bl+IGv2iyB+D98ZTB8FZgegx4z8If8Rh42p7C7Kw8e2+WX5NfAtMtDEARBEORXe4rLSChvBpkeAAAAAElFTkSuQmCC{scale="+$scale+"}>"
!endfunction

IBMEntityColoring(sidepanelclose)
!define sidepanelclose(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, sidepanelclose, sidepanelclose)
!define sidepanelclose(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, sidepanelclose, sidepanelclose)
!define sidepanelcloseParticipant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, sidepanelclose, sidepanelclose)
!define sidepanelcloseParticipant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, sidepanelclose, sidepanelclose)
