' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $whitepaper [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $whitepaperIMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAXxJREFUeNrtmzFuwkAQRcdAk4IiIk2iHIKCnpyK1riMD8IhqMgNcggQFQ0XgFmxhYXsaNbMklnv/9LvFrT/MbMeW4YIgqCcVQjXfbJr9hf73ViGI3vHXrH3MQC48L/smfEf88Seh0IYCdbUCYQnv8c69EMSAMuEWjp4rxPBmo+e58azdPljryoVMGgBAAAAQN6aKH7XxcjUigoAAAD4nzOgQAUAAAAAAABgEsQkiBYAAEyCqAAAAAAAAABMgilcPdACAJC5ih69XaACAAAAUtKCbi9QRZ8DrIbfsl/ZL+wqpwpohndas8tcANyHz+oM6Aq/zqEFgsIPDUBw+CEB6BXeOoCVDxYtvGUA7nL17YMtYoW3CqD0AcgH64LwcPhUzoA2CCrhrQKoGhXQBkEtvOV7gaoR6h4CaYW3fjPUBYG0wjtJnu4cqMd7+Ip7KFtaQiW89Az4MXgmqISXAnADyckYBJXwTmPBmjN7Q7e/y72xp5F6XVqJO63wEARBVzNWP6ltKe/gAAAAAElFTkSuQmCC{scale="+$scale+"}>"
!endfunction

IBMEntityColoring(whitepaper)
!define whitepaper(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, whitepaper, whitepaper)
!define whitepaper(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, whitepaper, whitepaper)
!define whitepaperParticipant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, whitepaper, whitepaper)
!define whitepaperParticipant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, whitepaper, whitepaper)
