sprite $voip_gateway [48x16/16] {
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
00049AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6100
004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA800
009AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAA308AAA704AAAA308AAA604AAAA308AAAAAAA00
00AAAAAAAA006AAA400AAAA006AAA401AAAA006AAAAAAA00
00AAAAAAAA87AAAAA79AAAA87AAAAA79AAAA87AAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
00AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
002222222222222222222222222222222222222222222200
000000000000000000000000000000000000000000000000
}

!define OFF_VOIP_GATEWAY(_alias) ENTITY(rectangle,black,voip_gateway,_alias,OFF VOIP_GATEWAY)
!define OFF_VOIP_GATEWAY(_alias,_label) ENTITY(rectangle,black,voip_gateway,_label,_alias,OFF VOIP_GATEWAY)
!define OFF_VOIP_GATEWAY(_alias,_label,_shape) ENTITY(_shape,black,voip_gateway,_label,_alias,OFF VOIP_GATEWAY)
!define OFF_VOIP_GATEWAY(_alias,_label,_shape,_color) ENTITY(_shape,_color,voip_gateway,_label,_alias,OFF VOIP_GATEWAY)
