sprite $Cloud_Routes [64x64/16z] {
tPTNekim24GH5WpiVy6loK-t3GxwpRabJQJCGTYHDqFD7p2LPopmIDXpEU85CAbHn4kWKkATUfUA2z40bt06eWL6DpmEhF7ovs_0-_NU3g_l4Ao-_mOcuW3C
LdZz2EsqtiuQtsc4VNTwiGZxxbGKzJP0lAwNuV455Evy_6N6ZUbVLiW_739t9fyN-vSceGwDreiJpvCur0XQFx0jLPgLkREzEk9hcnA7n1s0syrSRr-1VvUJ
ZZ84umuyNMH4Hgg8P_m0vRvRkNdQgXi3f3nGbQV_pt0jgDOX2fBBwPFpXt661mUnCrplF_coOkjXNBapVCfF78K_sndcVPlEKGtUFqkUbFspsyIg_hqY6_qh
0_N-YUVzCvQYOl_cNhAPT2Mjjznzk35-3BWUvbVk-VLZ1yt--4vT7idyx7MvYX9t6pivVf31EiwENqGCuWoJhnpMWvw-zBdOwLCVd9_xSdTjXznTts7jxjpX
50uEmoCEZzsTEtGfqMDtvn6QF351uDbpncnyVtmZVWC
}

EntityColoring(Cloud_Routes)
!define Cloud_Routes(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_Routes, Cloud_Routes)
!define Cloud_Routes(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_Routes, Cloud_Routes)
!define Cloud_RoutesParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_Routes, Cloud_Routes)
!define Cloud_RoutesParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_Routes, Cloud_Routes)
