sprite $AzureActiveDirectory [70x70/16z] {
vTZBRYin30FGw64v-VyFlhTrX25g8X0KPnUkkZfWX_CmSll2w2SGyV41nJty0uX7s25YImazHPOISZAFftB2Y4E94mJAU7yUXn9-X7WSC4RA6tkhinBIHaYP
SpOPSLBcRw9xPP4asenloaH6Rnva_edt4IY8DUOX1T76FAGWqa2Wz1clbNflgvNxJwAD-8QiZCOyfDolM75bAOIiQ0intuY2OS7CL8sKZ9H82gfG29h5F0bi
2ad120cai3HeO_mJXGBfyV1j7W9OuMotZS1eAFoMq7Uwy7CWrbJokoAIyxYWJg7G2zZdl3RMz0g5YkZw4yynrM65N-7ZETJ08sXR7LBeNMVN7UXP1NN42YNd
bS1TZ3Aeewpml0xZgIeStUgm4d8LsHycepgl5ASYaaPHntXU5F4NRmOQtMZUD504aLTrZEQbxq1L1uhjLpNgZu2XZc5UWx5K2jNHhBEKd9VVbNMTXEsQ5qNq
LaIfJiwB8juy1brB3XYOjrU7v-MKeqjC-f2rwnXwe4YxphZplFqwW-RjnQ0qY_3eW-PjnvwAd_zOWNaFOdRxmlm7
}

AzureEntityColoring(AzureActiveDirectory)
!define AzureActiveDirectory(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureActiveDirectory, AzureActiveDirectory)
!define AzureActiveDirectory(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureActiveDirectory, AzureActiveDirectory)

sprite $AzureActiveDirectoryB2C [70x70/16z] {
rTK7rgCm40DWJ_4CSFy3Rt0CId7VhbV-cky9H0d_LUYNAAg_137vQKHKpUZd4RMVPLYVYltKF7efyUUGh9WkAmfbdP4tnNWPWR8u52kKPORqMx5r18hxxDxw
fVWPNK6WU8xCpmF5x_0YeY1c6DQMuZGvJrcnkJCBPPxHdZ9osSY0ikayeb_8jidKF510fF3WF4W1sPmc4NKGY8_E0mK8OkE8YB30U4jvRoa8Pv9IWhGtJmQW
52Kf80K1IbdYuZm2eQv0sZTwLr2Xhm3Q_RqAY46bV6FAal8r4ykqOk-VHvqPHTA7pUvvg75sf7L6ulaTDWufmufHm1j6SFUWpe2YGOwKpS-mP0Hr1XG9_130
M62zmwZJLZXinvLhx-ywqb68ZZkRKKWfrMah3WKNJQbEGp7Ve32KLXtnGg1K7tM4EXK5PMBz3S0PhYk-vuK2Kgy3HQEVCNrssLCRqyOB2MSPYj4pbfiuF-B7
pc6W3abMd1F2z_6S2ivChywbQ5AYNqnaZiSPgR_nKITwJb8mzSwyO-nE7Kma3qGSZCY1eTfrsFnAJ0U4gSrmvNNgH4U8s943uRA2EkQ8aZgoGz6oWJhkY94L
RWACNGpd0qBUJ6yV4I9gNa_CqT09jnG9esaf-eSLRIWSXiDI2uL_Cpy
}

AzureEntityColoring(AzureActiveDirectoryB2C)
!define AzureActiveDirectoryB2C(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureActiveDirectoryB2C, AzureActiveDirectoryB2C)
!define AzureActiveDirectoryB2C(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureActiveDirectoryB2C, AzureActiveDirectoryB2C)

sprite $AzureActiveDirectoryConnectHealth [70x70/16z] {
rTC7SkCm38LXD1BW_I-yA-i5YXZQY9N-JqdrDo0XqP-AFmKnfOzdrkKJ4EkTwMFffdoK4TkL_a44Ill8UbBfzf6RJQNhnn0e5_UjgI3-26BzEYEMzUpAUcR5
lLr73CQMNLfFAexqoir2yIEvY9YZvnYnjOBuoPjTA_qIOdw1iLBnHZLIAs7bUceb8hH0AYNsvE6EAoMGSxMUkOce65it8SZVZwYAA8ovLjyiX2trh6Pq8QIo
XlJ-UXH2PZvtb-6r02K__5eQ_zCPIM6j31Gl2dvseKoojHBZ24ZMA6Dze9oG4K1M38dULyQf09B9VXpi-fuIunpKBB1ZnZXhPLGn7fG7urYKYh4XpbkkbR3f
Y6elQIwzL1griueJFHZ7nfk4-4mJqNASjUAv4vkV51BB1EEibKQU7uvTovRZw4fXqdpAT0pD0S3mQfpvTYr742CA9yBrU3qE51p0RWTgGSHCv0TVZ6EUespT
3XJx3pBsrhTpl19uZp2A6L4RH8B1Odwfr-EG7k-q4aKGST-aCMuW-3bvEuvvnnxiHc6683wTj1o7I2WVaRoExkDOK3KESC815DzaGLdn35ABWHm7IeG9LUE8
U-Gd1GT2IgWOXvl7LWxJ5qWv3f1asWAfn-c16fm9AUAJql7k7ONGkz93qPlhY-tKCPH6w62SdaYjXmjb3KYZf-9s_e34TXgb3yO-dEdZAVtc_W4
}

AzureEntityColoring(AzureActiveDirectoryConnectHealth)
!define AzureActiveDirectoryConnectHealth(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureActiveDirectoryConnectHealth, AzureActiveDirectoryConnectHealth)
!define AzureActiveDirectoryConnectHealth(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureActiveDirectoryConnectHealth, AzureActiveDirectoryConnectHealth)

sprite $AzureActiveDirectoryDomainServices [70x70/16z] {
vTQ7ZgGm60DWahy1x__0DnaiHMC5VfhQhU-sxtwonhJf3wQ-WHIr5nHLrnSGTPU7Y7mLhu-HfdXvW5I5yeGfsXL_Y42ncuh-A3Vt5b9SRY6atDcxAYbtXYgg
h4G4Cpd2IhJu9KLP2SGk849AzEXDHECdSd4ULf1wzPM5GYbt40tEb4TpnNCaL_Az9LVcJpIVXyD8YwIlB8U8BJL3E8GWktiF3L4Ya2Xd4H6fLLX18fq7GWkK
0UJ9F11OOSds4G2aZ2NbUQW3AsDfeRsfGzO57sZlqebSiLZtBdroMl6F0iPxbQoECDAK9RY8w4QUK-ohh3EkCZKSY6f5dLnnAEjMn9hR3nJKaO5229Iv5TYM
qduU2zKPAmRb4okEkMT1bOCwmWYKTMu6JeNI6U7HMN630cRBTeTAwWWXNLbG1Dcfmufr1GoAq1az6brw5LPMlZW8ro4522iJajJfYh7IGbs6TQGhOQGWTJfN
Hs2CbOKHrE7HcrALb9uulh5Lm18wrTqkE2tpEfyFDbIGCb3ub6ZHaK9pftN43fNL6HZLAJPKQEwaJlLKyVmfn68EFr0MAoUUgsnkYHqb97zcxShiIWfgvAbT
aU-NKAX6bWB59qIWK8qijIdrznknjchNOZPHf4p_VVu1
}

AzureEntityColoring(AzureActiveDirectoryDomainServices)
!define AzureActiveDirectoryDomainServices(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureActiveDirectoryDomainServices, AzureActiveDirectoryDomainServices)
!define AzureActiveDirectoryDomainServices(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureActiveDirectoryDomainServices, AzureActiveDirectoryDomainServices)

sprite $AzureActiveDirectoryGroup [70x70/16z] {
xTM7ik8m30LGTGdz_mSlJbWSa98PixsSD-srYtIT0d-g_uW7X6_0OW_wSH2f7J5yGkoDuYSX5Qs7T12MiBKKLg2T45YWLgplH5Qqm-1YjTFyfCZCkDZHYdBQ
cby5hdKxBs6CF92bb5bCv0lgKnfklj7HMxwADgNywpHICDzfb-8NT3OxtLPJ6C2pW8RvEGAuPK5GYPy3WAm4Al9JsgSGDFHg8OZpNgxxZV5rfm3z6RNa-Syl
70OgAGOzYuOZREnwbEiO9tYuDTtsj9-asKdX3BAQnv49mHF6N8TFCyJkK6QE4Plf8uSYmt8Nba5NJqn6H1Op5KBSWnMtZ3iYKbKY6XqPdh-V5OzinvGRfHtt
1RCz4KxpnuywQ6VjEObDWfFQMmpJfZrkiIDy8Zl8mMcGxh79DZGhYHru3ZH4SnkG3TrAziAV_UO1dhtEg7Ix6ySRHAHvO5qf0yzkwp1CTCio35fLkzsDFeou
UK28LuI3UB5TCbwV4EWDnS6y6CD8y_WLRnZUiNi_JFCgyDReLxrnoyg0l6M8vAsi0iHxX7AMKe5vJsgtvokXds7lHHPElggc14eiGoWibZ4K7ilqkwGO5F61
7vMYtsKZ_2udlHx3q29PmF1d-kyB
}

AzureEntityColoring(AzureActiveDirectoryGroup)
!define AzureActiveDirectoryGroup(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureActiveDirectoryGroup, AzureActiveDirectoryGroup)
!define AzureActiveDirectoryGroup(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureActiveDirectoryGroup, AzureActiveDirectoryGroup)

sprite $AzureActiveDirectoryIdentityProtection [70x70/16z] {
vTO7SlKm20HW2rXq_nF_nOrdhKSFuqmDKzA_x6XnMNxXo8yWiFT8Sq1VAt00yXfnl6RCDmNj1Q9-A2yOyL1Gh-TJiJeIIhLlX59dp4S5KgY754Shr7DLrazR
wMH3sJ-l8Xx6GmQ3uZ5MGnn-6KrtJCfpHdskkAGwdYkzUqlMmqeWlVjNnLaPa0I3gTAFGROULlh7MAuULlfbD5CFAtqOITSJIkTfQGHnAIOPt0cXCEI9wnYa
a0Jkc0HIIAA-bG1IYAA-XGLMU8Q-1IWeV9UmYcAyBi-LjlvTssFOzea-K-pezlnZZJXPfSML5mTBSUQAVcugulzJd8c2sB6rRzFnbO3ZtDVR4Ek7fKN7Ut5p
9KxrG3PLnZX22jKRnd4nNU8qti5va7Px1IZ5uNev25y1Onogbu9aub2zExAhIouErxiY883YsBw3Xs8KPFBcSBk3Pxq8mvRPD72SiLwdKyt4YNgJxtQyW_lG
qdmVfTBvjIuR9qh_Nc-YzEoBuMm7-SMx5eU2bE9GlQKuithJfLEzXMcWKosDol8Bvoy
}

AzureEntityColoring(AzureActiveDirectoryIdentityProtection)
!define AzureActiveDirectoryIdentityProtection(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureActiveDirectoryIdentityProtection, AzureActiveDirectoryIdentityProtection)
!define AzureActiveDirectoryIdentityProtection(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureActiveDirectoryIdentityProtection, AzureActiveDirectoryIdentityProtection)

sprite $AzureActiveDirectoryRolesAndAdministrators [70x70/16z] {
rTO7KYmn38HXITsokF-5Nt21InEi5Hc-YgH_RTAq_0e6-3-0oLifFO6y2NnwLqVzYl9AvhVqNITPv3LyXzB7iGNfib6GBXy5jezIaXwCalKlzFuhZPfBXuu7
UfLuuDTLv4igBYqU9KWBegJI4vKXJNmgGBfY7ndIXcqaLFfOtQVFgqWVgqWVYkz9au8EFqQSXBxwGKzHnZe7HVqVlAOnsJoL0QRftVRAvppkdxgSJJ5jhfRT
050HDRDzXvxOBcylgiYocH4mgphOZnxBZKmV3YXSZqARzXtr_MDGnqJO7KbOFDanex0DBGS7ym9msXRAgN1u1H9spwFSFfPVWRplC2BArU9vZ72o4upufvvX
AlyWLnoMUKprE4NQHNo1V9bSgJQFvKgw5d2Q01Ox9iAOSiLfnX6d2gk94AkIh4QgZDWIt5M0O-RHViAuLW03wUDOiMWu_en0pawge5TPZLcPF5KyEbOZLSYn
AgDR0UnGMTTAWwKMwo2hiZgpyjGHi0JCF9-bDh2jwAeqE6uhjjPAJ_1QGRa7wskjYiYYAzFjO5qcC_O1pnN8ks1MvBqKLFcn_W8
}

AzureEntityColoring(AzureActiveDirectoryRolesAndAdministrators)
!define AzureActiveDirectoryRolesAndAdministrators(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureActiveDirectoryRolesAndAdministrators, AzureActiveDirectoryRolesAndAdministrators)
!define AzureActiveDirectoryRolesAndAdministrators(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureActiveDirectoryRolesAndAdministrators, AzureActiveDirectoryRolesAndAdministrators)

sprite $AzureActiveDirectoryUser [70x70/16z] {
hTPNOW9H20LGwkLb_mjE8Sqo-1Zn_AIeLs0-W1uIDGFCJEXPRBXWFCYOvIWEw3Wa6PrXm3n6WNcCeDQV3Huwqy-u9snmjvHvCOuTscDiyRIXfBsK-M0C6m5_
VhY1-7Kc9H28GzxfA4hz58qjfIqPfwJOOjf3R80QjDFGl2MYOJ4hLXZruE33VuAQEBzp7MFgabLIwjDnI9AeGiOnmISp3ERhXfyxXjG1EBDTFc1dFhDWnP6K
FwdXarl-ZlozayEE7yut_E-5C-S2NvFsAhcv1w_OvKlj4FXnGybR8KduWkAATqDWHId9sgkLB-2MTcy5FPxj3-bkrhAKrBqhfPXjDHeSicgsIDoyMig6aZTN
cNBIrfRKA80JMjS3efBpbTRAvYXPpZOgHlyiQlofj_aHDStPbcJRKFASRScQjuP8xuBmUCIiTrWX-kgMreHlBeIUs1m8JKp9reXGyZLYbB16yBgKUKUlV4OK
qr8IntWgoUFj6GjAwGC
}

AzureEntityColoring(AzureActiveDirectoryUser)
!define AzureActiveDirectoryUser(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureActiveDirectoryUser, AzureActiveDirectoryUser)
!define AzureActiveDirectoryUser(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureActiveDirectoryUser, AzureActiveDirectoryUser)

sprite $AzureAppRegistration [70x70/16z] {
xTO7Sjmm44JHHlU4jUz_NrjvYYEX2iGgItzpu6CE-5nPv241sGE6FvHt1N68cKjAjd18cyfu9oLUHV7tLNuLPeiBogzYsR8THT6Qx4VH6lYi3RO6m1u0jd38
BYq3BZs0_Il-G2L-5TYlOhIhbH19nQvI1k-Sflnf6H3zEu0tpsciDfMBYuS6AbgBWAm539NHdVNuShj6R_cwBaJE6xEbsxv9vppNgcAcYM6P9nGp5zbJv4d5
tDZopBDAdnnPPYdU5Pygva-EF7DJgTcooARyRJdGlacpWwCopYgL5xAjI6PnhIAo9cTJ4M-gsTfInBliljXJn5BkYbAqg8ZiYdayAeWLHQpCAdzG5gB4fbIn
gWnnhXYn6ZLJX3DD59nDpvM1ymqT5M8lgXHXFpqgkAeXjfdPYn8-SVy1
}

AzureEntityColoring(AzureAppRegistration)
!define AzureAppRegistration(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureAppRegistration, AzureAppRegistration)
!define AzureAppRegistration(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureAppRegistration, AzureAppRegistration)

sprite $AzureEnterpriseApplication [70x70/16z] {
xTU53kCm48JXjMTcDxttV-0BmwhW-1W-OKVLBnL2zdk1hioA4euR9joNaYAHc9L8z6Ip2tLMogUA_SEL_vKQIVq7A_f55O_aoUPFAv-KUbNivoWr6RUQb6Tl
k_0X6IDvSZFchVPL_bVi1rV-L_vN7icuvMcgF1w3Ynwhlafz104S6KTFnOMPtDSIYzrK16Adc4ZrPiH3sAqVJEIU0HEpmWGf0f0YwFk7YaTYLlCKQoGJs5uP
8Xm0dsGSpPKO4N8d4YTBOsM8SCd7bEDCOX1ihCI1E2Z22Ub-HQa2qCljYkD0dwF4NFcIZ9NBwo7IHzg96FLLClus5QgZ0cIEfahwZIxe7YsLKQuSj3yG3BSg
n0ddoIRuM1dY89nuZ6Ypykdk4FxqH-8o5sk4_9b0YLggrinJXjCmLzpQbKi6KBgFRrJZX51ewSAiD-C4wIdIyw54AhpQVOmpYTQ7laTSrReLK19HxRVr5G
}

AzureEntityColoring(AzureEnterpriseApplication)
!define AzureEnterpriseApplication(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureEnterpriseApplication, AzureEnterpriseApplication)
!define AzureEnterpriseApplication(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureEnterpriseApplication, AzureEnterpriseApplication)

sprite $AzureIdentityGovernance [70x70/16z] {
rPXPckmW28K5cSpT_txlby6WE5GFJ_q_cRRgS2268ft-2834R2VCc7u4YXqTHV9NezS57rFaeoKWLbL-0XuBZ9wF2cT80raV-Dh4AmbZ9iJCtAHNCkdDc2Af
SyceKXyBkJnsz8L2BHyVTunbnVNqeWsz6wdAL1TpG8xwRPGO45ttaabhBhlmXiwXjDpOWhrAzjWSjgXPOrhIMlMKOe14GGLWfwARZ7pZAWCtvPQGqQgwRXD5
AxYeBert6XAqTvgiWQjoFRKWhkSg3-uIhGFTpEBmOdkivT5Nwvb4vDHYnr7Y3bc0lJIZI7s0SsPH9dn3MY3SEM5CqSfXAM0tnKfbw6UZbNXSeGnW6c5ulRkL
Rwg07bJNP_UX52a3qoIiJIWDQ0a4kxKxW_TxdMHSdED49f4y2ui9UQ8j9OsG6t1RCUkEd4RWt0Yh21yDacPOTP2zq96ySU8gM2FoL4ECxAa9AqEQe1zKKCoC
0P0v0x2PqI9fhWiQZTW5tA2T2CnLFBK0smt11TaDp2edzIdAWvC7XGirbnbEWoxg0lQ2dj29JeuTBrIalF2fmdvDYxhWSAImE5TzhRdUgDZwQIO0AaumOxMe
45MWj2Y0bfP9Q_2LGwK3iNJayMdq9k5OwM0k7H9kaVbIWyk6CkqpRe23BJz8Mx0FYE7nzaEz9NS95Rym2Brf1ti5swC6dD8FLEQ_Xcvp3sr-c954bGbIqdzR
BE7z6f17AzJCDO0Rm0UF4grmc6pMWEYBkHLtucusUBnXWA-3MFQ9Rm7LCJ8FAlp-0JPcV3hrq1YsCCpF2zo03-ohgNm9kbKF-7kL7sK4CQDbTVTrcLRNlojO
NsIBmESxVIqaxZbszZxSt6e7roUo3XiOXmYfYQnEkRkXx7tMX3atR-MNBh2_b0y0yTCP4jcn0FmruFhe7fHZYhV7z3Mob1_-voI2B7OYp8ZfZ_0V
}

AzureEntityColoring(AzureIdentityGovernance)
!define AzureIdentityGovernance(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureIdentityGovernance, AzureIdentityGovernance)
!define AzureIdentityGovernance(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureIdentityGovernance, AzureIdentityGovernance)

sprite $AzureManagedIdentity [70x70/16z] {
xTVRRgOm30JW93vbt_-5Ly3yjV0VkPZSTdRRSlLfO2GExMN-GhtjPx3k8vrPPHzXrcs6JqLv3u6Yj87GZw9ZOnvNjEyXKFJzFAwy7OfTUSzmK5xjJGl5w3t2
88wCuZnHiIkzFeyhzeaM6Bu51fYN2DijJ_UcL35-XKJ5g3WFb9XHd0TAJAyZKPbp_iRm8X4vc3B2DmBHmZnHcHvvF0yIZUkGdoD4D2WOpCnYSr8wZmlZ31H0
zYauvrWfiGC21RaGC3r102mLnTd8oTXYdYX41GZhfzBy5naAmb9HdmmdfK5P0b0SGHS_x65cIXGWYFfX-mfb2f0OQktJflEu_bAY08aXiU4RNsAY2AyZkDlm
4Q-JAo8UADFEZH7KeKoHR-MwstWvGftI6IbkVOCvgUDNTzt5RpMKrCcNPlDxS5u72fY8C8XbdKP1MJ9OEToZmkXH6HGGQaXI9oWSR-yIWBGEDkhnhXgAP7Ne
Kj2TpS8CJ-iSYbp7QZPbVKz0aj7j0kLy26XI9Qi3x32WW2dMGH4e8dxbIdN87uq21SZpEbtzCKy3IY--Pv8NqSFtBfKwuaKQb0BJwAu8S2Yzz3K0nKQxAQFu
QI8eSbUe-Dad_avPlIuU4h-VbQ-BP_HG3iXM-Yu21iWkyuty1m
}

AzureEntityColoring(AzureManagedIdentity)
!define AzureManagedIdentity(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureManagedIdentity, AzureManagedIdentity)
!define AzureManagedIdentity(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureManagedIdentity, AzureManagedIdentity)

