sprite $AzureAzureDDoSProtection [70x70/16z] {
vTVPUkqW28PXH1JukzRzt-xkN19jelHmlyTvlimETAMguvrhfHnM72ZJlev1fqtiUELc-ixCySeBxMXuvNhmtX5Q9XuRnuvLMb4wtfXE65vvAzS15dKCDpFS
5hmBprBD7D_Sz5V7unf5Sfk8dH2IyyVXxcQwoCpVO_rKqOIXufhWTvNUPD3wRgMMYRfRuJB1kvKobQYmlJo_FOnp5JLfpn-Qgw2BF7ugo5NKc_xzMbWHA2Sg
kNU4J0Kh5T50afN-elxyqLOgTZI-QI-bsD5AnLJa-SDo5Nb1k9I7f2gl92WbMud-oqhBLXe5agq81JLRgHG1lbznW0uyL_5XBRXV6TQB5V3TYWELZd8LEb70
epBbqMG1p9aAqva1UnL0QL3tAqmZ0tOgWD940R1U0L1efiKAbmcEbKPp7Z9I9YH4Z7x129dU1dsudwaMCbTkjZW6O2cYTA4ui19nkiG0xYCeTAtYrLs4wOuC
cI5IYJOoYKZCN69QKpSYgOmphMFCUQ4Tx9YmGdkAOQ2qh-54A8CzVpUHubkZFBbvmLiFkTDVoSgFymy
}

AzureEntityColoring(AzureAzureDDoSProtection)
!define AzureAzureDDoSProtection(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureAzureDDoSProtection, AzureAzureDDoSProtection)
!define AzureAzureDDoSProtection(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureAzureDDoSProtection, AzureAzureDDoSProtection)
