sprite mdi-image-marker <svg width="48" height="48"><g transform="scale(2)"><path d="M13.55 18C13.97 19.08 14.59 20.12 15.19 21H5C3.9 21 3 20.11 3 19V5C3 3.9 3.9 3 5 3H19C20.1 3 21 3.89 21 5V10.63C20.25 10.23 19.39 10 18.5 10C16.29 10 14.33 11.39 13.47 13.33L11 16.5L8.5 13.5L5 18H13.55M22 15.5C22 18.1 18.5 22 18.5 22S15 18.1 15 15.5C15 13.6 16.6 12 18.5 12S22 13.6 22 15.5M19.7 15.6C19.7 15 19.1 14.4 18.5 14.4S17.3 14.9 17.3 15.6C17.3 16.2 17.8 16.8 18.5 16.8S19.8 16.2 19.7 15.6Z" /></g></svg>

!define MA_IMAGE_MARKER(_color)                                 SPRITE_PUT(mdi-image-marker, _color)
!define MA_IMAGE_MARKER(_color, _scale)                         SPRITE_PUT(mdi-image-marker, _color, _scale)
!define MA_IMAGE_MARKER(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA IMAGE MARKER, mdi-image-marker, _color, _scale)
!define MA_IMAGE_MARKER(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA IMAGE MARKER, mdi-image-marker, _color, _scale, _shape)
!define MA_IMAGE_MARKER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA IMAGE MARKER, _label, mdi-image-marker, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA IMAGE MARKER>> White
