sprite mdi-map-marker-right <svg width="48" height="48"><g transform="scale(2)"><path d="M9 11.5C7.62 11.5 6.5 10.38 6.5 9S7.62 6.5 9 6.5 11.5 7.62 11.5 9 10.38 11.5 9 11.5M9 2C5.13 2 2 5.13 2 9C2 14.25 9 22 9 22S16 14.25 16 9C16 5.13 12.87 2 9 2M18 17L23 12L18 7V17Z" /></g></svg>

!define MA_MAP_MARKER_RIGHT(_color)                                 SPRITE_PUT(ma_map_marker_right, _color)
!define MA_MAP_MARKER_RIGHT(_color, _scale)                         SPRITE_PUT(ma_map_marker_right, _color, _scale)
!define MA_MAP_MARKER_RIGHT(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA MAP MARKER RIGHT, ma_map_marker_right, _color, _scale)
!define MA_MAP_MARKER_RIGHT(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA MAP MARKER RIGHT, ma_map_marker_right, _color, _scale, _shape)
!define MA_MAP_MARKER_RIGHT(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA MAP MARKER RIGHT, _label, ma_map_marker_right, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA MAP MARKER RIGHT>> White
