sprite mdi-map-marker-remove-outline <svg width="48" height="48"><g transform="scale(2)"><path d="M16.6 14.2L15.2 15.6L17.6 18L15.2 20.4L16.6 21.8L19 19.4L21.4 21.8L22.8 20.4L20.4 18L22.8 15.6L21.4 14.2L19 16.6M9 6.5C10.4 6.5 11.5 7.6 11.5 9S10.4 11.5 9 11.5 6.5 10.4 6.5 9 7.6 6.5 9 6.5M9 2C12.9 2 16 5.1 16 9C16 14.2 9 22 9 22S2 14.2 2 9C2 5.1 5.1 2 9 2M9 4C6.2 4 4 6.2 4 9C4 10 4 12 9 18.7C14 12 14 10 14 9C14 6.2 11.8 4 9 4Z" /></g></svg>

!define MA_MAP_MARKER_REMOVE_OUTLINE(_color)                                 SPRITE_PUT(ma_map_marker_remove_outline, _color)
!define MA_MAP_MARKER_REMOVE_OUTLINE(_color, _scale)                         SPRITE_PUT(ma_map_marker_remove_outline, _color, _scale)
!define MA_MAP_MARKER_REMOVE_OUTLINE(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA MAP MARKER REMOVE OUTLINE, ma_map_marker_remove_outline, _color, _scale)
!define MA_MAP_MARKER_REMOVE_OUTLINE(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA MAP MARKER REMOVE OUTLINE, ma_map_marker_remove_outline, _color, _scale, _shape)
!define MA_MAP_MARKER_REMOVE_OUTLINE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA MAP MARKER REMOVE OUTLINE, _label, ma_map_marker_remove_outline, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA MAP MARKER REMOVE OUTLINE>> White
