sprite mdi-toy-brick-marker-outline <svg width="48" height="48"><g transform="scale(2)"><path d="M18.5 12A3.54 3.54 0 0 0 15 15.5C15 18.1 18.5 22 18.5 22S22 18.1 22 15.5A3.54 3.54 0 0 0 18.5 12M18.5 16.8A1.2 1.2 0 1 1 18.5 14.4A1.29 1.29 0 0 1 19.7 15.6A1.15 1.15 0 0 1 18.5 16.8M19 6V5A2 2 0 0 0 17 3H15A2 2 0 0 0 13 5V6H11V5A2 2 0 0 0 9 3H7A2 2 0 0 0 5 5V6H3V20H14.54A15.55 15.55 0 0 1 13.54 18H5V8H19V10A5.11 5.11 0 0 1 21 10.6V6Z" /></g></svg>

!define MA_TOY_BRICK_MARKER_OUTLINE(_color)                                 SPRITE_PUT(ma_toy_brick_marker_outline, _color)
!define MA_TOY_BRICK_MARKER_OUTLINE(_color, _scale)                         SPRITE_PUT(ma_toy_brick_marker_outline, _color, _scale)
!define MA_TOY_BRICK_MARKER_OUTLINE(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA TOY BRICK MARKER OUTLINE, ma_toy_brick_marker_outline, _color, _scale)
!define MA_TOY_BRICK_MARKER_OUTLINE(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA TOY BRICK MARKER OUTLINE, ma_toy_brick_marker_outline, _color, _scale, _shape)
!define MA_TOY_BRICK_MARKER_OUTLINE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA TOY BRICK MARKER OUTLINE, _label, ma_toy_brick_marker_outline, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA TOY BRICK MARKER OUTLINE>> White
