sprite mdi-greenhouse <svg width="48" height="48"><g transform="scale(2)"><path d="M12 3L4 9V21H20V9L12 3M10 10H14V19H10V10M16 10H18V13H16V10M15.33 8H8.67L12 5.5L15.33 8M8 10V13H6V10H8M6 15H8V19H6V15M16 19V15H18V19H16Z" /></g></svg>

!define MA_GREENHOUSE(_color)                                 SPRITE_PUT(ma_greenhouse, _color)
!define MA_GREENHOUSE(_color, _scale)                         SPRITE_PUT(ma_greenhouse, _color, _scale)
!define MA_GREENHOUSE(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA GREENHOUSE, ma_greenhouse, _color, _scale)
!define MA_GREENHOUSE(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA GREENHOUSE, ma_greenhouse, _color, _scale, _shape)
!define MA_GREENHOUSE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA GREENHOUSE, _label, ma_greenhouse, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA GREENHOUSE>> White
