sprite mdi-alpha-u <svg width="48" height="48"><g transform="scale(2)"><path d="M9,7V15A2,2 0 0,0 11,17H13A2,2 0 0,0 15,15V7H13V15H11V7H9Z" /></g></svg>

!define MA_ALPHA_U(_color)                                 SPRITE_PUT(ma_alpha_u, _color)
!define MA_ALPHA_U(_color, _scale)                         SPRITE_PUT(ma_alpha_u, _color, _scale)
!define MA_ALPHA_U(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA ALPHA U, ma_alpha_u, _color, _scale)
!define MA_ALPHA_U(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA ALPHA U, ma_alpha_u, _color, _scale, _shape)
!define MA_ALPHA_U(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ALPHA U, _label, ma_alpha_u, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ALPHA U>> White
