sprite mdi-numeric-8-box <svg width="48" height="48"><g transform="scale(2)"><path d="M19,3A2,2 0 0,1 21,5V19A2,2 0 0,1 19,21H5A2,2 0 0,1 3,19V5A2,2 0 0,1 5,3H19M11,17H13A2,2 0 0,0 15,15V13.5A1.5,1.5 0 0,0 13.5,12A1.5,1.5 0 0,0 15,10.5V9C15,7.89 14.1,7 13,7H11A2,2 0 0,0 9,9V10.5A1.5,1.5 0 0,0 10.5,12A1.5,1.5 0 0,0 9,13.5V15C9,16.11 9.9,17 11,17M11,13H13V15H11V13M11,9H13V11H11V9Z" /></g></svg>

!define MA_NUMERIC_8_BOX(_color)                                 SPRITE_PUT(mdi-numeric-8-box, _color)
!define MA_NUMERIC_8_BOX(_color, _scale)                         SPRITE_PUT(mdi-numeric-8-box, _color, _scale)
!define MA_NUMERIC_8_BOX(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA NUMERIC 8 BOX, mdi-numeric-8-box, _color, _scale)
!define MA_NUMERIC_8_BOX(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA NUMERIC 8 BOX, mdi-numeric-8-box, _color, _scale, _shape)
!define MA_NUMERIC_8_BOX(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA NUMERIC 8 BOX, _label, mdi-numeric-8-box, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA NUMERIC 8 BOX>> White
