sprite mdi-numeric-6 <svg width="48" height="48"><g transform="scale(2)"><path d="M11,7A2,2 0 0,0 9,9V15A2,2 0 0,0 11,17H13A2,2 0 0,0 15,15V13A2,2 0 0,0 13,11H11V9H15V7H11M11,13H13V15H11V13Z" /></g></svg>

!define MA_NUMERIC_6(_color)                                 SPRITE_PUT(mdi-numeric-6, _color)
!define MA_NUMERIC_6(_color, _scale)                         SPRITE_PUT(mdi-numeric-6, _color, _scale)
!define MA_NUMERIC_6(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA NUMERIC 6, mdi-numeric-6, _color, _scale)
!define MA_NUMERIC_6(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA NUMERIC 6, mdi-numeric-6, _color, _scale, _shape)
!define MA_NUMERIC_6(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA NUMERIC 6, _label, mdi-numeric-6, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA NUMERIC 6>> White
