sprite mdi-numeric-6-box-multiple <svg width="48" height="48"><g transform="scale(2)"><path d="M13,11H15V13H13V11M3,5V21H19V23H3A2,2 0 0,1 1,21V5H3M21,1A2,2 0 0,1 23,3V17A2,2 0 0,1 21,19H7A2,2 0 0,1 5,17V3A2,2 0 0,1 7,1H21M13,15H15A2,2 0 0,0 17,13V11C17,9.89 16.1,9 15,9H13V7H17V5H13A2,2 0 0,0 11,7V13C11,14.11 11.9,15 13,15Z" /></g></svg>

!define MA_NUMERIC_6_BOX_MULTIPLE(_color)                                 SPRITE_PUT(mdi-numeric-6-box-multiple, _color)
!define MA_NUMERIC_6_BOX_MULTIPLE(_color, _scale)                         SPRITE_PUT(mdi-numeric-6-box-multiple, _color, _scale)
!define MA_NUMERIC_6_BOX_MULTIPLE(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA NUMERIC 6 BOX MULTIPLE, mdi-numeric-6-box-multiple, _color, _scale)
!define MA_NUMERIC_6_BOX_MULTIPLE(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA NUMERIC 6 BOX MULTIPLE, mdi-numeric-6-box-multiple, _color, _scale, _shape)
!define MA_NUMERIC_6_BOX_MULTIPLE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA NUMERIC 6 BOX MULTIPLE, _label, mdi-numeric-6-box-multiple, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA NUMERIC 6 BOX MULTIPLE>> White
