sprite $AzureActiveDirectoryDomainServices [65x65/16z] {
fPTPbiCW30IDDWJS_xxZhUqyFKymfBwZ1bI89CjNs9QVIBN9J_MbjShBFAMjL9gkpssdfCbwQoTbhbxQHPwffzfkR4hW9p8d04p8z1QeQLmWc92fxG5_Ny-r
FP671KPqL62aogZ0IALXWUCohNsb30kC-9H0OBKZaphr2zMlCbFfxfxhDvdbHVyKCeS4mk1McI5pIE2nB6KzrYbZ0d6BasMNuwG-911pP9RT-HWMUp51SP9r
3t0wRCkmGB4Z8AVznQyyA53i3F1jDnPavhv0kmBSZegI1WGcsn3MFKAFFLyovON0ZRJRTZzKb6kkg2zGKRzYlaAG-LgW6OQGVMDDurEcln9e1l7a6v2PEWbR
fzaix00gx5IP-m933v00aLh_gMS8M54-Dg1-8lr9sWK2PjxEBM98uDui60Hi2BFGifY8P2JGz-V8F-kLcMqjy2t1Lw3YnfudQ8E9LsmFS1KHPdFCrOtKA80_
BW3f6P0btJRjts-5IX28po009rV7N8LMHe42KzW1bWio3_B7144V2iu0msfH9be90GH_8K3l7U0GePMOmMG7bwjjhSIulnQE45fPqdKBTAz8onL4TmypFNx5
GWFkWR2O4ShDJJJZ9ZsIyPHXbCDx0Eov7EDP3Qty9q2__bA1ZAH8G7WSncUeX5QQ2JQ0zdNms4fJIYIFW_YwbRdNljXAF2if1CWIUDbA1F3OFzTZEKK0slSI
h_Wudm6MbY7IRNOFq6KM_CZw2Nqw_Xy
}

AzureEntityColoring(AzureActiveDirectoryDomainServices)
!define AzureActiveDirectoryDomainServices(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureActiveDirectoryDomainServices, AzureActiveDirectoryDomainServices)
!define AzureActiveDirectoryDomainServices(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureActiveDirectoryDomainServices, AzureActiveDirectoryDomainServices)
