sprite mdi-panorama-wide-angle <svg width="48" height="48"><g transform="scale(2)"><path d="M12 4C8 4 5.2 4.6 3 5C2.5 7 2 8.9 2 12C2 15 2.5 17 3 19C5.2 19.4 8 20 12 20C16 20 18.9 19.4 21 19C21.6 17 22 15 22 12C22 9 21.5 6.9 21 5C18.9 4.6 16 4 12 4Z" /></g></svg>

!define MA_PANORAMA_WIDE_ANGLE(_color)                                 SPRITE_PUT(mdi-panorama-wide-angle, _color)
!define MA_PANORAMA_WIDE_ANGLE(_color, _scale)                         SPRITE_PUT(mdi-panorama-wide-angle, _color, _scale)
!define MA_PANORAMA_WIDE_ANGLE(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA PANORAMA WIDE ANGLE, mdi-panorama-wide-angle, _color, _scale)
!define MA_PANORAMA_WIDE_ANGLE(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA PANORAMA WIDE ANGLE, mdi-panorama-wide-angle, _color, _scale, _shape)
!define MA_PANORAMA_WIDE_ANGLE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA PANORAMA WIDE ANGLE, _label, mdi-panorama-wide-angle, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA PANORAMA WIDE ANGLE>> White
