
# Author: The-Lum
# Script: 
# The script generates all the README from INFO file
# Usage:
# perl -w script/addReadme.pl 

use strict;
use warnings;
use autodie;

# Input dir: 
my @dirs = glob("stdlib/*");

# Strings
my $hdr = "<!---\nDo not edit: autogenerated by script from INFO file\n-->\n\n";
my $hdr_tab = "|||\n|-|-|\n";

foreach my $d (@dirs) {
    open(my $fh_info, '<', $d . '/INFO');
    my @infos = <$fh_info>;
    close $fh_info;
    chomp(@infos);
    my $s = $hdr . "# Information about `$d`\n" . $hdr_tab;
    foreach my $t (@infos) {
        $t =~ s/=/ | /;
        $s .= "| " . $t . " |\n" if $t;
    }
    open(my $fho, '>:encoding(UTF-8)', $d . '/README.md');
    print $fho $s;
    close $fho;
}
