@startuml
sprite $basekit [51x43/16] {
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEE1111111111127EEEEEEEEEEE11111EEEEEEEEEEE
EEEEEEEEEEE000000000000001EEEEEEEE00000CEEEEEEEEEEE
EEEEEEEEEEE0000000000000001EEEEEE000002EEEEEEEEEEEE
EEEEEEEEEEE0000000000000000EEEEE800000EEEEEEEEEEEEE
EEEEEEEEEEE00008EEEEEE300004EEEE00000EEEEEEEEEEEEEE
EEEEEEEEEEE00008EEEEEEE00001EEE00000BEEEEEEEEEEEEEE
EEEEEEEEEEE00008EEEEEEE00004EE100001EEEEEEEEEEEEEEE
EEEEEEEEEEE00008EEEEEEE0000EE900000EEEEEEEEEEEEEEEE
EEEEEEEEEEE0000000000000000EE00000EEEEEEEEEEEEEEEEE
EEEEEEEEEEE000000000000002EE00000AEEEEEEEEEEEEEEEEE
EEEEEEEEEEE00000000000000AEE00000EEEEEEEEEEEEEEEEEE
EEEEEEEEEEE0000000000000000EC00000EEEEEEEEEEEEEEEEE
EEEEEEEEEEE00008EEEEEE900009E200000EEEEEEEEEEEEEEEE
EEEEEEEEEEE00008EEEEEEE60000EE00000CEEEEEEEEEEEEEEE
EEEEEEEEEEE00008EEEEEEED0000EEE00000EEEEEEEEEEEEEEE
EEEEEEEEEEE00008EEEEEEE50000EEE400000EEEEEEEEEEEEEE
EEEEEEEEEEE00008EEEEEE500000EEEE00000AEEEEEEEEEEEEE
EEEEEEEEEEE00000000000000005EEEEE00000EEEEEEEEEEEEE
EEEEEEEEEEE0000000000000000EEEEEE700000EEEEEEEEEEEE
EEEEEEEEEEE000000000000000EEEEEEEE000006EEEEEEEEEEE
EEEEEEEEEEE777777777777BEEEEEEEEEEE77777EEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
}
@enduml
