@startuml
sprite $django-icon [51x51/16] {
000CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC000
00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD00
0DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD0
CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDD200000DDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDA5226200000DDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDC0000000000000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDDD200000000000000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDDD1000000000000000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDD90000000000000000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDD0000000DDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDC000000DDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDD100000DDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDD000000DDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDD000000DDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDD000000DDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDD000000DDDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDD1000006DDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDC000000CDDDD200000DDD400000DDDDDDDDDDDDDD
DDDDDDDDDDD00000000474000000DDD300000DDDDDDDDDDDDDD
DDDDDDDDDDDC0000000000000000DDD200000DDDDDDDDDDDDDD
DDDDDDDDDDDD7000000000000000DDD000000DDDDDDDDDDDDDD
DDDDDDDDDDDDDC00000000000000DDD000000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDC20000000002ADDD000000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD000000DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD1000003DDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD000000DDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDD0000000DDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDD20000000DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDD300000009DDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDD60000CDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD82DDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
0DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD0
00DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD00
000CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC000
}
@enduml
