@startuml
sprite $survicate-icon [51x51/16] {
000000000AEEE000000000EEE7000000002EEEEEEB000000000
0000001EEEEEE0000006EEEEE7000000CEEEEEEEEEEE1000000
00000EEEEEEEE00000EEEEEEE700001EEEEEEEEEEEEEEE00000
0000EEEEEEEEE0001EEEEEEEE70007EEEEEEEEEEEEEEEEE0000
000EEEEEEEEEE000EEEEEEEEE7005EEEEEEEEEEEEEEEEEEE000
00EEEEEEEEEEE00EEEEEEEEEE700EEEEEEEEEEEEEEEEEEEEE00
01EEEEEEEEEEE0BEEEEEEEEEE70EEEEEEEEEEEEEEEEEEEEEE00
0EEEEEEEEEEEE0EEEEEEEEEEE72EEEEEEEEEEEEEEEEEEEEEEE0
0EEEEEEEEEEEE7EEEEEEEEEEE7EEEEEEEEEEEEEEEEEEEEEEEE0
BEEEEEEEEEEEEEEEEEEEEEEEE7EEEEEEEEEEEEEEEEEEEEEEEEB
EEEEEEEEEEEEEEEEEEEEEEEEE7EEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEBEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEBEEEEEEEEEEEEEEEEB00000000
EEEEEEEEEEEEEEEEEEEEEEEEE3EEEEEEEEEEEEEEEEEED000000
EEEEEEEEEEEEEEEEEEEEEEEEE0EEEEEEEEEEEEEEEEEEEE00000
1EEEEEEEEEEEEEEEEEEEEEEEE0EEEEEEEEEEEEEEEEEEEEE0000
0EEEEEEEEEEEEEEEEEEEEEEE808EEEEEEEEEEEEEEEEEEEEE000
0CEEEEEEEEEEEEEEEEEEEEEE000EEEEEEEEEEEEEEEEEEEEEE00
00EEEEEEEEEEEEEEEEEEEEE70007EEEEEEEEEEEEEEEEEEEEE80
000EEEEEEEEEEEEEEEEEEEE00000EEEEEEEEEEEEEEEEEEEEEE0
0004EEEEEEEEEEEEEEEEEE0000000EEEEEEEEEEEEEEEEEEEEE0
00002EEEEEEEEEEEEEEED000000000DEEEEEEEEEEEEEEEEEEEE
000000EEEEEEEEEEEEE5000000000006EEEEEEEEEEEEEEEEEEE
00000000CEEEEEEEE60000000000000007EEEEEEEEEEEEEEEEE
99999999999BDB50000000000000000000005BEC64444444444
EEEEEEEEEEEEEEEEEC000000000000000CEEEEEEEEE40000000
EEEEEEEEEEEEEEEEEEEB00000000000BEEEEEEEEEEEEE000000
DEEEEEEEEEEEEEEEEEEEE000000000EEEEEEEEEEEEEEEE90000
0EEEEEEEEEEEEEEEEEEEEE0000000EEEEEEEEEEEEEEEEEEA000
0EEEEEEEEEEEEEEEEEEEEEE00000EEEEEEEEEEEEEEEEEEEE300
02EEEEEEEEEEEEEEEEEEEEEA000AEEEEEEEEEEEEEEEEEEEEE00
00EEEEEEEEEEEEEEEEEEEEEE000EEEEEEEEEEEEEEEEEEEEEEE0
000EEEEEEEEEEEEEEEEEEEEEA0BEEEEEEEEEEEEEEEEEEEEEEE0
0000EEEEEEEEEEEEEEEEEEEEE0EEEEEEEEEEEEEEEEEEEEEEEE4
00000EEEEEEEEEEEEEEEEEEEE0EEEEEEEEEEEEEEEEEEEEEEEEE
0000006EEEEEEEEEEEEEEEEEE5EEEEEEEEEEEEEEEEEEEEEEEEE
000000002DEEEEEEEEEEEEEEEBEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEE7EEEEEEEEEEEEEEEEEEEEEEEEE
8EEEEEEEEEEEEEEEEEEEEEEEE7EEEEEEEEEEEEEEEEEEEEEEEE8
0EEEEEEEEEEEEEEEEEEEEEEED7EEEEEEEEEEE5EEEEEEEEEEEE0
0EEEEEEEEEEEEEEEEEEEEEEE07EEEEEEEEEEE0EEEEEEEEEEEE0
00EEEEEEEEEEEEEEEEEEEEEE07EEEEEEEEEE70EEEEEEEEEEE00
00BEEEEEEEEEEEEEEEEEEEE007EEEEEEEEEE00EEEEEEEEEEB00
000EEEEEEEEEEEEEEEEEEE1007EEEEEEEEE000EEEEEEEEEE000
0000EEEEEEEEEEEEEEEEE10007EEEEEEEE0000EEEEEEEEE0000
000009EEEEEEEEEEEEEE000007EEEEEEE00000EEEEEEE900000
0000000EEEEEEEEEEE30000007EEEEE0000000EEEEEE0000000
0000000000EEEEE80000000007EE3000000000EEE0000000000
}
@enduml
