sprite mdi-home-lightning-bolt <svg width="48" height="48"><g transform="scale(2)"><path d="M12 3L2 12H5V20H19V12H22L12 3M11.5 18V14H9L12.5 7V11H15L11.5 18Z" /></g></svg>

!define MA_HOME_LIGHTNING_BOLT(_color)                                 SPRITE_PUT(ma_home_lightning_bolt, _color)
!define MA_HOME_LIGHTNING_BOLT(_color, _scale)                         SPRITE_PUT(ma_home_lightning_bolt, _color, _scale)
!define MA_HOME_LIGHTNING_BOLT(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA HOME LIGHTNING BOLT, ma_home_lightning_bolt, _color, _scale)
!define MA_HOME_LIGHTNING_BOLT(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA HOME LIGHTNING BOLT, ma_home_lightning_bolt, _color, _scale, _shape)
!define MA_HOME_LIGHTNING_BOLT(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA HOME LIGHTNING BOLT, _label, ma_home_lightning_bolt, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA HOME LIGHTNING BOLT>> White
