sprite mdi-power-plug <svg width="48" height="48"><g transform="scale(2)"><path d="M16,7V3H14V7H10V3H8V7H8C7,7 6,8 6,9V14.5L9.5,18V21H14.5V18L18,14.5V9C18,8 17,7 16,7Z" /></g></svg>

!define MA_POWER_PLUG(_color)                                 SPRITE_PUT(ma_power_plug, _color)
!define MA_POWER_PLUG(_color, _scale)                         SPRITE_PUT(ma_power_plug, _color, _scale)
!define MA_POWER_PLUG(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA POWER PLUG, ma_power_plug, _color, _scale)
!define MA_POWER_PLUG(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA POWER PLUG, ma_power_plug, _color, _scale, _shape)
!define MA_POWER_PLUG(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA POWER PLUG, _label, ma_power_plug, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA POWER PLUG>> White
