sprite $AzureWebAppForContainers [65x48/16z] {
xTL74kCm34JHHc2Kxd_UWL4g9mQJarENj_yPN0cZSSWvCE7hnffAhJddgFmLTSXM7mROh-GKUBEkLX_dUQjBzfb1wxNDygCQS5ynGnOlFwprt85bG-x_VLXy
rXRmcK6zEkOhhfRRxXSqAur1RBNFtzq0NIC-6VVBlLe0t2Y9SUqMUx43r5ha0Po76tiNv6UWxW6-FnJu3qGLPXPDNmEKf0GY7oZi0u70ei6d38gRW8AkEiQK
Kc3e5Y2GSFM-50Mo0NX_1tn9WMKWDBqBIq39DgAsj_7g1Ghj0Iby1Fp3I0nkUnTa3XG5c8M9T03e5CW4kPTz819yrZJ0KGdJt0M6JsFnv1ceWYRk0pxIRCqp
4A5DFmRkNsLBhySmDVqKy8a_nI_896tVZl0sqkH6ZLWv8A0pygS4VEeTO2Pq9g4i04wagEYD22kz4uh-T0LmWj4TBmEoTi8-GAi0Op3I5I0534To0Mcom9YD
MMxJuGJVOry
}

AzureEntityColoring(AzureWebAppForContainers)
!define AzureWebAppForContainers(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureWebAppForContainers, AzureWebAppForContainers)
!define AzureWebAppForContainers(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureWebAppForContainers, AzureWebAppForContainers)
