sprite mdi-arrow-all <svg width="48" height="48"><g transform="scale(2)"><path d="M13,11H18L16.5,9.5L17.92,8.08L21.84,12L17.92,15.92L16.5,14.5L18,13H13V18L14.5,16.5L15.92,17.92L12,21.84L8.08,17.92L9.5,16.5L11,18V13H6L7.5,14.5L6.08,15.92L2.16,12L6.08,8.08L7.5,9.5L6,11H11V6L9.5,7.5L8.08,6.08L12,2.16L15.92,6.08L14.5,7.5L13,6V11Z" /></g></svg>

!define MA_ARROW_ALL(_color)                                 SPRITE_PUT(mdi-arrow-all, _color)
!define MA_ARROW_ALL(_color, _scale)                         SPRITE_PUT(mdi-arrow-all, _color, _scale)
!define MA_ARROW_ALL(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA ARROW ALL, mdi-arrow-all, _color, _scale)
!define MA_ARROW_ALL(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA ARROW ALL, mdi-arrow-all, _color, _scale, _shape)
!define MA_ARROW_ALL(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ARROW ALL, _label, mdi-arrow-all, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ARROW ALL>> White
