sprite mdiArrowTopLeftThin <svg width="48" height="48"><g transform="scale(2)"><path d="M12.07 5L9.24 7.83L19 17.59L17.58 19L7.82 9.25L5 12.07V5Z" /></g></svg>

!if %function_exists("$MdiSprite")
  !unquoted function $MdiArrowTopLeftThinImg($color = $MDI_DEFAULT, $scale = "1")
    !return $MdiSprite(mdiAccountAlert, $color, $scale)
  !endfunction

  !unquoted function $MdiArrowTopLeftThin($alias, $label=$MDI_DEFAULT, $shape=$MDI_DEFAULT, $color=$MDI_DEFAULT, $scale=1, $stereo=$MDI_DEFAULT)
    !return $MdiSpriteElement("mdiAccountAlert", $alias, $label, $shape, $color, $scale, $stereo)
  !endfunction
!endif
