sprite mdi-arrow-top-left-bold-box-outline <svg width="48" height="48"><g transform="scale(2)"><path d="M8 8H15.1L13 10.1L17 14L14.2 16.8L10.1 12.9L8 15.1V8M19 3H5C3.9 3 3 3.9 3 5V19C3 20.1 3.9 21 5 21H19C20.1 21 21 20.1 21 19V5C21 3.9 20.1 3 19 3M19 19H5V5H19V19Z" /></g></svg>

!define MA_ARROW_TOP_LEFT_BOLD_BOX_OUTLINE(_color)                                 SPRITE_PUT(ma_arrow_top_left_bold_box_outline, _color)
!define MA_ARROW_TOP_LEFT_BOLD_BOX_OUTLINE(_color, _scale)                         SPRITE_PUT(ma_arrow_top_left_bold_box_outline, _color, _scale)
!define MA_ARROW_TOP_LEFT_BOLD_BOX_OUTLINE(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA ARROW TOP LEFT BOLD BOX OUTLINE, ma_arrow_top_left_bold_box_outline, _color, _scale)
!define MA_ARROW_TOP_LEFT_BOLD_BOX_OUTLINE(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA ARROW TOP LEFT BOLD BOX OUTLINE, ma_arrow_top_left_bold_box_outline, _color, _scale, _shape)
!define MA_ARROW_TOP_LEFT_BOLD_BOX_OUTLINE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ARROW TOP LEFT BOLD BOX OUTLINE, _label, ma_arrow_top_left_bold_box_outline, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ARROW TOP LEFT BOLD BOX OUTLINE>> White
