sprite mdi-arrow-left-thin <svg width="48" height="48"><g transform="scale(2)"><path d="M10.05 16.94V12.94H18.97L19 10.93H10.05V6.94L5.05 11.94Z" /></g></svg>

!define MA_ARROW_LEFT_THIN(_color)                                 SPRITE_PUT(ma_arrow_left_thin, _color)
!define MA_ARROW_LEFT_THIN(_color, _scale)                         SPRITE_PUT(ma_arrow_left_thin, _color, _scale)
!define MA_ARROW_LEFT_THIN(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA ARROW LEFT THIN, ma_arrow_left_thin, _color, _scale)
!define MA_ARROW_LEFT_THIN(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA ARROW LEFT THIN, ma_arrow_left_thin, _color, _scale, _shape)
!define MA_ARROW_LEFT_THIN(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ARROW LEFT THIN, _label, ma_arrow_left_thin, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ARROW LEFT THIN>> White
