sprite $API_Analytics [64x64/16z] {
tPVNWkim24GfWe7__-1R56MBBBm9ZtjUKXLFvk16lmmPViCGkiS2juJTBqVy08ng1F4Z42hnLzOxLIZY1Q1qXX4lWMvv2up-vYVWPdaBUDDTxN1jlXzW8Du0
eoYlMw6zkzwAydeL-llh_Ut1htS3H0FqtEqEQtVG1Ig7bJiuy5cnH0JWA1pA9HSJ4IiYP9ORkTww_4zPxevYsMT2ZdG-ZmdywWuy-uGnaOSJUJeH6mBZKXNq
uaw9aHcP8SGH8X5C4lCjCEdkS62NwXdAWiGCW7GY98GrqlVDOQ_4Y5SjI2Lz9DB4Afh9uXjxe-FvPRAqXngPJvy_EJ8AUkkzoCypVpxpyqV-t0nS-hCC5KK-
gepLduf6shK_SjpuczJ-u3DLFJ-Jh_Dp662hvtTHp-znzpNPTnQCsP_5dhKuV028RptdUkjy046qGF_mEHdjm_T-6I7HGDgdhudtJvyJRf--9qRVGREyfaEb
HSyXw8AqtFKSEXrWDDor70uwWqPv3OTA5OvcUGjvmrstGgCx1ivioxltZoRqo_WB
}

EntityColoring(API_Analytics)
!define API_Analytics(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, API_Analytics, API_Analytics)
!define API_Analytics(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, API_Analytics, API_Analytics)
!define API_AnalyticsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, API_Analytics, API_Analytics)
!define API_AnalyticsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, API_Analytics, API_Analytics)
