sprite mdi-radio-am <svg width="48" height="48"><g transform="scale(2)"><path d="M5,7A2,2 0 0,0 3,9V17H5V13H7V17H9V9A2,2 0 0,0 7,7H5M5,9H7V11H5V9M13,7A2,2 0 0,0 11,9V17H13V9H15V16H17V9H19V17H21V9A2,2 0 0,0 19,7H13Z" /></g></svg>

!define MA_RADIO_AM(_color)                                 SPRITE_PUT(ma_radio_am, _color)
!define MA_RADIO_AM(_color, _scale)                         SPRITE_PUT(ma_radio_am, _color, _scale)
!define MA_RADIO_AM(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA RADIO AM, ma_radio_am, _color, _scale)
!define MA_RADIO_AM(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA RADIO AM, ma_radio_am, _color, _scale, _shape)
!define MA_RADIO_AM(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA RADIO AM, _label, ma_radio_am, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA RADIO AM>> White
