sprite mdi-stairs-down <svg width="48" height="48"><g transform="scale(2)"><path d="M15 6H22V9H18V13H14V17H10V21H3V18H7V14H11V10H15V6M4.83 8.34L10.34 2.83L12.17 4.66L6.66 10.17L8.5 12H3V6.5L4.83 8.34Z" /></g></svg>

!define MA_STAIRS_DOWN(_color)                                 SPRITE_PUT(ma_stairs_down, _color)
!define MA_STAIRS_DOWN(_color, _scale)                         SPRITE_PUT(ma_stairs_down, _color, _scale)
!define MA_STAIRS_DOWN(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA STAIRS DOWN, ma_stairs_down, _color, _scale)
!define MA_STAIRS_DOWN(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA STAIRS DOWN, ma_stairs_down, _color, _scale, _shape)
!define MA_STAIRS_DOWN(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA STAIRS DOWN, _label, ma_stairs_down, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA STAIRS DOWN>> White
