sprite $AzureApplicationInsights [42x65/16z] {
tTP5WYin34NHPyaMxN-_7u9ood8pdab3RbGCcF0GDVTmK-c42el7n6KPayM27bk9Wc3IB4hMS4SU6qvbMAUNiEOD9nfFqbFOunbwMlQUBqRMGosUnK3nJAt7
CtM9PnABPpAFP_9NbcxtPRXQMVe0W77-dG4qpMNw8kEahqyUato-D946sEdOiGoWtHSfFO_q23iDnUdOIHxQxz-Yyv5juF3pwbg-41jqdXbqB_DC1MXQJxC6
CWMwwSWdB-KhdN4WyrNlUNzcJUB27YzYLv464W5OHFrm6RF77O4Zvel66KXfKQQ9ESrb3hDUbuoPLEN08r-NXWDUbuGZMvM21LgKth2Ynt9WYQOoZIo6vb9G
uCUIKF6vD9HaBWTA516THmJHE5raDPhW5nYMOKCY--oIHuPVW2Jfs1dvsRyd-TLhJ_ChqfwbcsRs5m
}

AzureEntityColoring(AzureApplicationInsights)
!define AzureApplicationInsights(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureApplicationInsights, AzureApplicationInsights)
!define AzureApplicationInsights(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureApplicationInsights, AzureApplicationInsights)

sprite $AzureArtifacts [60x65/16z] {
xSzL5iD0243HZ0AJxd-xjP4AXxWdz_yXrNdfDaeg5SeeiKBhEhGajBvBgxRQKZAWfMBjbbfR4fsylLfOfBrQJxAGRQHL-iKOG8eG6CoCCVebfYOaTGQ-dNkt
50hUojx7XrzjBIHwV2l_YnH1QtjBm2T0sGnjNV2R0ICOq79mZFPgdVtYHhVR_pVfsUBtlsFsBlWlTcvfMAjUhQwP3gsh8iNeDzMWEgK7
}

AzureEntityColoring(AzureArtifacts)
!define AzureArtifacts(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureArtifacts, AzureArtifacts)
!define AzureArtifacts(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureArtifacts, AzureArtifacts)

sprite $AzureBoards [65x65/16z] {
xT87SiCm34HHm22uaEv_N_Uo2GS2q-kRbjZUFoeKZvTpkQlsTI5Uvnq3o-iy2u34yNzdn_y3P2xm7-YqxvyI27OBqY3O47Y5RnXePBZdcO2HVWxWxei2v5S4
FlurdgqN7tKIu-urWNZgfO4OZO4WsPuLWMJFfWEHqRb0fFfK87BmEh361i3gAyYkVeTJe5VdOCtsgiS2xfUGpTSrtPyAHxq8BCd-p72a54Wk8Dq7xlUGp2bW
RToV0os_0WwOQXlsyNW8Q-QnlnLeJu5bE-1wrdX_2q1ElBY2TYlmdgz0V4a3NB1XVmja75TD7tOWBfiCOs47Ph99STTeJrIsTN1Xt7Sf6AWmxc5I0Md37b8o
44Tw0Jb7pcL6HqgcA38gSxJQrxou_vgXUFurwxJk9g-WvlqqTbFv0FyE
}

AzureEntityColoring(AzureBoards)
!define AzureBoards(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureBoards, AzureBoards)
!define AzureBoards(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureBoards, AzureBoards)

sprite $AzureDevOps [65x65/16z] {
xTDLWiCm38JXaLbp__ikg5npb-5x2_r931Z9U2Egl350XhS6cDyQeBgt14p4WuH7HV00dtcc7fiaAcyaxF25bIARBwy5h0Y5NHapBh6hNXBYOrRY8YYd8emB
gV2WchI9PA-zilvobXGSe2IhG5XwrZG3CdbMOFe1PPFcw0Lc72YjPuE3MGZ4pk-k1XnFzEPtbmCqrUyk1yhkPbLMladWF_0V-0_y1r9vOm20-1Za3G6JoP9Z
SFk1-_FMyR8V4AMfEgi1EBPeITPP2C3Jz3hHooI0o5hTOJ-0p0VWMdbh0CfT4JU4cppkU6uHL0BNALeILsMqPRvA29b34Jrw2033XaUNw2dGRwXWm9q2tOPY
pDy4waR2JBHxUes0kMo1TiDXHK2BXAAuzGm
}

AzureEntityColoring(AzureDevOps)
!define AzureDevOps(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureDevOps, AzureDevOps)
!define AzureDevOps(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureDevOps, AzureDevOps)

sprite $AzureDevTestLabs [65x65/16z] {
fPO7bWGX24HRClS_yEOWquZqyx-mqHgXAFMg6IXgxcxAS3q7rMTaF5pkWQSIGps3kkl15sXlFRaVAQ0NM7F_9tlmadqdnNUCVG4dHQZlWMg2l84awqZKJ1d4
EzoCDty65dC_Oo-46hPjbwnLP64Sg_LOkbHtlHutYxEawyY0tdxBlr63NV1eiRTFXI1WwrcZrGJeL0BueG0Nap9MGsoJ2re53lDVZtaEh0uSPZ6Mp-yGTeUF
VLO9YG25My8B81MGsAWgXPmAlBHQpmJyuaC1WaC1lUnCm2yw5AXye5J0NbC_gakKxh_2MpImEDAIggBpi8wqfbaTyT-bEDP7Mfs4OTRYOk55rc7IbTlLDX5B
YvMHVQ0yhWssxEtHGylQ0iM0jk3oWRDdz5yNpnywSFhKr8Q0UGKsBSGVljGKlz2UbV65CEyRMbPA_1YTrqZxhGhXPul-ojv23QPWx4zj9QQR187P8TrPoFTj
MVW0t5YOP8D3YLQ7WFOvuTh2d6XbOQ5W2HLMglSPUNbz-5H0MZb-Uh0CyIRwDKhl
}

AzureEntityColoring(AzureDevTestLabs)
!define AzureDevTestLabs(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureDevTestLabs, AzureDevTestLabs)
!define AzureDevTestLabs(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureDevTestLabs, AzureDevTestLabs)

sprite $AzureLabServices [62x65/16z] {
xSv7biGW40HHcS9KtF_0ivgsCaddbjX9aE-pVBTosBxSDjSr7fNnzNxumr_FzLpFzMQjw_6wwm-7rry9mARJvVNN3a0ReOzndNuMJroZ1LoZTVn97-6hI0ku
HEjuEQ1rd2SWu8Tqsmzh0DGBMkWKBmYTuc3W1GmS3Bo0WIS6Ni304ps7XkBGuD1G15h50mmy6SsXeJWqwT1G31hIeI4C6jAX8GmQqg4X31hIeI4wHXshjCQ1
qRv4_YulVm
}

AzureEntityColoring(AzureLabServices)
!define AzureLabServices(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureLabServices, AzureLabServices)
!define AzureLabServices(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureLabServices, AzureLabServices)

sprite $AzurePipelines [65x65/16z] {
rOzDTkOm20IH8uC0t_-w-UNDSyj4vXklKlkg1le3_7dQFZHbSCdVG4SgXOO-CWe1qHNtVjTdWQOF0_8mqFM6LnyOIQ3-WEpz4uR8Am_iFP1geAK-5keFS3y1
WU83_Gn3eFI0T60Ai5rn1NWLu4HtUo6G-qy2xguJ0_pT893ufZFxEI3BW2S7g8tp0RfumSEVCK4_3_WFbWLin1UiDWLyHZFCT0Ypg9dU10p5VuCMw4t0fbqP
TaeeCBB0nHzHIE0aO2Sz_DyB3GFesoSwVj2SZQw1t4yl68sk0SlzBD290hxwDlkMpIS52nlzR_BvG9P-aCzZmIe-pcF10l1dHgEC4OKx7-QlXJUvss-4O64Z
agNlJWlqZJwHfO-1704Vz5AWiVpY7wL0OsO97_MZTW5_aVkrmCvVo4KFtrFd2oWqaiGl1ABGY4X03xyMe4PV2CoN0iZceVzdeFdXvk0N0k07uDS3V9pmenZ0
GauvGFmqG5mF851u521-5CWBNW_a1Qu6yeAdFdq
}

AzureEntityColoring(AzurePipelines)
!define AzurePipelines(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzurePipelines, AzurePipelines)
!define AzurePipelines(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzurePipelines, AzurePipelines)

sprite $AzureRepos [65x65/16z] {
xP9Pbkem34GviSPY__jzCf19tOs5EVbxbo5VTLsATKi8tYEtzyXznC20eG3l1VSn5me4LMIGdpIWSn-3pYM2-oVaC9j_Yl4nxpCS3EOps2xmXFrgD4_y8J2c
GFoCKWka851wONv0sXCQ2YoYQYRnE5hxwQOSXf60NqVhQOh8hqLq823IrSHxhIr7ZTuBR6iU5OuJ-0D4XSi4UGH98m1mz16cNo822LFX6aKrF9okaLMeDIel
4fll82_IU9NPJy1QXxqWS4cB703W5XXA0Ww-4MWMEBuIe6FS9WK8NAa5TO44jXtkqe89mTPzWyHB0XDLJTq3KW1U4cZWv-wD3O7N11tFtJjU4g0RgANk7Iy9
7jMN9NN_I41Bi1xkAJqK06YhW1GvNXUaxcK1LW6bxaK1DW5Zm-iDa0HxV2304LiwpJ4aDS0JNLuOtf0QfFE9cUBXzGROQH5y5U4PWI-Bu45qc17OrZmg-CM2
-WZNlyHyZMB64zUO5yan9u3J4h1ZLX1uIWy5ZXby5mXca5ioJEQ_vp__
}

AzureEntityColoring(AzureRepos)
!define AzureRepos(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureRepos, AzureRepos)
!define AzureRepos(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureRepos, AzureRepos)

sprite $AzureTestPlans [59x65/16z] {
xT97aiCm34HHPe84xd_TII8nSYl1sapyMzShiDfoU-L2M2t96GfbIwcKxqkTZnKhtjdo3Qis-4yD_LEoqa8R6cmo8BIVfRPJjCZKThFGjb-vbgKTvEqROTMu
qOsbOeE8oBWKm9hVAXFdCvbXrRn4rqjvbBFhfUeZpThy8LnlL3yE9gNbwbFMXwQFOWW9Q4ld6-KqgTfwyGUfd0MrfBISR5I76sV3EAhvuuztCBLHvU5I14S7
Zh5UVSf9ryLQxuyMQTEHCEfWCqWULS8QOs4j8n_JpbXVqyupsiJ2M79QvfbqmkGjj4xxb2BRexB5TKhwK2E6aMG9k1-KXKKfF7ajXLNJ8hCynd1p6milj0hM
1sGvp2Erv_71zjpI3Kc3qfttZlgpCWtuz58StBfKoLY9xjlqtt-l
}

AzureEntityColoring(AzureTestPlans)
!define AzureTestPlans(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureTestPlans, AzureTestPlans)
!define AzureTestPlans(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureTestPlans, AzureTestPlans)

