sprite $AzureDevOpsOrganisation [70x70/16z] {
xPXNsk8m34MjUcNO_tu7nV6V7bDUvz31Ff-kH2zVyHyYJkW70-kAxqoi1pxsaDe97th4pb7-GA9sYVmkIUHtISA_z6I1oXYs4Lh6s1Z-hIcTaOJCVY-6pVlX
3hjJgByBNG_OtqT-TYHwtbF_a7A4_MD-boIc_BiaCIaBvD-pr6F-2TWUT9S7nyE2UyJZKMiWLwwnkHICSDH7KcVW1mqD7T4LWUu9tsa40oO7-bn9_52FZ09v
pJAiR93ObKF5Xn8h1pHU-2hJhUJb22vdOAEvjQIaN61hZU2IdA-NItIbSSSLqIkvhWQ8YRJ4wI4dIkKEZ_2OWCOLjKgvXN9_J72SuxMYhvQBhsG6U4oKwrAu
9E9HLSpqM1a1hJDMBCv0ByLUkhISVf5IODekXQyiEdMmrd0b4kaVYQpszox7SwHSU168PeaiN_Gqxvdm5hSbqdpuN1BjTGSk7L6Yb03HvJeLqz9TjiKpLsSE
w4B4UKafJWlFZvrPB6TGVV-Uu7ywRHQpCeCbIJkqvcfKsvVI-zfy1AnMe6xnPZa60lKTG5hSPVFu1jGuiw2Yp33pqPAHLo32qh9BjFI9vY5sIuTiQ_4UVa6M
FldpYMRXmxUnfPw8DkcGic1viqiUkLqllbLn0n6KaTR5Q5HF5L2VpwTFDlToWqPeQxhp8ibIufaq2Rlhu1t8ymArXZ4L4eyQDlNgbGRQnDcMEn2H2nXJiv4N
ON-Pyt8KA948jD6XVpRB8NRE-Hu4fBybEDoEwsbOIcO1gDnXMSe80-x7w6vb382RPU9cLCOGRggHjt_wSMheFCuY6K8EG4yBMIHZo8339DWIAX-WdXZJh6Nr
qO_g-vyhPdbs_YavXjGxhGugtq6YceghVs7-0G
}

AzureEntityColoring(AzureDevOpsOrganisation)
!define AzureDevOpsOrganisation(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureDevOpsOrganisation, AzureDevOpsOrganisation)
!define AzureDevOpsOrganisation(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureDevOpsOrganisation, AzureDevOpsOrganisation)
