sprite $AzureLabServices [62x65/16z] {
xSv7biGW40HHcS9KtF_0ivgsCaddbjX9aE-pVBTosBxSDjSr7fNnzNxumr_FzLpFzMQjw_6wwm-7rry9mARJvVNN3a0ReOzndNuMJroZ1LoZTVn97-6hI0ku
HEjuEQ1rd2SWu8Tqsmzh0DGBMkWKBmYTuc3W1GmS3Bo0WIS6Ni304ps7XkBGuD1G15h50mmy6SsXeJWqwT1G31hIeI4C6jAX8GmQqg4X31hIeI4wHXshjCQ1
qRv4_YulVm
}

AzureEntityColoring(AzureLabServices)
!define AzureLabServices(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureLabServices, AzureLabServices)
!define AzureLabServices(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureLabServices, AzureLabServices)
