@startuml
sprite $moon [51x51/16] {
000000000000000000006CCCCDDDDD600000000000000000000
00000000000000000CCCCCCDDDDDDDDDDD00000000000000000
000000000000006CCCCCCCDDDDDDDDDDDEEE700000000000000
0000000000002CCCCCCCCDDDDDDDDDDDDEEEEE3000000000000
00000000000CCCCCCCCCDDDDDDDDDDDDEEEEEEEE00000000000
0000000001CCCCCCCCCCDDDDDDDDDDDDEEEEEEEEE1000000000
000000005CCCCCCCCCCDDDDDDDDDDDDEEEEEEEEEEE500000000
00000007CCCCCCCCCCDDDDDDDDDDDDDEEEEEEEEEEEE90000000
0000005CCCCCCCCCCCDDDDDDDDDDDDDEEEEEEEEEEEEE5000000
000001CCCCCCCCCCCDDDDDDDDDDDDDEEEEEEEEEEEEEEE100000
00000CCCCCCCCCCCCDDDDDDDDDDDDDEEEEEEEEEEEEEEEE00000
0000CCCCCCCCCCCCDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEE0000
0002CCCCCCCCCCCCDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEE3000
000CCCCCCCCCCCCDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEE000
006CCCCCCCCCCCCDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEE600
00CCCCCCCCCCCCCDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE00
00CCCCCCCCCCCCCDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE00
0CCCCCCCCCCCCCCDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEE0
0CCCCCCCCCCCCCDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEE0
0CCCCCCCCCCCCCDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE0
6CCCCCCCCCCCCCDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE7
CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEE
6CCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEE7
0CCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEE0
0CCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEE0
0CCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEE0
00CCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEE00
00CCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDEEEEEEEEEEE00
006CCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDEEEEEEEEE700
000CCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDEEEEEEE000
0002CCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDEEEEE3000
0000CCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDEEE0000
00000CCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDD00000
000001CCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDDDD100000
0000005CCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDDDDD5000000
00000007CCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDDDD80000000
000000005CCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDD500000000
0000000001CCCCCCCCCCCCCCCCCCCCCCCDDDDDDDD1000000000
00000000000CCCCCCCCCCCCCCCCCCCCCCCCCCCCC00000000000
0000000000002CCCCCCCCCCCCCCCCCCCCCCCCC2000000000000
000000000000006CCCCCCCCCCCCCCCCCCCCC600000000000000
00000000000000000CCCCCCCCCCCCCCCCC00000000000000000
000000000000000000006CCCCCCCCC600000000000000000000
}
@enduml
