sprite $group [128x125/16z] {
xPljSgmW38O5GaBQpdZ_Ttj0hAAY8g1iv_Z-sPPbVIAV8K3VPuk_U5JVGBnGM_hJ5d1KRUbFMS27Qak_sm9EKblwNHRm9RMbLpQ1CzMMplpDBUaroe0hg2qz
tmAkgBRqwnRm3MfBJxU0RrHR-ha5_83Qqfs-sk9tYe2vhG4lFovJe0lydPm4ia10oGR4trsBJXIe4s1A-5eKInVmILGGvVDr3RvEui_1Z42gAyTtAga2egrF
rNX_PLx-AP-VvlFB_o3-p_Fyd_F9xrO-l_nCljH8X8llb4lHCfVFL_Y_7WLEE8bZVhZ2vpp-F9tIQ82ammcxBZzy6leaJFz5EH_3x-Nc-PZ3vtI-N3mCkhL_
OsGwdpFuouVfTOcS_wIKlyY0Z_FbzlqVBV-5D-s_LoSU-ocVyG8V-AZ_CLpW4vyiVAFZ3sxAEgWJl3B-S1P_gc-QlbLqj5wfpRUJZLrPKpZRI4qs2PN8uVDL
lkL9cP1qpkTCVfNv_-_oEwT8MXR_wnA_6wfQMIshsoKDBQ2xnEV3i5TiC0Sa7rOoH7esma5ifq1GD_ALNiSo389SKQnLz_1jju-7gEGQGwe-N-9kjX4NpeCe
K_cSnfTqb0ysKpF9D3udyZ4X8tBK4Qp0tuaXhMWw7hkgmTTdELqcMCRkAl953b-y_9TVYGzuBEq7w51GTVovoVzu-Vyxls_BV_t_w-k_UloC-4DDVbxyinf_
Zl_jhO5ktFzB2W3Vj_-vtW3PgG1PZfS9uVTT0x2SZua707OCA2m1cOhVxGDQ5KWRJkKtFt_I-lpHSmOqFW3MVoo_yVcxHmpuwFEFjnkGVG0K0RGXDvvf8d3d
kenD0lGXDve-4CsGDPlVxqMOf91Aa5rgkgWZEEV41JpTRYpwELQx3oM6z9ruLUu1N2qK6HTd8pSdsuKcMRn5soGOmR_yJg8nEkxrv9u_DdAOnItQlV-m1uL-
tsb8Ml3ztn2RTxCFGDEuxGG3Vx15Zm07MlB9EmwGZ--tRWYCrJ3nOTo9Sz05t_ixLCHVdqPRybKUl-00F8sRZ33pm_B7MFdh4lpA0EEVIdBcX-tF5uzHH-sl
x082MaUEd2yuyOV-Ptp_8-7w78Y3_bTw0M88yYiryyFnnwqJx903_lsbIrzt_wBhdNwdGvCP6XtYjFSnZh_Zw6oGXlgt_s0vFYm1ep4OXWwbOkTDY-_VADUS
RAq2v_3BBm3PfkTst0vtGNRvDIuW4Hoj9iAUiirKSl_gEsW4MGu7bDq0UyBZ-U3xRyK6d3x-7m00
}

sprite $sa [128x125/16z] {
vPlhagim281hhj3T6T__RKzYgzKQ3H1ijdFurPaw-GZ110YEerZmZayPEmXkf2_zqnfWKVhIFwK1dafV-jKQ84dwqg_I05dIbwwi0WgbBntn1tlIDMo02jAN
BjS05QKldQy1NY1zwNGDy4BfIwzhW1-GllGizxxu0nE8HW9GKq12zyRus8iVdHcI61Sxy27OOH4Re9alfqyQU6XKWBVimqvuZj30VovxGGE68qZvEyE_BGFL
4MJy2ftX22V53Dwobnm110h8brtc23m-mV1CH-3msNI21dGySTcvZa3bm-dSpQbk1XJuvjZD0W34SEoOb_9VJXvjA_-Np_SR5-7pVwdkL-QxxLEEpSSclWNA
KzVnm_jZuQFy_S34nyfyPF9lRl-Skp7vAETldFyfVlX_-3TTFlPPVnJpLVo_XQ_n_ZVnT_kV_Ip__GtmWvoFGS3VAY0u_zAnZQJGy_3yNmO7DqZusCRF6H_a
0CYBufzs_XJ-dGQ093usy6iHS2qJ-WR-OVnzs_tOxHBOpYzkxDFahFCXYNVsm4IbOsB7luluEVPV9sZ57A3EHqBYwqcvNJ57z1hytSbY3xBhVHeIDFZmPlcJ
GSFRAe0AVpCjSrfQYERia2pn2QMIjGEQIcLZhG31_KWIE2lAUfXOSpD7ML_HMlJTZohsnfZHOe2RLSAlR4eeS4PjywyNW61HK3V_QaqvVAU6VzcKmuzw_CK0
3BxYz5y6OF0rfxyOWCvNdVwohvBVVwCx_JaAg0_xLDGhu-TJi7Qa4H-Jhu0x7VcP2J6iFp9NuDontC2qFkVYgpwuv_e-w-9j3eIEbc1EGncBpxlvcy-XiW8p
tZ3ndAj7Sno5dVtNL00hXdVlLojB1Lw2h-T0-nZVRhR29VcmZ7rFTFdyYiPjuVw3i-y8RxzNnPOf3LidNawAPrs_hx8SurQ9f-44V4tt_wwKydCcZutz3_ja
r_AYNOq6Z5NzWzi0Cgese6YqdqWwSAAtnbX-0v1Y0vYa_wbt0zgVxR_xY09_kl_nSWMq6a2ZS-uP0qIVVWSrFaa1FtLUJB66UpHXE2qyHO6O3_eKyjYSRja8
aEAYg8KdbKIdwVgGJwBuYCs36hwkG9hkklwSvcz9jLQr1kmSWfZ7iPCF0MgjL_1ftU7fbmEV578aJOppWM1_pGPuc5Gm2PeC3wJrr-p_3uzGBq7XaUw0gV5L
Fq28wTNFBvs130R8CR7NnO-K_ITCvHPZZNML3QZfyyvYw9FstpZ_IYO8GHclUH9zvVStQWgCNyiVyQUvSDhs1LZNsVV__grPWUhm_m00
}

sprite $user [128x125/16z] {
xPjjSuCW383BImZfTkV__xT3T5tR2GA9Phip7rhF0vwW44A8qpGiTATL9WMX5z6bdwq1ROek_ImDg2gwzACre2RHfH-b0NM9BbrO1HeKNJhH1sdI9Pu12OWk
VLm34XHTUhy6T83eqjire0D5bxwl0PqWklHPxhhumYCWqbNWuXSa3aiFlr0IlRF3uZmsAx1T3WnJWCLduqiAjF7HylaMn_a2tIyyW4emuqdSZO-_kQONi3dn
d4J_NRpuktmQuz-IZF59WfyCN3AFMdmNSiinE0s-3Jy5WsNoFxlvhsQjPYWB_C_znQV63wz5GpUVM7p_NjQVohU_siGp-JVViLOqyAct_z2nLfRunE27tuN3
nH_bayxxfs7-ba_JFVuPV6EGF_zPV07xn-8BsFy7dy80_rM1O0RuI7iRpwfZ0Ozs8vWHFl7unWAcfYE2DIhyx03kkd-xV6BmpRxxM-CJcp_i_r_ybN_dy1dx
dsy5Q8YVgJOD_pG1xEF6UNpd8U0Iu8eH0tXx7j_wWB_QJ4eKT13chxk-pVAREy4wd_hunO3U8rpOnwSkliFzIkWEuqDJI--heHWVMkl18NnehmW7y6r7Cz7A
yw6d9iZpGq_D8C_7dffuyI_-nM_WJxhyTl_N-GvnylxthKiw-9pz7zF_PyGV9FZZyJSH_a_yhxG7El3yhoa0VDpvv_i1I64Q7tR-stO0TzpvDxMU_zkJyCNy
1-3aFq1x_eDs_eTw_j5v2YWdW4r_bg-SVtUA0dyw__5m1LW9e74nPyiVWlUhUOiXkNouMCjq3P73dsgxMh_yGLuQvy0ZB6xAzoKONtMLUGcuptndGen9YJZZ
Ku_HpJlqj5xw428BNrRWYHzjZeU4H5xlvZjGzdQe8mEwgVyEbYYeJzrFaXu09Zu8u5luESpdvg7cdq8aK0kJ37rQL-BFWzvcxyeR3ul4Af-V0F_CZ_deowKx
VcNETofyWVn_D7bq-VIIqVflZS9oDpfNwx_41mZHpfCEJ1x_UTJDaoxz-7JfvuTJvCjy097GoUnaqcf_VCn3SRvqKPI_EGPnjhanOBR2wJhysDziTH2Y55vo
9VgNtz-8AJ3zM_v47rouvtq1fjfx_U_Vs0hiDly5
}

sprite $pv [128x125/16z] {
xPlfTgCm38MnvKLgUmxl_xRZhIb9CrwmGCaCzqUpdC9tRHnB5cPTTui-g6WL4Dr9bdws0tegMVfP3gWgMVhH3gXBilIZ7D2GPEbH7v9mpawWtVeaIJf77_o4
E0a7n2HP-Zu7n2nP-fW3EaYoz3u7TB1awNK7T9Q4yIICVsxWueloYMGDNFp_ci-HwSqO8BhuWdmYMGCNNvJ_HR86wEA_3nyHlVSkobgRNiFdyErkVY_OEsj0
Qws2bgtY5re36EiyZXleGLlG3z3d2ZwCxJBHou_iBlJM1BGzzF7HwZ7spGDOxEFNw6OVF4lN7RJvNYzp0fpYmp8hyzPyX1FwdzRgw3zi_7rHS_Wx97Imz_UN
Zcx_02gjrpgSWxm3FJh_c7XWw3sOuuSpfOaiJFscQm8ESG2CouUOuBhDhyq-ATAKniJ0bm8G_0f0T-4d_Mkmcu-5vXJOvgUpRq9R3i0b1AVWkmc_oUFjE2w-
ocq44sr463wc1C5IxXnr9ox-naNgZjZTD-cI4yIBeWRvDCBVMddCFvuBMZ5uBxzJ5_-r-IJBfuj_yI_-tzFFIVmonISxtNutLoHmSrT0J-BpydCttIBD2vtP
O-4xQUHGgJxyv3-L0PVpDElPu0_5bxlyP_DQyhAn4iouYs33MMjCoVfqoGH3NchTT_8zL8MQSuCurrQXsbzd_drE3L8OBsT0jFoxfm3xpzQ_nU__YDz_5B__
ZS9yyVqdqlkFpZCWl05iVLc-yFwxKmoyzFx7mmqmRG1rDgnAGf8VrqUsh9CS3x_BW56W0DBo3fJFArNBW-yoO9Q8TafZ-6FJIbqZ4xx7WCcjDM5vZJgIlJ9i
-0u39dUwYzJqtdGiz5TEVhxB4SihqKJk13R-EiAFRDSn-ZWtm6_xFmnzLpwpuLi6DkClzO86Pdp3W5cKHRGgtrw5Tfc9-G68EFzeNV1v7k3cLtT4XkljxQt0
Wyxpuwizq37Ufl4r0sDy_WU0XlW7F83aHYgBR_ly5KiszDRFlqqRQ9x-3m00
}

sprite $job [128x125/16z] {
xPljpeCW38Nbeq3Tct3_T_lgr4MCZWyBDHddpmmpUmxeIgtWVR5mn5MUGHY8bzxQ0PwAbzxA0NuLBxss0qmIBxsM0ymIBvtO0XQAbuxuGauwnHWWWNZfvGwG
KBpqV0TOGRpqT0TOKRpqk0DieBfqQqBPatF6YftNWzXhKCb3WEtusFcFusDBFdP-vryKCvhmiTRCq_b5V6pDnqfyes4lRHhp2zCWPlvVU_uVR_V30UZyIpbx
a5iJxOjc26LI-5yJUd7Gaj4xUMY6pFYpDz3vh7pauMFdT_wCDpnyYod1lsB_EpzXxgt9noH-y8l3Xnys3-TySPllT22bruaULFY5FP__xLr-xHneH5u3sFc_
p8-UuSxpxAlsgzFB7wWFWKwwq_WdrqaK3c5Ht-QB9Bum9V6typk_ypk_yt-Lx-Fy8P3O-8Vc3p-KYYQWiVnV1P9gvKz7WRRvDsoMyFJyczC0O_KrlG3Me00y
ClFPwz_ixtyyCxwr0VyulcV6jpJ0kFhh2xwL0VzOVfe1WF2XtcfBX4yoC6LU8H-4eS8d6JZsFujVOG5c3fzY0QXvuvpHUgckJdox7T_dHmquDLz_AuMKIzKR
X9BJiJGa-7X1UkPFDo4uPzLi08Rvs6nF1dVnCGDlFYo5BJj3OT3BPG0QVCJ0cw_Mrm3pvth_MQ68y4dyPR3rn8R5YujTWAAjTJbyvOZmtnT4b8q_sVh_ilkF
RWD2qV_F4_FFue-bxFxrFRZmT_7NWflZhwF5Nuw0apAtg4-w_yPcyoat03ajSzyfU5h-vmreVRx7rzraKz_R0LOrstt-_hVR1g8__my0
}

sprite $pod [128x125/16z] {
xPk9SkiW34NDBlLrnl__jm_m5gVOPX5M5skcaqpRv5m98OEHnx7Qy0Dd6naCTyPBlri19esNVfS2F3LUUcy5c6Myz5uAiCXuwS4-EE6KGS1g-uUST8eOR9Su
3WL8PBpqEWL8RBpqCWNOoNZfUGgmi_7IpnNWNSQCHsPyMi33P-KZyWfu-7-QJx7IQn60-F0P-LNV0SuePHmG2AY0Mor5DAajtCiFZi_mMK9v6Ahvc-DxAmp3
3l-P-obdLH9U4OPYzqFKnQLbXw6CxmwYdWw3TQHyo75yRye08T_gGW4Per0s_72UUJLPcC-7_31iZWCP7_JgqPVAatOy_9i6ChuQTex5gJ0SEnxdwQ2o-PVX
Lol2fGlmDk9RTLJP0v3BJvEELFNXlqSwuNXlVgB2fQfZJ_xhI1nDYMm-ZbNy40OV17Vqnql-9sPMlqE-i8XMrFBnuUTTVBhnyU6pyv6JZm__Z_EHbuy_c-_u
-UxX_tg-7ChvWoJZewdntn3UBJnQv1xpbKDIiwg4Botv3LCmCfSl3M07IoX8yQNkGezfeA_vsc57Uql4B_pYj1kR4l6DhuhJhkBMzsiQxFWLQLTvwtrLyCAl
IlhQiuSb4JT-LTer77vCYRZmwwfTs-bBICI9h-ggNVFnZr7n_eTfFm2ghOWm_RGVGE7jzitE7zdFlu6Ppzv_mjr_T9y0vWQmyTlocmKOquHl5G1IGXE-KK06
lsi3vZM_jG4KZFMNtUK0oEdGVx5SZFrR0lwv011IIYMdpRNVbaevxRNy5Zsy5HVyvWPSYFjwq65tQyFv2rWPLa5Q-5sFanURxlR-OuXhhccWbOZhBYkqNuJ5
WDXp_maQe46e-Ag5Mv8jl0ODb_atal3rpBUB5902p7otGT7mnsB-SCqdQO1VeEeb_Y8h_ZJz_tF-kP1eUie_uzap-2J_Y1v02FFFWOkfxqLOW3WBlOZmw-Fv
FvBnOvcPqirF_RN--0sXhqgIZf_kYFJZ3rQRvS3VwlKitXh_rbaoV3e2I_wHhJWA1LJn2Hy0gk5JFe3ahxytyfcVlo9P4V_evz-Q1Ln-_Ny0
}

sprite $crb [128x125/16z] {
xPljTeCW38Oh991qEuVxlzlv0IssJeEDJNVc-ySTrlAyOamXOagxnLVEIWRYcMpfxtR0YxAblyi1hygMVhG35icMVfG3Rf8jNTa2xvGjdVcBBUaQOy0AigNl
Ty2AigMtE-03P4kNE-03PKlVTi1la2rzqDKM_yiGCDiQEFccV6PR0oV_N_FlnGmR0ymdtv3FR6lWv9lolz_F_xOz_Va0d7nJFhEj0UatA0Q4kv36nbbJY7GK
FuBhQbswE3RtVzHo48_W4tHFolmd0JNn9HyEhfFpEnTQ34Zm2v1VndzIKENVyQwId-BFrsqj1iHyojqwZ5Gh_xTMnF9PqkD3IrYLG0KfdxU6AaSOIczihA9p
hLjkEdsGPpPe6W3PrNSavqk_8UE7nz6dk2Xwl09Hn1TUphYU3EPtN1G6ZEpoNnu64vVv-701Bg38zsryhyq_xFotrxtun5zA-DtbYO-I52nD_dLqmQBYobTU
uSVMz5CIKDJXZy4awctks9CEFyURF07cdql9xqLgwCyBHo3whZLXowOV3WLTKfa01DOJtEQs62fDyv-w1MzpP534bn0KppzbmTTY0Dhue8iVBciB7xNnOzQJ
yY7o8OheNRqCSHD_rkGy7aJFS-rwnfDjrNCWubEdJecBCCRub8pnvlnaZBSpy37rpwintxp-RVxyn_pvuxz__cw-_yHw_z7x31Xl04iVozzf0549lyy0kPPI
W_x-noR-0HimM_Wg6q279uxZ2Zi40WW37uUZ2d_RG73zCdTO_9BpVYWrz8lUeSMJ1dxJG7Gk48NE4VKkGeZ3eL_umdR9HsN_CKo5FN03E4pbkNmW5Vow0V8P
GoNmIlp1HibDPmDs5Uqtlf_Iq4R5SzUhTNfyfGtmPVmZKjFug-t_B_7NXHj_B8Ijfo6z5n3A_UVlvz_vyVv3HNmIvPyo_dt-MQzvllHwvqh-dGo5CV-oAbvp
Dl8dtxzHCv3-B3_nrwjmUEqDCDEpjt__xMK3czt_0000
}

sprite $sts [128x125/16z] {
xPlPbjiW38On892cFIVl_xOL6Bma3eijXqux_yMSsEFaKp3QC7ayJek-AEanGBJJMFgdBQ13ZQL_oW8gQYpzRWkeIMFfTrb0NHfB3_eQ2PSS13gjNpIIBZ46
QueROG49QIpzd0KahB7qFWle9esbjrb0DsiilMm1VKg3yJGOVsp03tyedsYi0J_y_vhVK-cXNvHF-RtmwKgi6j1XkzDJbau6u7egogPB8HqRbEEZLYiey_Tu
jV3pfKwI7mYpLhxQQUM7YnhurCatismQLxHc9yYtAXpe8pvTucliU8DLF_mA_tTFx70ikiodZmM_VuBlR8_BRI_ajrhhB_Bzb2BPDkIKGvuopIceuUk_XbnT
2RbL9n7blwGSURxPvz9YodLQdB-Ci5IGwl6-E_ZqlVZJMVuR_-_Y8yTytnFqW5MEVtM-xnUsnz-5J-yCC5Etj6_d_wRAy1lLpLVGyVrFy9LwT_0KXiNvuRNM
dDOiHF6avj9If_zSu5CJNnjm7f-d5wBdnApFygcHhwt7edDQVIFVk7grYQ1t_52Tv0Ba8XzmstYwUEU3W6_8PbZGxlXQATt4fmhVPJI4sRPlinJFI0lP2DZn
r_XRu5ELRvSRhDufJ8zubRc17zxepNjuCY4ss703tyVFLJL5m5ryyhPiGRe1xecVvYTC1JwryBEB7zvyOxD_Fl5pEi8tUR6g3Nzs0GSSx1QnXuUOU5WavUhO
qmLbFZx5tAJzsGF-kZvoYO_MLiOFlOK3FZTX8dmTNFmW-wGC124us8FvXtHD2p-dm3dcPham7Smcxj_CFwmtjddlRdwfxdhXh_bd29_zr0paquk3VeRFa_Ig
rrtZJpaPZU9FXMnpaj_GXqG-tC1FzKTDDYTQu_koNLFzHNE1VJGCQYxFd-klZkSmpVNdhj5OsXBhZkhFZiT0dVLtBi0v5HJgxvx7K7Vq7rrFmHhwBtUX_pgz
0BRlFsC5y58ADVIVfnTWN_hlAVRVTjD_JmtzTntVmd-j0PIQcjOV6lZ71i3Kkm3J4VeR7i0Xc5x1IVpuvzyuc3zy_yde_KUVCs3m1h37Nyi_OG1AuhiDuDPO
5DzhW9-iBBxJW6w-o0PGhZUu5SUuBXLhJnzMMxqCly40fdBcrpvMd1f2tn4Mufq8lcw03zK-GXXw5r_giCpb6lfzcVt7ReAOd5sw_tvU_QnlYX3Q0EsvAqdr
QEHpVsYWeUSHsu0TDs35gdoU_x4_Cu1Y_4VT0VGq3trQ7mTJNUyHsm0VYt3aGV297quW3mA8uOi6mEnfDlETXlaqoE5B1h2dSISI_SrFsY7FF_xZTMcnLVG7
413ZZVPpost3V0pnH_Jh5mtWNZnv8C-yO0OVWvV5IrOZt_BtDs86FBujV_3lhqH6u5l__kso0TMF_mC0
}

sprite $ing [128x125/16z] {
rPlRRkGW38O7CATkfRp_soupcLC869iOK7spMwdgvy0VV2BRrctn9pvjMs3nO6lfips8HLjBd-L1H6qjVRG7aMHhwQCyY2nRIx_Rpqguv2B4RliNLz8brk0J
ubPu48LiBRtFWoXiQ-ay3-8WMqkdUI112TqUo3mbG9y7KgiCoeIERH3RPRWfxTdyACbNsd4TaEKhPHVp5QB2ANn4XMEFdHSVKU4SVbs5a_XL5UBya5i_lw92
bEzqPWOzJQp9JAjlAweGpVJiJHtjXfsdLkM_dbbHXTZos_CVX2hUgQQLLCZaLqyphnN1x6M-AaiW64Moamgnjw_8rw4SQebcS0VQ_AAEhI9Rha8slw11HyUh
M-O0dtzI4Krx5GaSyByaVgP1glOghq3zyA_oZne41hrm17Jm3ngqgbzylVml3NAqrmm1PFvx6uFkLjwPdx_LdyXNrM20VkMT7CWFrOz1LOEv-hNpBpEjuDFW
u-_OQpEFR_-tmhxp3wGG8ULUXNs6aW9TEV_14WTQwkVF6-hERo2Kyo-q48sqrDCHD7Xyp3VVqhe1pNAsga5TZCrFFbu2qlbD3UOQs_bu2SpWDpNeIlctQIVj
BtpJ0Lo3KCh_eOt_ZUJAnrKZIe3pWoQ-PRIZQ2sLgWRF3mfDvR7vY0OBg-KZWq_igMb6JSBg1n9_5T7W57uXtz5-9X_Hu1K-ewtAqI3P0KvVLrw3lBwBl0QP
VH-Q1fqNvmUE1iddNun4l7qVznGDaiz_-hw_Eq0K3HBZ7q_thp_esXgand_UUs_96gJcFynppr4rICt_QEPEAKTBWzJybtlcb2kVCucQ_xFFN8Wa3HBhduwO
GzCWiVwhG-lrBw91TlsBdFBLyX_H8Bl-h_EH_eVhwBrnLJYd_zF3b-n_TV15-t_r03od_rbFG6jy9zd_HVBlAVrlf02Rql__RW1G-DBp3wG1DcF-WpLWPyo_
cFrdyVbVDW31-GFcdzW0xZp_3TBptyYQVr-OlvFdtuBrGjVyVnl1huMTuVUFyB0x-lvLu_xBw0jWZVi_sno-RSzT-XnmuDjyojYfqm5eDNtG-s_Nxpzw6reE
icvUYMi0kVyeSG7qyVpM1Gl6xilimK3w-RNclZrokUB0VVz32agfIjltEMLXwR-6q8mKkO2xyvNnz_8KxXs2v4L8OHX4y8Hvt8Fl7ys9fBJd-m1Dlj05wEVw
XqTtGeVaIjWJ8H32S_bxQkpb-Di8ljW5-8mVpPwRDzPVxlv_phSFS32e_WG_GCZvIO3WdK7VlsqWFpuQJWQmHe_ajo_U9QRRO-3-J_3E1uVmXtw0ulPmWuJb
iT_Vs7kcbHw_EeqR_05Gge5rgdaOTus55o0uCCRwACvV_FsLI3Rqfxz_k-n0yy__1m00
}

sprite $role [128x125/16z] {
xPk9Zfmm3439vMDRYV__spg1cU782M7IIdLLZTjXUKxY6DjXv_coy0-lCWyGtibO-hSjuAYCfN_B0ixAMFhJ5d2LZAK_PG4toLXwPnFueeobC__YaVGUSy0T
P2pzkWNSKSRIsotW1sGilTu2Vb36qiiMy1TaBDtBprXyOWgOnnhmdp-KVxo4hDO6cUL3568oEyKourvnpE0_DMmK5nHBPGEELw2Q9eLCUX9Hj2fQ5BKg61GZ
jA288Uwj-Cz9BBBXf-K-pNnGIcdX6-KLpzyfCX4O5BjSkb6SDyIBZD-6Qv4kyVtqCmN9AbHIQXpWjFxWi9EtHGp8D3EQxen0nOl41x5em2KwY7EOeWLsyfxG
oaTh8KztmV_49nqzm9TDPJCtHRlIWmKMR_AvZGzM7IIp354-N-U7PJzBqWAhT4V-UzdFekCxDXe0AlZA5fOzOe75Iu-Wtx5P1goR-D8onCV_ktNtH-awCXtc
i1zjBFxi9w027rbs0qWI0Mt44Sh-N-AZCTkxo5Ft287FfOUl_FFwBl_W_tGQ8svpbUEtRNnkvozu11VSZKmxds_ntNlU3OHiASrtSV-xnTS-jz3JijZ-xcPA
ykFxhynNQNumxRNea-HYQ-eLvHSZK2Ars6LjT9f--cn8F2t0OVpv2QYAFllxmuu8f-zf__p1H_ZJTZRsyQ76__DyAIfSWg-3GwD-Yn-_sONY-_oq_qiwJ_nE
lp_9-3OCjl0P6lcfDMha8-UMln_VXJeoFG5Fyvc8h_1LBtu-0YLBcttyqL4-nVcQqdSw6b1PwyJuOBI18jyg1HVu-wWPuukBo1zNv4zN-AZtySUS-Aj97zRc
adf-gkuzvlzsElBn4uiF_DDFGje3kPBlL8gFv_6x_dmuht_8EIOJcVyTpnc3z_buveU0ltcsciRjd-LZQAt57D1iUpJRQiT4tI_FptLjzdTnzV7FxKUIZZyj
WlLyFDJV2YvrhIX--oB_CFqv_yyCzx3-dmKeye4xyC_zXrS8Bl4rFSD_JK29x_WX_YlWkuJewF0b_bZimZyMEN41xYA7vzyfmqc9xNL64QkQI9Vm-ln3242z
Z88Bityj_YIgHfV7k-h-Pt6aEhwKjddnk-s_HAzdWwVd-Ha3ulWyVsxc9tt09PlbDfF_pEryxnldZNSbxkJoRwDTEZYT0f6vT5Xru-X7xmUVYJ3eKj_UEVdr
vm1h_wrm09ICFza661MpDfBoJuPUF00hzpz_olLtoeIAq5xcput-toOL_U_v-_owypzdHSIzo0Q5LmN2-MHKmH1mjefaHZK7mB7rltFe3xv0dAP9bGvV4kyV
wENj0zbW2tzHGjTpvI-5jdiheHnrIwc-yb_jyJB_R81tRGWI77shO4p1e51CgS0FV__eUmOCVW5i_clvbmm0Hxtmbmmm2hlXhnZGnk__0cOJ_-uBeEG8_FD0
50di-E4JM5jHvjvz_nMK3KMMf5_-lCUz-6J2lotTnkSDy4ybYQXI70Fv711MllLegGpSVNpM05WAt1K4lXVY-RWqHKXhke_F6G0XAPCodDuyptSoV2zPNvox
yDrsd9xd_twQuz23dtuRBSLNPkq1OGzyhYljulFlrgP17tocAdGSzx_bDGXDVV3fKpctDgTs-qySppkWJVO6vxxyDVxeRVpn_s6w3J_XW_Hoi4_yNHAy47-X
8xvdDl9F_lvDDmFcVvO_yw_RnUUztm0RElhnl_zssu3YxVy0
}

sprite $cm [128x125/16z] {
xPlRTeGW34L5BibfkvR__xT5PyHUh28JpDZXlDK7zY532PSm3CN26-uQ58HlqgMVxG2hqgMVvG2RqgNNTe0iwT9hES0XwT97lMd29OE0Ohr3aouHWoN5QJY0
a7JfPGuWB5twCGUe95rwdWDKbYvzsm7EaZ8UolXr0usloWTq3JJ-I_CbLdgF600QNv4Fw1fuOZw59FxzQK_yCD-P9BfzuTvaYxBu7rlyhWeVkJz_uz-RwXP-
bqdl1FZ19Ss3sRjiSGuVAchy9-43kWOQ_wNvE6PWcVpyl1mecl_mWPBkBvD_rzyR3qNpVmh0KNvgVPzlBi277XyNv7zP_CvjSydwjvWlF0C0kWOQ_wNvQ3ew
0IvQ-VHJydZNpvgJEzd-BraIvw_b_wui_vVn1VFF9VbowwyY_ZBOx3p--hz5_-t_hwdf_oHW_VMlEd_F05FIogSzPHq0RAhI-Nls0LYjysUqy_Uy-vSwv-_P
5t319iryPxD5UNZz-szMvglNdsZN7vrdGBa0R7XQldBztIa6dhh-iRe1cG9GYWd0nmcJFR6tBeoNjDQn23_3W8zRxzx4hIMPSJDgZ1_FHD9s_37yle4mejaR
6_aczZfkltjYjYQ8u7SDs2cfnoJCTEkpDNwovMJmEmQuJu6EyUTfXKhJ7qu8lyEFWL_ugC4VQl2b2k3d-0VFH_XozVzk6kXnl1FdymKV8CHH7vXTnENtN_G1
H8XpZHc7Vat-LaKaUUV7cos-NO7HTCl5WIJnafdeakzln0mCb-KhlxyIYS2btxyzR62t-Ky0
}

sprite $netpol [128x125/16z] {
xPlPSkGg38Pjq0APgVBxl-qn1dTxmHYnXBaukaawhlJt8mH2W9UbsEoF3ROCC7koiVJVLc2ZDfR-MmfiqiRIUokmMJQMtak15TbOUcC9jj36qgtzOqVIM_Z0
Dh2nz785jg6DfSiLs0usbfwlm7QqiVHt1VONR2pTsSzO_8CBh1qhu7_-KBxe_urXsepPD1AGpsO4fUPWIcaiq53CP_oWlwP0Ag6Gpp0_c2RJdSzwJfYc6lvt
C-EntsEUFnbmkO3AneSue6vyKdEEWUd3npdJSWN8y31dcouIqAZr0W42VXgloxeWdqz9F9bRvw2O_pSrxfEHluwuku2SOVWtj_dmWey8K4ReW5BlXuRU140p
VjBx7p_V170hFkRWxmAqY5_M_5EONmM8753K_CiekmY09doZS_4t0To2p_dugm3CvnUuNu4tFz0fV2gCm1BtduO0J957t80_v_5nIe_EKZvLy2UevsCDN-Vo
xQEdelsQw__N9CJsBVpZuNUCzHg-jKNXxzTNOM9-u4-I0I2S_3FuIha2DPDl6_DTFMnSWMxoPg2sV2MgGwlvVE63h0v_uR_77xApppX5QwNyLDqR7VydldpP
TnLWs_7toiUuV8XSpwTPnAVpFW5mBPz5V3_X7LOXYYlviKPEEt-A9xmDhm5Kbe2NmlSS06gRr_GkpN-yy5sNQTwweIWW4m6Wjx6sxxGP_qcV-Mx8xc68USlm
_0x0P76uyVcmy77_Z9KEWEIYzxJYtVXqpBimJRKTmAbLztd1VUVZbB48aktyu7F1qOVFZtN7hUR57dmB3m9k5I_RBlpR78HHVA2svz-J0CQSJz-fN--cX7l2
kHj0UCVhmtfXsislHAcw1sxB48nlkKNJPOyGU2WsesL0tcROoo1y5M2UowK6_7S1nVobD0RQyBCFlWpqu4iE_f8d81NyR04f5vJnfKUVpyT_HVo2iry6zSmG
yh_xVp-IoOYk4XI4chEOBpnxNsjhX3MzAAq1YKrwk-Q9t_xmNyJlSFj0mkzn_K6GVxfSluZdNyXgVXC1CDyz4Aq1Urq08hmQcLpyxzs06Nm1RFbd-L81YSng
4ELueG1A7BMRftFuXlSVTM9xuOdVyWAcdiNjBxe0ocWC0j3-2RQ4wugjzMy6sVs5pm_B-KjiNbrJlWgxIUZseToNRrM9DZIxH1mg8F_GJNbnVja5N7BxocPT
Vx8ZQ5wziGbO-z_uX-vs47qVhYadoY-yVqp-ks156ENdS_Uxxt_o2OxN4jIeEJp4AB_q0ZJjdaU7sKuNtEy-_iF3LPZXi3UuQRdpbt8-xZ_ec5O37_V14AGu
TXt_SXljn5SXiR6KNtu1_i3VNRnDlQ7_CSl_5VV_3_nFY2dwj7-BFzVsLFpLl81mu8SXvg4hXyFWvDFWl8-_fG5_YtbN1BefXlRDBWgdVUdvf-hrJkFFKdZ_
0O1cNswve5l_WjVvrnBLuNCp4SrGi-Ae5f31x_e2q3k_xmj83DIDlzW_rIL9tHjWNLUx__xxRzK2Nh_-Fm00
}

sprite $ns [128x125/16z] {
xPlTSgCm38NnlqxQ6Tx_RHSPaj3TBYX4Yf8skk4C5_baOIioCkDus732OgE3uOlvqX_j0RurN_gZFC2c-TAjFO38VEbM7k0cywKhku23vai7Fk19ruW15CoN
Vjm3A9el_NOFO62-TBa7C3HV-hu7U83vqjbEllZ_X03mTU3DT-K3lWwy-R-QVtsPuUC0yBnyAdco2hIBu6jkGELhkGXQYTBlQ_1h648OCeimYpAmA41c4Uei
1XQfYmQAmv18oiSsdoslHEc2-U7CFulK1VD3Y2GDm4RmKuo5hV63M4JxAcWbAbyhTHzL-748T6I6KHXy-TC4b2w0JmF-ZdqAfvyL7r9-sfn6M_4lLO4FQiU6
lpF_O9rzR-1l_mxPZ1_2yAUOo9D_FFy4NtxTdlyGFdwhzNzruBdvq_-VHVwNyktM7snhFp4VrMVy3QBm7tx-k-ENyStoZp4VjLR90WIyrl_imBFp3___vPJf
VhvX_kbyitslX0z1yhEg_uJyu_Ml4jym_vZoqMhRNu20v_gNXD6RdmtpZwdZald_0lpMcYUVecN-CPp_XnrNopy77znFoJ-aulRXD38LJk_yev5_gcN-6SsM
iR3-aTJ_RIw3vmdzZw3lHOiXATJV_1w_J9kfo5PNel0rJQxbhuBwbfNlDCdm1Vk_kUF1LXRHMmzTz8u7YxdZiHAIXo_PW9ROnt_kUFJMHpntFAwYSQKSUirv
4SBtFtiHu3XIOziGM0IjXGm_dbmIX6Ftxo-yXmDFrl_yzVrtz_CdtkUF7kU0ym6myMdvpkVl7kB0Kvz_D7T0wG1ehLJdKoRSP-CpAQJ5bpX0KtKNOYzw-ll1
68DigwDq09ThyagKvwCefLTSLGilUIKREuwunijTjjBKy99tadrBJDmPAY6MfXTy8JzU-CJbRyoQmzyzZRRcS-pJVFH83R-_9rcDlwiYx7NfEB3cvtKerF1x
Pm9M_6dfqpJ-h8iNyvVyaveoVtCEBft5Vf7aN-SFK5xo-nir1yQNvO_uk1UUx_i2p7Nq_j-_tUt0xi__0G00
}

sprite $secret [128x125/16z] {
xPjjT-iW280J5O7TdPF__sylQcBIrRJ6lB2UXIzjTUk326Z534Epy1UFCYW8FuWk_MeDk2YwzAiqu9UYIpzR0wuINVfP6l0cqQK7-TA47sa4RfP_h4a_mWRp
4gUX0HyaklGs3VXWqQLlqu1F4brwdGPyikZINsl0LuaodfNnPGLklYgVMLU1c_-d-KVizFOem7pp5VdCkWhyOZxwBFJSz4veDz_rMJ2raEch1Qlutw_utIby
hft-cpz-LJVpKvDnuBtu8hWrXRe3-DvbcPmPmWV0sRS9mPM5QlYD8KmUh8XOWVPbW3Qu3LRlkYxEXB-OZxRl7gRQufLyA3WRjFAtszuLlTrHcmAR-MubtDmr
_6ny2nW4RDiKDF9nX9aSTkJ716Jm0huhpFRa4Qw1pqFBy8Kq3HOb-YS5S9alN-O__kOTmpV4penVxiF4ZuiIF8Jcg_oV3R0nzfApUQ4k-F8vSMrsZtVhNoj_
7BuiWaj-QEWNh_NyxOkEY0-lKywdq42SEjAhgUBpQLjVUmeVNPtWl4Ec8_bGkUdo6pB05glwe_byy_yudtNvl9TlZ57a6o0YAF5fb7FvVgtPcIJRT-LR-Evd
jizyszMi_tlvqpn3zyIlMty-dAzj__V-Pr0d_kYQ-DFEF_hvz-RluwllFmPD_YdxxsuR_vq2XAFGXjyV-P-g3W3g3dksd2rKhJzr1s3v_5UIxUG7y4vgVd_U
v-zrzPVLy_UQKAYhlxnImDii4z_PQi4wl7xzcvJvwlTFjEyVNQU0yWMmuTVoZrHWTUjzpGL0NCiy5zr_T2kPzweBc2lyjWkWv9rru-gFalp7jmJI7FPQ20In
CNVA1i01jV0B2f3hZJNfk1_2JwvKvq4RtePjaUjjh4ZapbWaiDI2BoZWGwr7b83mLloAKkd1zZ92KSA79HhGBplbhpstuPyLW5XN8uZZmjJY6NiRvyC4lakR
ljnPdF_M2z0eHau7wIZ6ZHK_iJhCrRuqM5fqblZj5x33Tj9OKM6kxTWqp2L_sRcFFnG287gQZ1zING5B_Bcpm6-_01zJQQXn4gKvbq-JLuXR-Dd-bF_-YR_Z
_hzBfpZ1lMmQT61Z2Z09Zf6_x7pYxta08SGLILm9puUgRmYnQ697X4P08_z79-x13pz-War9Hrmnl8ts3aadlfs2VT7f7_V-EvzzGSYNJC9DbwcgvQKvPiAf
WUPEX4N-LNu0vIEVlpbCWU5Z-ShFNnrYWOz-_cst0c-__Zy0
}

sprite $quota [128x125/16z] {
pLlRbgiW35N8ZPbPg___jmS1hwKGGUt9IsTKs3iXn13mzMeMz-EIlBuWRYVVHN-QWSlATz6VOk2AybtqknaubNmN_Iu6xfHy5_rY2gvHlelktA_x9leLDZZs
9YGFCZZsn616VCm6HzNHZkCu67bc58vszwf7eIVyu6Zu6ToBlTyJtvhok17svf0R6UHQmh3YWnyBliq6-NQqDS0usBlYmQTMOdO4w9w8L6W4M_YsERZAp_bG
kni0l2Ke5vuNXWlL_q2W06_7ZV-Fu9x69pW4W6VnqwldElLTmukUqLocVev0lKru0svZZoHv27zo16jYx652i2Q91IH-0d-Y4DpHZaVn9CxaHks9tiOJtpWW
D-ElnOoYa1sB0jH8GATx1Jta9tmNlcoYa8-7tk-IsKsyiDX0Ri4di_KsP3_nmXNh_o2qsxjq6l-KyZPvUi9VvkOf4voCVald1dYVbTZSrAXxmIdyDG7UQdR4
dnWiDFb2_6Nezse5_4Cok1YgHc07_-TKoG_A8IiStfDHGHs1F_sxrtpg4BBP61aL0Iq-5rPUJBaN3weIDMtkPzKkzUQiLlhn8PjuUiMb2b_Eb7NmkyHxrYSu
ETNXoycIAlKqQuXV2TZXuo9iSLPJ7G4DVh8-pTtInYMokk6GV8Mg8w30vwMJH80t3WwVMqok2ZMdLQiVZEW93BCsSLJoqmlyOm4q3HtK3L1JdvFJhUzLA2o3
qQGeJLe3LDI79TtUpufFPO3bELinW7BLpsVkP7n1Ml4BReQgXRWjLojcU2f6NcvHJJ5CZbrPVIv543ie2Z6bUR8Qe6n-R55DCq-g-555FkkRRoOSe8ZVQ3pG
UE2SePS8D7BNUM0iN3RXKrb1iPfI8DOTeDoKNKDqK2lXuNyQJJTx82aS40iXs1NTlpI-e5XhnIK2DE77fIInbs9gbdTlcTfnBKmKff-jLLnHTxUuPw4hUMSL
M1x8txKwVAVIFsVYbQ2HIiM-PRzWYr_MVxJk1dnN7N_GZl_GLBADynyHwSDQ9on_9-Fax_fcXD2BpzMYIB7KmUqR5bWFRqA8BFNusxHVH5VijTID-5cvtgss
DOWsRTZKaZTz7xR7TbrxVLrZIFtRBLqgz0z0Pm_GkzcAVHQaUX59eNwx0htjDVnVTVkr6Y3HnqeHiBE7JAiTUrEh0TOD44iO0bOr4cHZHiewzJK6c4OWR4AJ
nkU7-Nbj2RHUViJKNRq4kopQeNvKGbF_J5aG6kN9Yxd-1_NDwhN-zwCf9kkcmlvveon0Aml0cWhuZW3fu9K5S5q1VaC0jV354ZIqrlz13ryv_d46VY6Wgtrh
jq3EdBaA1DIR7oe2vuvyUG9duSi4y6GAotWQll-igLPkE-pQ2Vzr_3u2qWtVHO1qUT9jvvtjAFtm7GHK-Cq7lWK1I8YcgSrnXiSVW73mI7o640xVCAOhZVYl
Jm7DU01ZfmGBOvv5yTtahrkEcPht08nRdnzyeVK0hW_0A49cEE2ZXnR12Su_mkBJB-ClUBRK39yZGF5TYkCUNqnCSEm45yQVOewCsLT_-m5eZFhm0J_HYh-B
_ybqN1Gxu5-P72Wk0SmH7zt2A-8Bsh3rtON_TXeDqiRt0H_Vy2S_jKWv-_SSW4_sbutz8Mj_Y6TayBtattN-dsCD9_XV11MxyJ-O_S_FGevx1zW7VoImcNz-
Yf5C4ty__wP7ECvJV_DOykp-0CA6E1FCCCMSQO6pYpzXhMeaZB_nDsql_i47XNnKJSFW_voi4LUvk4HRGZ_swN-YNlXS6EB6KjvLtnurub_t0L0J_eMVFo4z
Ylzolxt99lHz0NPhjll_V__MJQ3Q_Jy0
}

sprite $rb [128x125/16z] {
xPljifmW343b8oIvxOpl_xP5H1PM552KTgRvOyPnFH53I28xpvU5VzZBF40uaR7qjotWh8oblsK1dyfO-jCMS9MCfJzb0JV9M7fd4_YYZAKp_-AHz1vZm1ra
BFsw1TnHnjBRBU07P2oztW9-KCRIonRm2pAMliZFMFp1432FDU0_VoZ_-nBIKYfajWUh49DA5CsCgGBCPZbA4odW54rb0xwlG35D0fdaP4MGLwHLX5VGAShI
d68DWQ0inybQfDslxNsQ-KO88IrVYKLP-8bY1mATejTB8mKMGnQnpw_TjKYN-ClmCpavLQYar3Z0xlqRm4xUbZ7Wf9dHNQmFOj601oURdXPFQEMZrcOatqug
_HwVt-RpYtmXX_Ap0Q22B_I3aoBb_yvORGm--Vo_NrjxTIx-f0FmB3_h_oK-AWKZ-K_FVouC_-DyRkSJ6j0V0UVNb9mo-rm3ylxNp4Vj4fuWqvfMsJGiEIqr
rio_CZ-DFwJ5JZn_9vgQ8b0-Qc0oaaQAUduQyAaq01MscWpaOFp5bdj6wm_Uv7_mCXAr-f-ApsKCEFB_SxujAaBy8NzR2KYnVCOt2C9sBTtZn_wlMzngSrHT
osTJu7iFgmx747dd2H_vxFL7V9q-Jqt64_y0N1rvF00bVgYywbVyz1T4V8M_FO3v7dqR6d92tsy0goBGqJE46-vkbWi6wPJ7sEIlIFPjGCtwbGu_vFdmzGAs
zwU5C1VuONuxlchZgvW_NU6ZtEBFxUS_vVzmoVzXnyy5V37j-53ay_7mV_XcvrqwApiFDNtus1f-jW3a3GAby0v_RG69XcfajLXLHAnZFhhMMkHlzG7GBvSr
wyLSKpRv-wdA4K2Lsel7yQTIpBRyLzo7jWJ0HCvmfPCIPsqwvBPW8Y5Vg7u4Gewio_dF-IX-tdzmmUhyCt6-Q_mq_yzbtsVyE5NgmRUljOMVE4eN_XBrQlbV
1H0eZHtubWHAncN8cjPZSaggJctRp_gNJeeuumdp-vC34VSIwdKlz1Drb5oBFzJj-I_wlnHwAF_n_ijVmP-VvnkjJ_AV-N5-eG0wp28alC9__CChmb7yUUVB
xs7yEMs0qUsihRx_-LFH_tkIFxh_FFxxrz7tF_1zPbgxo-mLinM1UmLTm8aL0AZv09nx_tS--bkBb5DA7ryEzX_8TVU1hQDN_gguRgldhoK-16NoHVVICF3y
qAKjylS6B55ZhIf2aR4fc5DmgqdsIWL--FwZzmmOl05i_clvpGOGc9xuPWEmVOtekl-ndTzt0sOplzS6K0AquHuj7w5beqgl_Qyeb2rx0SNwpKdtmzSPO8j-
PIChkirTg2eBZ7xxZt5jhuL3JQ-HEsw0jiJO_vIWZlYvsl7HDpbrJNVsqb_h-l6xRe0FVEtRWzGLNpGWy3V_wuml6H3uGXFPLCtqnjVobOi_qFtn2pv8QvVF
7WWqu0Fudjd8F_d_csu6pFyiV-PVjulFU_y06_hqu___Tjk0ukt_0000
}

sprite $ep [128x125/16z] {
xPlfagKW38LbJtgwolT_sm6NArvHeXE9tNFFByljEqGs8_RzPU4NJke5X2l9qbixmA9awQqSuA5awNSxG99awNSvm5EIfITzIS8vWu2NzGSbwHmnM8Ou2GV8
95dwDGV8B5dwEGTuasJfD0TuisJfnmwmbOJnA8ml6_ZmHVc8iWO-_F-QJvlfWQaAhXcWNGMgKuVgrCtygduc7rlpySD_4F-xFH-lT7uV_g_aemGVVoBVLtKh
_vuv2AAi0PQRGIk-ioLKCBuDtoar6qYpGMr7lEwKRy5tgOrD1k9iiElCY4-x_JK-zYVnIeMbDp3PxdC6ll5qyTUSXO_sYe7J_BTYPlnh1gXyAE87VZVntmm0
dLy_BOprRVEGGyvV6GY6Re0IzdIxRHrRypC3iJa4Hhxfee525N_ZlmoarkZu-90Qjtv_zb5-g7zfQsr0hsqTy-id-MLmN_16HusqABSsaFPIAm2vrQs3x_AN
NXrmOy2pySryIxVA16G6NE5aoyK7FTzorQYofvBj3yl9NFmoA2jftYFeanD1GlZjalBeSWDX6-aq2f-i08IKpt9BRV9kPMvjopvlbl9tbeV_AgQnRtFRATXk
FK6s-bmBh3_-65DjVTXfc1iC19V2q16xuEhZryO5s6yPnSSyUE2f004EOxFVp80d_fMw6L1Itk4l5PHqU9HuAR7M5NFBSussfOFsrGcL5CxsEbqXj-oN2T7s
gCaxZCsbuMAljvBV33sPp7QyolJXdng0M_7t9g2D-Fq3-BqSVp__q8H_a01hmJzAm3RWzm_YzoVvn_q_YN_y0UxsybU-FyDXRZcK3WRIfNlu7ffERnwu_aHw
_L4x0y8BmFh7yeNNtpKnyEZrZxSRu5e06k8ha1kpqXxSlCt19nbmSRZHAcKO8AK_upOjuSsq0DUhz3xdjOQK0udRu4ZvHgxrnrFQmIcN-86QYU1Q00rAXwHK
QD1w-ZZXsV0rViZc7A0Dph5Wu_SrldRpd8FEvri03tFI3-0LVrkBF-VwVpF2flhdXrHW9Tt9-WE2ZqqVOflJAVvfEvXA-9b_WF13adViVvH97tmiS_4hAoB1
EpVCQLFWutP0RZnn9AW--CjucW4A_yuVW0ZyUtz0ylwsual_VyKo6_hH_x_ziu7gxVy2
}

sprite $pvc [128x125/16z] {
xPljSkCW34KDuaDqEvFtVzkL17QSD2O4SDITZVedzJWv5v11IFXowRRqbOfT52pTc2xztGhIGzEblqj1gfek_Mm5gSbqwMSfI2-PBftjInC-inDIj_r9clGP
VN1TuZGKf4ccI-zJa2QRBlqr1UaaqwMtAKWdcowzhY2zovJnIHd_MC27hyfFILV0X_zVysT4UYC2Klhm5VafwGhuy5NvtqbNm6lVH8naOJNaIn7nT3v6ONbh
hTbPf6jWw28u7qB4C_WOl0EYUlhi5cFk-6ZfsfAliumuaqziHXj6E6w_i9Q2MpR-QejPh8n9Cx_Qv-xQsSi2T2bmLmEurOY3i8w9w93R8hZOAE3udWXRexXd
8OZxFV0rPAVaGUAkMdYOF7r3xX_XOsay3MfeSt7I4RZX23nCnk4GNrfXNS2N7syiFMVZK_xHB-IVSH6xvXVo71auYyy473KTudClhbfMu3lvD80U1oTPLvxP
3huCe1l3eoiFOo_VG1pfVp0D_7IfEZ24JlyB-GSE-T-fxlxhrCFFtulF0Cy1wxHvtFvMlcZmxVJWzklZ4DzlyozxOiWhRFmn0sEPVhsxNOoSJC9rVdK2mnIB
XB1RUVC21BBoEFvajv1WTnlGCYoHIdq9gF9b1Y89LgPHM7PBuI8pMzmjnUQwybYA0HfSfivVCZyxrDKZDbhcNnMPCc74PdTzrlwxkHjvXNMmBlOxleo88-_0
d-jodLzxY8w63dC46ijDKJpoO0QorIVdxCW_bfX9Zs-w-OY8cdn7FeLdysi1rBAOU3B_MG3tuN_u7tw_XNw-X14m9e3RiBX-xRoW3odm8ttejYYZP-HzJWmO
tzzxZhVz4j5GOD4k0p4uAB5Wz4Fk0xdxo1KaknJhIoB79Rja3QHXmy1Rq9o5a1I8X5bX3NnA7CJ9k9o5sL8m0oFtC8gv2NnXyywVMR0D3g4f2zRO2_kcvIpO
7J_iudCBld7Js9xxbDWN9F0jMRZDH5We4OjuoIivq9TJhq7IYw5iU_9EAASSNmxOb7BVzma0NRoM0DNomqZ-VpvVlVwZNdzKht-ZCb_z_8ds-QFt2L0-07Rv
jNpbytTl4V2hpp-UBc3y02X5sXv0ed8Voaw7Or_QSZIKwORFlo85VFJ76rFwA3oWs1kb06u0X_7FYj6MAuheEQll9EX5fZekTD9-pO_ZwmA87_B6EjAs96y4
_DeL27u2lbuFBvtkIKR-35oaQ2dKNURmeIG7V1OXwD2oovvo_lo67yaBM4CJVyu1-7t_Y-j3haBa_lT-3hvI5Id-bsK40q8k_yRZBVUi5n1eZsq3bzPzKPFJ
E_GyHenWmYpyCP-QJDHohi6LwXuNccr3gNtutHVkwN0zO8DRaY7woh6RUI-WhFutUTLf5j33d_a2K0T_xWj8mR-j-ThlNqs9Xlxfzz-61Jpz-Ry0
}

sprite $c_role [128x125/16z] {
xPkBSgmW38OL225jPtp_jpt0Ag9WbukOTaupq-cijVlzX10XuB8q6ttGQWk3qS5uwKyheApnqfzIGDyQBtsq0YeoNlee1LHblFIR9L2ZyTA9FecJVeSFw0RZ
fRShe1kDbrwlW0OOBxrS0GqqNlfx1VI0yTATVV3YBrn0n2lWZy_A9-8LyCV_h_bxCQF636fpZu0ckfRpBDiKzFCDYDcR0FCy7zLAzmeKTl8h_rkh-MJLtT3E
zzsUMgM2LdxezjG4u6Z-eTip2ie3uO3_wd5yMpTyrJO_InSPTyYoyLZ9ptIxr6Xi1bIPGBYTR-Rf3D4XACwEcMPpF_-CZoBD92weurCz_uL73JxSZApdKnSV
Wj-bwmTyc2yim8ZfrTdE5N9waZyfUsdhz4bQckveFzMt7rppmoTCEg0g0pJmzO6eaxy_mfzYRnppmr2-46xqeGZcsYyFgNWaNzgiwo_jvZ_5QR26JxgIVtLF
9H-fuja_W4z__FAfLvHjOhx9yqNXLBIJhwMGce-lRSwPPdY6BnF-AcbdHRUKyqlNlMewyt7FnIU-VpmM2YYz4-OhFgRjX_lvEkr_F-UOPCR_-du-fdoVyADv
gAmS_bNyFG1bj2I1UBKZQyFFyiiNZ52U_u0669RpSGG_VFrRlZH3-53ArqFm8GM_uuinpGyEUCU7GVYGyE72nDZc9ukSl6aQPmNr5pKG7yy2hYfGPYJ_VGze
6clmFHvej2csph-gzKHuGvm2Ml3BVJ7GqlTjEnywCmo5RiCtxRma5KUxAAT6VkFMZpWslcSJg2qCxUDchRyrRG3L5i2o1N7h127xj-0-ciUYrkr3dctpCy5p
263T_irj0FFYsVdivq-upnyz9u3v0DZoO_bT0hGolVWk0QfixZti_6CPVzm1p29--m5G1ANsUOO1HEKs-usxZ15VAwMk7yhDvr_jV4k8lTY6ivjx0A6_xAU-
dkycv_R2LIWs7y15DyKp44exwFPTxHKnWp5MX5xvog6j2DMEpmfOdQjslb_emWlaFxbRpEkoaTaIMFi1QDlETSjhz_-h7e2q_NPyRPllB1kBIm__jAv7t_1D
bcUxdx0ocg27dvn6A-PFSgq5OGy-yS06GZ0nF-T_ElHJ8puHiCNV5bSh_nn_QrYI4jY7Fmk8nfzMEl33-8Cm_jpkB2GbsEuN85xvnwqomUskhFoh_DFV_2G6
NVxrUHN1frtSLa1R_brZ8vj_cLz0-PNltzmcOFcr_8K-kyk5VM-0iRQU__stRW5ll_uV
}

sprite $cronjob [128x125/16z] {
xPlhigCW380Lo8NTdUdxl-s2e1KAY0Ywb-RFwIaTlm19205VhsRHFxINrmEY0tcMVhS6EYdFqk_IG1VbMVfe3NILF4iVfO4-9S_IEwkW6-LPkjO_zPFq7cEW
EyYpz7ODT4TvbdvU0pr0dgNNQw07ohFqOmtq3JAMJXWA9NxpOs3drJJlPPBLGw3lu-il_u_Zwplv-il_yZF5Z5luUjJAy-KtyVNTV3s8Zmhsel1cVcCQz33_
r_tyNyzsFno0BpyhJ96mJxGpNqCeMCCl9lHp92wZPn5z3IVZprw1Vua_psAHX_Y4n4u8bQZZwuxyo7OLL7Z0C7wb1_RWYtMZomXAMb6m-kGDVCNU-wNzVh9Y
bPB8T_25Yp9aZ7-AVYs0Z_WQB_BTsBEQavBLW7HDy3_cEpoAEIUIYWDmaR_WSvqFvcSC7m_nMU-iMNkF-523Bobmo9y2sVZkNyakw1yADlBPHPDDlATh7sIi
Db21VmUea_oAajzS9PAJ_ClxNfQ9pefA4-ZGVKWCDQSiCZK3r_dysLLXHXgcJmNK27x2-7Byn01SvYTdFyDFMC0ndjDvjlsUCyQVvKjks52BpuVxQRUFWpFy
cHhuSuw_v9PoEiF7hdoLjFu2Vr8z-TQSah4ltt_PbO-VhGTymVytVxwDJs9y_w70J-T4NVdMcz9hlykuIGxcospkuJ9kZcFdrDV_p4VEPVrk2A99w1n_R3YN
Kpdd3oS1-_AXc7igDmbGN7zUn_me_-Pt_cqMm5BowNP-M9h-YlnVHkBvw-Vi17Wxt2SeC23_ndBMhLJ9-peKFrdCjGAv0i380IXqlrFvLpPs_rt_kxO7eheP
aDnM0Euq0u9B1o3Tzo27Uu-k1t371G0yE7ySEmBY47yr3C6vsaF_2nYKTqF55VZhEr58-w54NONlK0em6amVTAx5TwY5i3rpsC4LiQx7Tpc6Oq9GLW0pzVSH
z-z8KLIrgppuxgG0J1ZLv5GBlbc1kFzP_aqNC7FyqnT0sHWJsBuXihlDGCQs5gTYeALrAGE1EmHOsmpVjk5v_YjUsuNRQKeXxIBAom7Zii6XMSfvAmEXsstO
DhlzdDqPP1Jwpbx0DSaTC1ibo6Gv0X0DI1ARdDwbtkQpYRlW-MffKrkRTcqdyNi5q4qZcFNBFOg5ooEKuP7RJoo_iNpsEOPSsfOrXuAqu_m5QENNRPldls7-
BxcKYcnLn_B3DkLpGpgFV-rIIme_eXzG2oLNJjhuiBMz-Qg9lzr62_XSoSSql-K2l1z_usaRFnX_VJp-t89V5LZjp_JCFIcqlv0VsP-t3Mx2UmMS_w4GQ_z3
_mlvaVyfjhw9ZVZNFlxOzD7pm_WJyiEs9Vw0RkLx6pGPnHP_rnikQ_n5Pnps3xYERl6NqSPce7RykPK8YgMLuU_Vi2hnXxy0PF9EmVtnzNmfQK3tZG8_AyS_
lpEyzWROzKpehtx_xR82Xu__3G00
}

sprite $ds [128x125/16z] {
xPlRagGW38Q544XcjyhtVzi5rBRjzW0QJ7Vj_5UjvSmNJY44wFlJuXyUrIk85zAbtsq1hqgNVfS5l2jTUciBk4Ywz5OMS9LqwKa_cd39Ik3J-iEQT8awcASu
3GjOIBhqSnQmi7JfTHPm8-dIoopWnjAbxrl0TqaPpyhuTGD--QhyYhyc_r1uVvL5u_km_6p7W0eyc8TWVEVDKlxbKoV83pEcc_YumRVZioKvVYvhDsZcTy-Q
-Vb9dc_T83_LYLjgQd1C3oNyYaWlyZjNqrtjEvylTFyFu1jDFeKGI9ZVqjcjyldB-EJigAdflLq8fY4tVpWnFIBoHVxiO6QNk-vouF46YwUWluTyrxswt4sN
__ZI5S-1NCutS_qlyFProf7dUygQUiIh5k-n0J-8EiaFuhC6d-luffe_zLHo08ukygkT_XprfI34dE6_1fKbebB_-yGl2FIA1LJCvnRybKxoo_ziFlSw_Bzy
CFgly0C0u47vM_9JTE9K-QQGptfy_a_uw_DFQxw1OGeaYC7u9f_RyQVfw2auV3UWBT_IKGpKbD-fygrpo7hyaYH5pwtvQV69wCyid4NuUJdO0TtE7-SVs0eB
s_93z3ceM7wUV8vRv6dRysqCF9vBcnOkTKkNQ_oK5J6dS4ByQ84o_z3hj-JxrDoinnTYN-CZEES0jVXZ3X3q-EUTZb3vdpELPoVWy-tl5fdY_HnK2_uo8xcV
0jl98JKVV_iBi3cLNEvwgrpVKVgDq5KAGpt-tgtdcWGidT0P_0O_vJ2g5Sxm-utnLz__Ylj_mGPSo_clPF-vOVdVzx_frlR_mFCdskUFxZD0-G1O_x7yQWES
8qbyhG5awrSwakSVoLQlTEGEOCQfxi4dCNmfFsygXimd10ik2F7B30ZM05YRLfens0S7nWOPV9a1pc0cHpxcSmveK0XVOa0O4afXvfCFKlW20_omjqmG-J5A
02n9iFII_A6s4tyuY66HvFXz5J_MFSBnaIp90_1XhFyq_YYC0uBay4S6HCSRSZL4lfkMt2I8Fp8WaZtvFFxppu3xgttn2n2OEftBxOy56Lxv-n_1nq4tPBhY
puC1g7m1vIlltuWPq7yjN_d-bKWDVFNzjyi67FxxVm00
}

sprite $sc [128x125/16z] {
xPlhTkCg34RDLJ0pQ-Nzt_P80Wpj2HTZ4jgPQlL7sgJUCWZfGpYFnxJvNpxQOuFv3xQN_cuF_5FRIt-N1xvfU-clzi0FsLxwgppmbsmldUpNJlZAGV3Jzjll
fAyOWrpYTdZW5zbU-fm7Vh7jfL_pmB_8zjB7FF0ljhtqjWV-NROPxpVZdplmmz_Al_3V3Wt8y3L4ex_TSg3B16iH24go2JJfl5CY6FtDujlQ6FnSrvSBV0GR
hOXuQE-jE4uJo9VvryDuRuxeZT86bl0Dtoh24A3m1lFjIeLyBUKv89Rvx1dzuDlUmXq-u1KqNuoGIk4DEfjcEqouEmteqs2qLYguhDbR3KFyPqhFq1rPGMD9
K-ekn2VEcQBXG3U46N7WsTsBWo8CBWNsHxCSdZ37jw8sUkC6AiJ5B5y8HMC_W-Ovu4iCy7sLpw57WGU34y6ViZe4OPNlX_XIXRLdE9HmnIcD2OPMjeF2QA2j
nJSu-2aFQLepj6p8ZMa-Bc7WEmbNv9LD3b4UoBV7UJ3zcl8GBrYDKwUEE_oOUXtbeOnuaWTLSWxDK1v8INY8_wV5pnM01nd7sEOw4FEWrpGr8Vb_3DSQttUJ
xoV-aoBeSXwicb4ANi5VgW7-Ohw3IlhgrbvS__e-NrVMV-d0HSylMJN-_OZskUs0kyDtIbcuDVUcLlzAVXtF1H2LtCn4E5IDeOAwpWgeNY7egA0dKmbqFUL3
IL8dxHEgmoJVd0a_vNpIdIfaMbeW9flZJ1U5EMa_b_xxkVuQu4EK7uR5jobgZWZAh2Y1HONazp5nE6sY084vFkcFaBj9J-8BAyyQ66fkaiQH7uMvAhG_DE8l
yNqz_t3uPVqLfvV7dMum6m61QzyP82mTwlh7-p--FVs5_c85Fgo_8EoOsleh3q2VBzAkYiUMYho5JnP6HHSXA1RoHLPNecbFFz3c-mlyERFD6lp3tyhtE_d-
X_-Fy_rUVbiwhi6hMH7hz0gydjRGphA0wHQTIYbAykl6xPFeaagbaZhant6sG8rLnuq1eFuRTLg2_g9zVw6_QaOQGUlKVG0j6_glrxoZsB7kixnE0aoNykiK
9Hy5khDoFlvjqbup3JWNEqVYBf_ZA7Pqkbt-imySkaM7kCcNEbp6fCq8RpzuBnI7d2Q3veYcGyL8jRbhpHUOvXygg6WAGrqq-dCVFbZQ2nJd0EV4rVU_G_mm
hB6ZcNTNj3ZoGWVUPfyBm9QzWnNyKjhJzf8s6peCEEy6NTWBnWKmsd-upf_A8cOs0Rwu_zKjmE_Wj_Nl2hurZOEmjlwMSa7_hHb_h-v-TVZTeq-0s-4lk_s7
kWE0Cs3dcv2KEnlrjzk0ZKbDdkNyGlLBjH-pevxiFrC4ql_7Ga8r9tPOdbV1i_c6cJfqgoX7o-xeDnnmiOOVujFPhzBfp2FaOEfJcU8CA7oQIf0RmJTZC3Hp
JFFiE_VVekPczGfZtV-1yty-WeBGtf55_qqKJKPpDeZwCVl_ysyt75fS1EdMM0W63KB3VEMa-0i-VxBx-QFtER3v0R37b-LlVlxkBGvywUSVN-x0gWT0wN0h
rXQgKVKoSva_v81JbEkvi-3q-N89ViW1GrqLT89FVJI_DAlm8muerbI0ojf9Fjy3QPRX1np0Kcj2ZRLHNhc5-3wVEtEI7ewoGmD_aJym0s32aptZ_9KFm8T7
xt0Mpl6tTYM-uu1J77GKUod-UbtMjLz0e4NdyFurXQ861whJP5Zy1GXgJMFIKI7_2DbzKcJrTrymwUgKT56V6rYENrc9lkNtRvOvyFYs_CtVlreo0j_w-s-t
7UXU_Zy0
}

sprite $svc [128x125/16z] {
xPlRTgGW44K5YajbiXR__xS3A9tfH43bKfhXF2InQR8F9Kq1ZTPU5dxW9aiWV1CjVRG3t1KjVPG3p8gMtji17X8jlPS3F2LQkjS79Rnb4F2o_Y0blKKClb8S
XGDi95hwDGVOMBJqSmwmasZfnnnWPz7Iymvmb8ZnI8pVDp3vf7n4MWEJ_r_pZytqZ2ZAN3Dmh9PX2yjgOPtvHJsJZwFvEFatud-Ev-ELmM_oVoKVAVZuHBvw
a_H0-VvQL_vtEvmnRgxMhf_wrF5nyYVVuudw_oVMplmhsp_vbGklMZu-WAyWizZp-ITJ3AgQhzcIrhRcoxn15_cbvhCgbGFm0BxG2Idk4QbIqOY_GB9Kv2PS
iFJccte-ql9nyYT_yX_BNthnpIO__aEy-57gsizrgX3y-F-ZwZ7fE8Nm6OR7YzYQE2NX_vR6AAdTgleaVsUZUNb5K-piGY_YTSVsgfxcvxAvs2iKsHd3v9zA
mAFugGde8Bwz0T_IyTFx3qFucGsm4VpS1km0lhqHtvxavyV_G_py5t3Tsr_u_ldRHlEtlMMzLwWFLKtXhS6Hkk7v4-hpH-CC41y0ixVb4v-_6sBWrkSVknje
S03KI13WnrCbpNhjquAMGaZTW5yoOBXRL74c3CAQZnI3a7JSOeohUdp9W6IksMxXgLoE32aFN6xJ3ktNgeNDy1RdZo6aKkrYxKmO7u-lK43-z5EJ0z2IST0c
Xi97NcvEi4NmY_omh7SM_9_-1WWN3yDvKtx-3hYkpjUvaBiNeHCSuZSw01-sCemCNSt5NWOZM_nrvXFOwFo_4Q6fQulTp_Koz0ICtR01Fcq0cEj-hXF0Uh7-
rjn__YHBzlzs3q24FIUsaNISs2hknv_qBa_3Pr-CaY3ZV5Qfrwi0wRCNn0-WFFBvcsO6x6FvnCzVDOd0evz_gpPG_FT_0G00
}

sprite $deploy [128x125/16z] {
xPkBajig38Pj991eEvFtVzi2jfErGq0277fcZZgpyQvJVpz2N0JuyMWs_yllzfXW_cHpwTzMuBCsb_uj1RveS-btA_0Ycqk_Iu5NsLnwj5ypuIETu9ljjvz9
7-63rn0tGu4VP7FfRGhyO9jBrodmDzbSkao1lzdcqiiA_BTiCjvFnkS5_C-VobS_Wyav6yqvudu1EhQpODQN6R2ElyLdmf_ifmPKI6ZdiuFrau7bc_dip5eo
8_H1uqoFOAqPK9C0KU7jAZ5H9JJm6LUP0T_15_Z-6GMavGlmPbtl4p0M7zl1MBuIB_20Yi_vkb-MuqT602luVohyVEGR00m6fgaLA8flittjSzHZiZd_s57y
JEN3fP_bNEkaGNmGHVVxk5Ik0J7VNP-BBEmVdP2lYtqhZXCZT82g-5RnNJU03vgejee8aF7fKlUwdi99-8eIrNgrQxIWf0AAppFo2is4WE5EFgbd5g2k0Bdx
wyM_Ei1syd7HrFvR12nGv_k7jFhHIymA0-2F5uIVsltNaA6g0-JFakKMPv-vBhvRjTL_xGAgV7amGz5J-BHJ-U7vPyeB4CVIWkMQMiepqjoeFP3liI4fKlc_
mdSDELbrwYMl_-j88Hk8LVnA_Dk6ZBGwzLMq_yyE-9mCrVZolgGGWOLSJCT7tnA1fLImcdXgnhzybcXa2p8Znd_Rb8ah0X3q4TY7Lyx_S3HUEVybPGwihe1A
4s0OZLVcFsuuNfN_dSC5H-0r-Uyv0iVWvVd_9LoG1_7VMrLfbHkMqNZ9-i-Rjs0S_aE_YiJyCGA7uelhVoudTZ3-y_hdijZCHDWeDeAQG-3Zf1GK8wvuu-UJ
W0oVLFY7xnAmTFKocfst_Fx70hruiO3y_Wzqu-LxZzQqRJRrBS2Mwy1mFrwn-VksoZs4hzbzlYXevNTilv_slnlvdVl_TEp_BoiFmJ_KZs6YTFvX47_w-PFP
vu--9s3o0R37Fyil2N18JVSq-980MqXbKP7cjfv_7CHlFe0vXjzq0DGX8EtyU9ro3xP4yVh5v-CUsqqEMTBp7xdimmIBZ305Cg7ZZtCEMi74wvXd9NwOe-_t
s6o34hvjFhGSm7Ln1IlElLoK4d1iuwIBKeeNe7RdG_eTOzgx-yDSnyQcyyUmFIn-_2mORIDl-eWyscPYuNln7YJXjWb_5d0mO_sx5IWQXYVJdjz7NkJRdHO_
auXqfmb_vkypp8t_MbkWdOSx_sW3gTGs2OJ6ufy4dFdWDgCoF_odjmRRU03-xF_DvvpY7_VCbD_ydrJ1EVgQp_yVmRp5NwfIDEuLV-3t-4k_X-zHyWAUrt_Q
Nq2WkDpoR7z07DiVn_ONhYbr2xZzG8h7OF1OXQ0U_0y7EBE6Vx3tF-4wdJ4CijBVxU6Y_Tw-xeFdHO2kTr_8ecNULdpYjTiSZnokKo7fTO-UlPRjmzTtPh2y
OaET-8g04Zyuw-VTMru0Al7jQTVZdXUGZa4sdoOZ3IZ-xFUlXio8_zFlltKBg3x-Bm00
}

sprite $crd [128x125/16z] {
xPljSgmW38O5GY1jPxp_kpsiwxRQus8IWcndzltLSJi-uKDu4t6UrQ8FMZKF4Eqqbdvr17IeiVIh8g2gnj9xHq0iZQNtYe146ait3e6K6aid-gIHT8i-80ED
fUiZ84EDfSiZe0uQI-T7G1qrbduU0LsWiVIRFipmEQMSZRf0Vfi4tZdlOp89GDnsSAjy7C3FmVqeNiy7jnKsyuLutE6Tpwq1I9i_ETiE48w-t-Cdk9QVd6iQ
W9VZ_nGpBk5Ju_HxystvvniTngtWDz_jVewOP06ShNRUIHMI7H_S9EPF9qkYW1-TJedD_vAijUmU2BMxVdLllg03H5iTNpYO7qtueJkVHl3fpNyHFetXqvl_
vj_mE8QVYEUzkhMVoL-TN_0AViwr-eZC-kOeZS0l2e2vmjVM75WMQ54919y7G3q3E9aAuin3wmMVU25vveDQ_c62LF2olBUX0-9n1qXBPset-AG3f7oz6xVX
goV0OJPmPViF-JHs_EKLR-qA9AtGSGiVDiaOM-e5sARvwjaNJ4PV-V1D3Ypm6PGpFpIDVLwK4CHBFoGiIerjXyN5zF1_p2dVpN---N-Rxw6U5_JbXzNMFyyB
6FnPpTyiQIbe-Hp_UyoFZ5qvCl1A_g_z97arNvV_9ix6oCj_5VM7_qlRXta1i_wXgBz5bY_arly-n8upiPm9bo-l__FuxFhxBBMSYMEDgevRy08kAFbHz0Au
qW5UnOSimDT78EnVm4s7up_nyT8361aX-8qEt3JwtJy0_-NRrSUVdXx16eo_Ae3vPVbD0UI8hVYc038ln-ns_f77xtS0ayKtEG2Q8q2yiH0p0DulOBBXdmU0
tfLqrAVYUKAu5JRISY4m-1O7S9Ftc3EMtRLuBb_Iwx8_ndB1JwTya_F7SDzNmQV2nyKVXFi6TCOtEG1ThFwQzfJ-Nnn6l0TqElzi3c2lqCsVSFTPsPlnQwVH
r7oZ0_2F_azbpktxlyutE___c7yEL_xwu6Dr_Eq-G7WyV-7H_X8At9w_6j_o0uZD-dFdbo6vhJ_Ub5-PWvlrzziU0cP4Ixob6_cJtz-O1J3_MVvCdwrmQFi2
R6Zhnt__rXp0wUt_0G00
}

sprite $hpa [128x125/16z] {
xTlPSgGW50PWEAodCrM-_ziEk3N8BYYv23UJINNuVX0Hr5wMsmK_k9TbGa6lpDNVJe3HCbT_Am5corpzwGHOLURgJoN0fZ9N7nm1RvQvEk8FpjH7z04EA7Fr
-mbmO9chjoV01yfSlJu1FbZcwkK4-4APgzlocSidkW1nRe0_VwgFE3V0dnyfWdSNqU5h8BIp4D1L_lTcXkVJxXBtiQhx__otV7pRns4-cUSpePHWStmm-5Qr
aXmw_N-DFd3fLQiLPut-luh9F-f_6-v_rXm9QF2ntITXmo-VNuy4USXFDBpG3OFyVCDZtT3WOyc7Ulo8m4e-DlYs-Qf5_tR0FNzhx-aJKddupm50YEThsUGB
yFsZnj8es4-0DQtlWqZx8Kzz7_GsmMIxmMcuZVdzsxscT82G9rS_h3ze-2NVrITXW8GltDJ-67BxzziDIaQ21UsdGO2uBsZQtxl1OaPZjfkt2-3nt_3SSMiI
5RwWUVzo920rAcB-9S31ou3F-y4f7ZihehuNG67OV77KoOKfF3k7c6u0YoTE1uZLvFT0u8ksQpXoGZYshHr4nXVqUTyDKCcFzQy1olnWtmdW-eA-vNy3EBwW
x_bd0CD_olnutmcmN-_fkpwLlg_WNH-Kx-S33FSF_kjd0upsJnwTsISJOB0FyQLiEi1O7r8hwMI0fCzk-91UoAS2v7pMw4Dk7v48CD27_3Rc201IcIAXtx_K
LDf5xG6Awwzwtwq9ofkuBS0pFjJi8TS0b_tN7Py6FjHjOMs0Yyzrgwz5u4Fj3bh1PVzb_bRe5b_Bo_xRxB-WVWEluEgRtKrivvlm9RkUknf0Djo-a4o7vp1J
TRvYuToXMGjlFX-TGxWg-uf7vow5DqemXrs7GU1h0RLpPt01hff3_GICUdweb_pyWw_e7EuUINEaMNpOrVdB3TyTYAwlMDkrAx81gxw67mFnwr-7NPLVUlIO
MSDim-3mOmU-x3VSVqmasFoCNdV_yNDh3MzcHEjhoMxj7V3c_Nyt0JWt6blzN_NyQ_hpn-LTV_br_lAcN_a2q5D-xVjN3_drBu390QMUV-aTb9xtxnHN3_Bb
09AA9_bYW6w_ymNCNd_fzxNWs_C69RNaV5-FsX-vqFt-Kl3DDHUs3I6dt3v_MVTLPhy55LkyxXTmfLtxQRD3LVRc4vLQIpl3c8dAT8asYVhvR02vpMV23WDE
rh70gJJRg_L7HTa0FXT0RYrSXo6dolaLsaTnMNyPuWl7rsUZxVDFUx4OuyVVHiluPY4AZ4kPyuUy0E_xP_-RZjU5up_c_N_VFySVt-xdPux_e2yWU3u1S_wj
JHU4QMrlkZ0zYA_nwJhfsDteUlm1EC0mF_56f53dF-RuotqgHZifczyfeKVnvMlnFlw6N7Nk1AZs7_e2KAt_r1UGfD0F-ml-zAxsUDytm1vTxVx-xxzr1oXM
_ny0
}

sprite $psp [128x125/16z] {
xPjjZwGW382LbnRsDl7__zi3P1Hd412gtRrSFqmcRcQVjfG2fIvBjzWl6sLX47iGNlhJ6jYiyDAVqi0MXPT-jmQsINZfTsbWBmaltSiN9vpI2RPR_bXEEeKF
zYMEGmDB9BpqFWqiiV3IhsbWRn9UUfi6zcRXfPSri4y9CzwEuWs08LUWzRS8Iiopa1hDuto3MixpDAyYLQyRklWc67uKeG1f-7N3nMRuKNf6uX8_P_YW6vhv
g-4DSYqWs_XrmnEP9ky6GyT7TJRYUGS8wKLX5p-pqsjsVOn1RxenndGve1Xw5Iy8ZSCpCCTESqw9RWWoG0OlvJQfy3mG9L9am9pvtktxf78Z8Jz6OfetuvsA
Flfqtmp8yhVSOau2KaXuAIVJN4JAZxd57jmmfNfP4DV7v0h_cEMz6z9aPzHdJC8r_dUTVnY9Ovpcmb9VKi0syOyZ4UVdZf-sZoO5klZhI3YoqJ7sLAAQrcft
1jp5dsRd0fnbi1_Uin2-51Bc9lwyyY7rlaWY7jf6e9RyA_o3-KTRuQe3UlYhTMfwFKX5DqN063yWpPfurFjFm-D9tSWtgVi_qfrk6O3Asb_cvpW6NqaHJ_JA
Ap30dn8_-rKWPluuBhVpLS97d_kcTLf4FZp9rydVMFXJ9zykFFnlMzxwtcu_BHzr4CF5_qo0RNpBnxU_d6yYtxmBhlpgoQYF7pSRi1q6n8TiErQiyUrrlewx
xfR3UMKdtiDVKxnkhGj0Br-KHX-RooBIzF7tdUoG-ULLk5ntmypH9iussLwPAGr0hUe8ykJVoNRxwqUnKkrF2rR-fmPFyzy3yNd-CH0v-6aWyl3tC63YRngm
yKCWJfpy48YiV1U8oCkFyf__R_0NNdxtjJCDV_a1_8MFFt3nJy4VwJmWu0-rFeppbn_4Nvxd3pQVZF97kry6pp-VzzyNBr47pt_3xJzZvr-2_gEHypz5_zL0
_OEe0Goag4gk_aFNW6QgOkqLFdF_tICA_EZ-nziL66u0HMrGlPfy_BTm7uuQzwTZ_AMMTjoia-kYedtbDSnmI9uEuYiAw51LHk6okX72VO0l2C8yg_0Knl5b
1VGarujFvPQ0K0g4rNuJduxZYmheUEy-Ir-WbR4X0s9DMfIkN1TAlYU5jfVG3G5RDm09VsdZn-wmCFvrFaq3VEB_q81YGj0r-9-e_p_6dtP047hxMeq_gXSG
mlnpayuPYcxgXwiUNEUV0N5QQr_e-E5w9smh8EGVxtf8dXBnJzvzSTv6fUB55cgrvbyt_kxxUHiYtGieEflYe5Bae7i3feTF-GAGpfAWMcIWucDsaSNIqljh
txyYsGtzwlVVXXMe_lk_
}

sprite $vol [128x125/16z] {
xPlhSgCm38LZsRAbjZEy_zkkRqb9ciK62rHsEJ_IIQRm7GHOiZ3Jj5dymLMJWlX9klIZ7V1RwTAFSi2BqgNlxO2xf4lVom6laYuzwKCJBXa4tgnFrgHBnE0x
nMauO27fqhSvO67fqjSvu9saI-zpm3jBbxxiW8-ICfwLyUyDN7nLFhEkWOl_N_CbAhqH0ymNNv7Fh6lWuglolrZN05_yy_29A8JWan0n_utVuw-R-RtWuD5P
031HjxdI3m3MElI1rXleGQE55-XxHHyEkqpqyXEx2pqtOTiU-lY4i8xzy62H-lXBTBSDNWJB3jhy0BSnMHhYszketAdvP0-8Fq-BL_zkrzyNDoz_JqpURht_
yjRj6s3Xw07YFZXu2sl77vSsZD6pO_oufpoGnQ7VTGt0CGzOvyicBhfkyvT6dvnfwi6an9SJaFsHW9xIJ_xNQBTiQvj3O9kVzpvBRIK1rnISa-yi_MQFZ-sa
-AOSetN9HeBHQqaGBPNWc2T9yMSkSZXIk1-2MXEaas9MydaDVsxbjVvuBzlAmLlvdRhulvlFkdo--1V_ul-z_1p4tuRuZCF7xyUQ17xi3C0Wlam_DzEHU5pa
tHOBzw9HGhNxy5t_B5nmfKx380P_QRuyrJ-plxKkMzU2MUyYsl28pjMg3seb6EjIzFVYUrKNQimDqTYnAlN-EkllOtgGodWz0whjtoqDs7-s_wt-_4Vz-QFw
yszIvgklFz5UVtIS0UK5ODElvGyPG1p6ZnWW01h63nZevE-s0BEFBx40j9vemZIv2h4IpjCSANxRW3MXp4qnJr3Zb21Dyxhu8WjmlN5t6zv0Y1Eq_Dd1brb_
N4Z1MAP7A5mFNse1j4kpUemVPChphUoboHTRW1tkXnlAcSXV9Fcj1-8MAAD3RU-GwU0BBe2FiNVfp2TkR_mbr_yJMCXdtfR-ZektOeCl-mA2CmRBhGYU25CO
bld2Bq3u6dX6oEDFO77-uef8ylV6La1N6ptUY-8bgv5JldyZPc0wBL_v_IkH29pw_RTX0ytT_m40
}

sprite $rs [128x125/16z] {
xPlhSkCW38Mv2jJj3E__jclYMvtrWh25bJG-_yAq-GxW211oIeU5NpWf2GWtagLVxG1t9Kk_oW4M9KllxG19agNtSe1DagLdVKd2EGS13-iFIj8vnc1TuYGS
89DawSSS8BDawMqEi9DawJG7s5cozB83l4h2U1J6xnku-Q9yH5a3D_-Z-HmxlJC6cluvhjffscdcvNkpo4rDOBOA4zwD7oqmyeDMUfAoiwMrBJVhYHVDsAnC
BFDRkWy_G2j_goU-_eUF9_d4yRVv0pzVsQS7BHQUls3u-QxbrrBdVxVn5GCV3__wWtCE1FcjakShfK_pWvyq3ttqMyq4c1l2_8VEMblajmIT9UJ0VqAELKyj
zIM8m7VBjrRvYrFto_XkC_-XEF-sWOz4Vc0EaZUVphTAQMZYhuj4082pV1Y2VcnP98QO0yNuk_0n4VQPLD7ZFtvZfVlZxgLDdix76ZziDfKagPs7z0J_W9hv
ACV7cz-B7s7PW9Jvs8V_8_uM-7ZpFvoFFVdZUbJYOqT-FgG_rcnODutNydVo7X_5DyOAykVdJuv_yk1yyz-N7uSpHv3WEtymsZ7nzxEjr_ArB5yry5EF-VTa
_XNxxqe6G9gVvFYL_4DlVYq1rfbVJS3svQSNugVh-OGBkENsx5p-XNJ_kci0MF9F97oAF0auFCeNhp-HhZ-wpe1m0LXwMRvm_Tqb1bww_h6x0RO2qE03M1Sn
UciTH3u-qG3eVCy8mUHA34szck4hm1tEbov0T7heUxJ4god6-kEX_xdFzh7U1jg6dxC06lJZTEsryO5pyEdynqe_JC1mt7I1bv_8_3psrcZA_FCMmC_zVoHO
_N8fpuIl6nZvSIoiYFKJF_SB25F_dSv9FgSzDvx8pzKEm_GxzkxN3CGfknJ1ktg-H_W5bBTy_uRDG7fRll3xLomZyDRllvqsKFtwlm00
}

sprite $limits [128x125/16z] {
xPkDSgiW48NbRzbDEyFxlsqHxgsc0g88swIUpbY3YTz1b4LMdJijUj0_EGRHatZfenrGKhpqKGweA5vwRmTK9LvwBmTqIBpqYotGIV7IYJw8atx5CQ0Bn4i_
xu0k52_zk0Fg85vwlGFgA5xwlWCQ85xwh0SlFdC8Y7WDt7nMFX6lWPl_f_dBP0QFWSqNm2p2XlAJV13VciHgVoYdfTokVg2cvHVGpjUhtJtpL-LFVD72tsnN
MVwKuQVg3zeOMsCWoLUfzZGwq_wfylaecjDyQ3xBNuN_EPx_MUxyklDfZp-nyerKoZBo2H5f5BzRb2dnwUPtvuFMnkxoYKablgqMTk6lmtbPjWz_OkQFgpy1
3zzIuVGVKVy2_scO-TvyukFJk_Cj020ZNuj2_8lyHrV-LEPJBlZT_3_2pvIZ6iFFwkQ_1tzYvOCwUnSxPFnpys_-pUyOVyxpvI2-u-M_-VWVeJm_qll-JvUJ
8ONPpn7Zly84s07-alU0JJvCYghvlqSBVozFLS5tFVbGCV_j6kQ_odd2ILRblrnYvlImVkJ9ObaT_iw_ipz_mltyqJW3p0-0kL_BBna0VtMZINQciHJRyIK3
oWSw519JiMek1Otj-8A1m3UGgtyqqOpF6r3bWLObtpNnG_sjGUixT__9nuWGyW7y5Xze_KOqfOnRrIEmnVPNI22q5FuFj5yA7Qjk_QhKvFz9MHVoZnfOyON6
kRxApbWR3xsLqeyqjG2CXUVnsOJCDzyl_6g0U63aBulGGYtuN49iEVxB-MQU-DwECja1jxkARxBySDieCoVWgLVhZl49hVOMacEknWVWw-gFmK9eeHPyQa1Q
mKUbGjP5g5Ryri0kVxxqb328gBSTWElDds_r58R-HufjA6fwlJF6txchXT35slYP_b_gOHKXXA5vs0rNuAySZRpa-pUN6N0lotVqqGhNRM-0iTQU__stPWEx
k_y2
}

sprite $sched [128x125/16z] {
rLlRakGW23MYWhDRrV__j-ijTwD8qfDQNoRTwSf1E1mmEf-FUFWVNyRdXU5turtqtxR0LyUxwBzbWM-ETz6_RO5dZNVHlsM17nhleZziWXUETz6z_-FVH7_2
1_w1yIwwt0B_u7WNVTm2_uNnBZhV0l_5yIvwtmB_2-DTz3X-teM_S87txneWU0nP3OxUmaUZfp0a5Zo0ZsQQXxPq7r-CBhBW7Zx2T1pQuc_XkpDwii3WB-3J
1NeQV0k4-4tq4GiQBpDke0zOC3vz5deMX2_Wiz6PaZI6FuJEic08VXITOm4V7vleIiW3BZwPvZHropZx0BxhPHjgbGNuPAZInCJ_U_qxerhmSntMXcgcDhJW
BzFzUkexc31Fr1xlEsO06kHhapp3K_7p4L-Ps_YspJvAxjUvzX7Kxj_3RuO_Fhy4NRkghv25Bms_WXLJOorLU0IGXZyy7jIQ2sTy9W64sHzyll6FfegpWExX
jy8VEOSrBemIiE4ZQ7FVq_wpqn82oEYNfxR4FuVQIKh00FtKCRVS_YEUC-GElZrLkur3J98zcsnIPQ9MGe0-_TJoCDeWQ0rXtPEQarBhA_7gAv1tlV3FqxO7
2AMYx11Yp0G3OFH83u2U6Vw04NkWlCYZVNpd0BjmMSjLXW9rrISpgzJOFNvmJBuB1dGZJMJu9Vox4DAgk1F4xYSvsBhBFh57WBxwcDA3MnjxMjHB5YR-Huab
GvUrkgT03FM9KyZIbigiCOLekUXh09r0gfrgbm0CzR4B5TIqJJIR6sJ8sNSXbhqIn2X-spfN-9Ie0PnQtI7WJvT-2dQLpMtmYLCisWJeqo-mV5E7LN9wRlfj
wNwNzZTAW1uhGJtwwRIEs-EZjP0AG5gPwYYGIPiSWCNZWgbJWdhqEzMLG8R8DtIbvLMPbu1NSMWJe5Fyb3qyCxOvK8FIUDKqjHJ8z-W7XwLDcBerYnRMvdbQ
1bZPI-APViR4uDf5Vu8KORKxjVMN1Kq5ulLUqGbeio5fWZdQe4w1hYtNjUGLzLvEp46OL0pgAU6nNWDa-BimbaUKXQxBJiMAqjGQTfd_Ow4xuDkyq4ytW8qF
9CFVqaklzLMduXVdJvLIZwSNGbeAlokexX3kc0B7HDDKep-AuNS0eS7QXfGgtVRSfsXkzHcXW9hEKhTFW4K0xNtkjTU_iDgdAZEr3t2l-VvbfTJgeAICAJzt
Q_BRMtNLfYuilPmnBc_1hPiVBkQdXKUuLvMXpT9hMVCHEfTb2KSw7v4CjNlxe_PmkFUHSh0omGC-XtkidG_RdZ_PKXVTiEunTrwkNe6d6UPgG2Svu72Fk_LJ
Nzdbni9Kb-QifeUzzuJNQzjow_1gWiSz_kRN1GUrMSgDtjK79lVA-Bd3mMg1e97fipO_pSZc4ux1t-3WyBwFQ0EkfuC2tHlVW7NSdJyIm7_y4noKS6-00YmE
EXayZuFg6zmRuM1l63ayomEzSGV-buvWFN7-pZKF_3Y38dY-0J1HKwkT39vjW1Z_eGEOKdp90T3quYC7bEPBcD2jtuRBEU8Olxs3Vp8WBYfqbZLSBc62U9aN
FUao2u-DIuFmoOdXZmQGrXXMEwd1qfCDb-4B3qex2WqN9FYG30WHC_mi_DXSYR3a_37bUXOJpkNAQiEieJISUlasNKD-9NynVz41wF0mSBYZ5Va2b6XeebE8
WWCmsN39F-41xDpVsnKq0s_mbwwBoihStiJVdqOBzDQfhE_mQSKtDWzguaiFmAUL3SQ05xTIIBiTVeaA-Td_DNpf-V-omUK2_io_SBd1TtdI110zL1BItOHV
3OXaJknoQ_xH5Z-W6Of9bzv8hlc7njw0_nprnoxwezqk_Z7rum-05lqfMW1ty5SERlLt5bsNJxVbFqb_ot6ty6EB6BE5hBi3_sGtyb_-_yrZ1dp-M_oF_tFx
zU6z_m1xTVRl___RRGEwZ_y7
}

sprite $c_c_m [128x125/16z] {
rLlPakCW32G88SXiLVx_RvShFZ48SCACdcQIb5j8JKiSVhswpJvjijS4ipkRY_vj3spMvg9_omDRjBded_R0icmk-gSyi4qs5_rc5sodpKMtziVEHByZ1lO6
culUxu6zqUQYjtjWFs1pqVaUs0_QNFIw1_OBDXVTstCk_4K8h9thGCTZ34hGPXO-AVbmrkF13VYa7c-JQCRnkz6xF1Z39tWSJI9z2r-VqOC7Yhw0RoxGW_4z
wCGlehTuKDZC641lyA1z-2pqA0WVm6UZCoMf3Ry9dUL14tmhEiS3FZuLqKKd3xZuHXM7AKlEuGtukZRRI8eem2T7XJHC_7_NlrEY1F-kmrAPdAi5BVZ73Bzy
r0DiA0uKZzzhPW8Av2kJFCAR5ESZlb33-5XcdmdXbx7s6SXzFuPVJBz_VagwrDbO4Gk_D_q2Lan9kQd28q1l-jtZGQnpuOpF943dx7SntyH7caomm8pXbzBl
EKSvBhGIi10ZA7FVclt_MlOGe8z-SMXB_cEgTKy9QA2VECujlV-NpZDa11zFrMuJ41La3uDF8WqKUmXGfvzO7cOs25A2M_U4vYJL-ao-wWfaTItzxs7Z0K88
Bpk6oCy41Q1aImz0bfb-X-5xeBZ8C_lylXEitP-vkSfGeAhwH6Qb6hl7Tu69tu82MPWcVVWf_RiKcbLn7-2xdn1Wr9TzOeq0TVLHgGT7z3qjoMKM1lvxYJNA
NDRgcW8nrCSF8KfRABDA9QB5eYy1P039TgfL0Z3K1nSgYCTsec5ia27ElWknh9KWHl7Rrhd4fq0DuDJg2W6VLVe9s5KslS4td69H9a2TVexbcpeiGj1Zqu-f
-rtQNoy1igq4rUWdmpfkZq-840f0M9bABv11cpG0qd71L2b1DVgTweeZW-SRwTJoYiXBeAiyb0bGANu23y_qRGxae2HTDKqb1R8r-i5XQUE6ZchHmjmuJyi0
xDiaVjDFAPzSNFJ7IH5bkrFCRnOK5OZNU_aW44P7mW1Zja6S4frRhikUBUgzdAY3C0cVrDE4ftmDwCFVfJ4z8YrqTGmgPPGcrx3tnTyNkWC-neL--0BO-63w
yBVqacjzbQ7u-V6RJAcdquQGx8NV5LHzIBUV0iU99asE_jGDlmDm3TOsfIRJRR_x5CcjFYqK48-prEqdm2A0ECwzyleNLlz4PgHu0_UA-oyhfTO01MKCytEt
9Xy-giisTMxffPNIyGXkFVpGVduYtCAzh0njbbxBci-Grb6MgANpwPAXScz_r1uEzrwz7CmCy83FuHxhv0FBupUOwg9krZtcoSlL5dWOOQm6vYG77EvnZtxo
AxlOMAZiqfpLzB3FdkXwRPk-EcnDyBZ7F_owuA1KIxcHk_h0v5wovmW7imN2j0oVTVYfMWwVg0r-W8FDvpvT1t0r7UpGlVO3MCqz-JCTy2zx1mTxkDT00HO7
THyyZuFY4znhuM3DL3yyAm8r6u7_qXMiNtl_xYiE_EhxZnzteFi2gE_tzrThrlsG-0CarmZwDO7UVTwA_xggVhxbnvqOkq_MNJTw0FYzHqJ_muiQq7q15_oI
nrL0lHOZISPrNB3PhW4oEcnO4kHLkFl-CSK1QOchGs7r1Sj0ANOT46AaipBSVm4QtrkzIG5TgnlBdFypVf9SLF6m8DS335p0LaiyOmNGPWsyYh9FyPDRy4-t
qUx07xa0d-9lK1_YJnWJOAluG_V_t_nR7mlfy6TfTIluWoyWnFcteYtpJraM_kWB49VwOpw5V-2WrryywU_cZflHWQ8KFZA7sx2JNq3va-_VtER0wy_Yl-pF
yFRXs1jWKqS___stOGUgZ_yF
}

sprite $c_m [128x125/16z] {
rLlPSYCX3CG2WSXkbV__RvThRWO4Z4rMJqcScXPIqv9W_7vtc_snoTuJp1viBlgtFR1Pcul-BGziqUQYVze3oxAvw9_om3RPNFI7NR2TDXVTsZzs9leJCR0F
s5pqVW_iWpONlTq3-m6RYyxtm7xGvgBNFR1ViBdetdxcmj-4mDgv3dGyXX2afbduHi7BMOy73-0RzLeCaCRnkz6xF1Z3D_9rDa3pBNnzHGyUAFC5VBf13yRt
e1E_YDxYGU4mOm2zmOFsvRFGeo1y09-DpfIaDlmcT9O7JV2jw1mF-FYcY2uwUS359rLS9fISmmVmTMst6H1HW2-E2Y0c_j_x_rEY1B_KOL2KSxMW1N-PuOTN
FS1auaBn_Bbc9g10lZB98pobE9_nXHh6npBxA8GVOkqZcVjy3B-OVl_yb7JGsLWP5dvl-eNSCC7ajWgF0BtfTu-NOjiBLtmc0JftlulvBZv0cM196iClfTzp
pkIuq4h0GenacVkMZhzhw2507_tYqjRynrJhdXBGG3zntblw-Akvxf0HVBnKkrr0L90z33w9j53i8K2TVc9z6EqG0AIRUq9pacfz9bzr1RAwblvbsNY24CBB
3XdZTuAIKa5B3s0iC_qEm_T0SSYZOtwN16ltOswlCXIegZwHMQd67l5TOEAdKaaeR9C-_9J-GmffKzoNzDrF233gspwnHe2w-gZKWoFwdjR0kWi3_xt4agBR
MbrJ88Rw-2L4QGjbLgb4j5ZqGKe88DbEjKe0XlhWIWNnscyqZ0soZBllHYnh9OXH_FPrBl4fK4DoQdM5W3zL-Wbvg6nwXq-SOb4cG9r-ZkMxEYn2q6FJZwdx
NTjVBm7GLe9gz8Cmnntn3Q8C1I1Cfk05CcYJbXBDUM2gbA0Q_IvrnP71yyterFAAo4jfxl9G9a2b-0ayFTEtEJ871UQkQIefaAtHJvv66xTqLAiMvjPv6GEm
xv1uePzIFhcuwe-J8fFjJZ5_M51K85xlvODWC3eI5XYpBSKbqRbn7NgEg8zoeax297nIBnlUv6j07_uXZUaHQT3LCQWcepIvXhql_hxGdV0n3lhX0yd6bzI7
lwSNRFKLGl7pwwTCgJUN0o7eXJyKL7rAjzy2vuq6bAE_wOO_0BW6QvzIodJRIvy2tEhJGW7nkahTSGEi0eZZt2lFltBpJsHMYWzmhtZ-ib5g2r1Gnh0_3pFv
y5LTjgbpevTMIiShkEtoG_lzYV8HxcLbQ3TwhJCV6QsZB9cMpgTBXigz_LbxEDnxzt8miy0JFeTxh9iFBA-VCDL5tQnxp9kNkoFmiC9O3UWY1npkSQz-yfDT
R2nKTZHdDJtikoTpFzkcZqv74ppkyI-_RZW8QYqtSAWFJEub-ndXOBP0KCloMPUVgkNooRJ13t2m-TwdwmAkfeCTkjT-0QkvDt_K0V-sJt2mXtiD561nKFV1
ypWeFi6z5WxMJFN3io9Gin7uBxs2zMlVl_kA0x_w_SUFEp3-0YZvOv1TVTFQZmAk0VJd8sOSl_Og2FZU7_GcII3zaQFIuFzkXk7B3hWMJxlPPnDvLvP1awkD
WEJqMOt35nt0gA-uBjJX-rXWEEMaSkrxu0LecLeRIbBe0qAhNmJiDpxwyDrg5m3qQY_f8_YtRwEDu3_o0hnSHYwpnXzu-C-y_x_mR-qokFWFVG7XklzuyN_i
2n19V_Q7_P_1l-CWhSVGY_w6nYXAijQFmJzPYVxBxzyyvi3xlyL_sp_3nuTZtm2RklhvttyRTg3w-7y0
}

sprite $kubelet [128x125/16z] {
rLk9ijiW3BH11xns9l__jnN8SNnW6u7pFDLCfqd8ymgnhCIHrwlPua-SxFM0nPKzY_xR7iIYFOl-Mnx4KtiM_TiUn2fx5lrR7aIJFOj-imknqPv5Z_5FV1Bz
ZXZ46-nPz7OFuetsBBhTW_W5UnQzteFuHNiM_Tg3-0lsB7godsVX3q8GuxCED3mceFSKdi9dSADOYmStu3ECRtCO-l6RqPiywCDdFsxD8VyMFktHimV0lu0V
3j2prNlGYBz5Tq1CEWri7fniPbIZUsHbNU252vKUsBjVwliR7vTDdhw0lnlt0G8XO8e_8BCRRHxOy0ki6q0ZhwCGtBhrKXHDy2NEP_maHEgWsxPVUL2FpyKP
TuL_DGgr-07AS_qQVnpn1dmQc_475ohn_nv_3uRs_eydMl2tClpkM6t3ZCy7eaoL0t12lcErpratuJESZr4FFevdveY1yJX4jGIm3_-CuDnPCrVXsuVVo-V3
oeqU0jY6toN9NUQSztlNIW3Bx7SVNLNUVH9keBqAXpxy_V1BjiiUX9Ju90GUfZoSqY4q4V0aHljvdI8jFc22ZJY8nkOCd3xZm4q4CD4lgDvemPtnTI74PRfW
5tw1VXhGQT3V-96m_Ft1T-5ZBtuL0KpgOyIlKA185lNPujC5_Z41EBQe3o_mWyH75ORWG2ug5CXOU-Iq2pINXPdv6RzOAbqJm9fyKjgL_d-ohhmH_82kAGMT
gSzmb7O1LtqL-Q6ZF7YbG0t9pu_rTaa0S-q3rrM19GMPIrywhygC1FonqM_GebguvZyC088J1yu9O4f-7loaF84_wfmYV38Ys8Y_fv-6ajzEy89XYbzouY85
6UYdJw84uoZ9ZSyrs81pfd9s0fYI7yrHaOUYA67m4y7J1e2KPaKLE5EWQACVpPE28c2kkbBjAVy2va518m5Cz4j3ZJC--Z1lmxgf88fWL22R-icZU0vg04YL
rzIYUGYj132M_lpkeUQxiEolDF9u7txmPIa94c-Nat24G6kbfIF1RWg0Ev2o8FM-LFk4k1aZuf82-D26Nrpyf1E7t7Klwv3DDmPVgW5SAtoHp2a1S8eDJ_NV
1agMHQvwzhTGGESpQQ-s4i5xtQBOOLmML9GmSma_xF0XTXaTftKlDIZkXbh4qDt1lUlzbs58VD-Knk3kujuP1pzyNxSoZRTnxuA3KpuERbZoSiC7YZSOkxFA
Qj4Asz6guTwhWuEut1zsj0rM3VUgJZxmfB2Ln9_tFoY4JT9qTV0r9ozm67uHEpyjHJsipo5gk5Txz7DmufSNOKEAS_13gW0Mdc8jV8q3VBh96Tx5WdCsxjKV
Vj45FZNatC_-tq-F3agemvOXLRfdE_s3qqte1jsp7ZyQ5jreXU_de5dtx0UmTCE2l-ly6xlN-tqNC4uvQ4fwZHU0WX--mJqB1wyCsk6h8d1bFV2_T0NBSl-E
eDGZBb-o2B3ZNZ31xns08fsnJ7BQAWzxji7l7EZ3B_oryGBctVYl9dn2Za4lMEN_19_JUTUR8m3vI6x2p-TZGVVdONCnp7h_DUEJRctemxNCzkdSLqjUoFdN
XpU-b8IfZJLZhjNOV04NyevNNd4lyOTKSv1pEHPf6mxInncVvTlIbjU2yjTs-9K3yWI5t-1xfG5AmQizz59pP7olOvxQjkFVS05Q-ZLLC-luaxxsWkcpxe7W
9Npn9sq6IW3y5h_b0dPUqE4UNxaeGPvpyg3ul5YSDkD_RgF1u7MO3_0J5L6D9tmtlQTD_vikmASdO2RtX4-x-CEij5FymwoyI_os-__f2JAFC8FbHmwPVp3p
RvfXuDRy8xVcN-CF443Ns6askpJdq2tcNuQ6jEmI6iXhqadeACtDKUScDy8lyNK4A5ysWQN-y4T_qciT2zJr04rRkDo8hnnarAiDIKT4Lv43SVwKOPRMTEz1
hqIe8cVzLLX6_TB3Fq3vBtz_Svi3h_yM_nN_T6yVzlq2xD7UF__xjsu7BX__3m00
}

sprite $api [128x125/16z] {
pLlPakCW3CG28PYPglp_tovN71yOnE5uzRHJsN8BgMb9OBzUtMP_RBBN0sPtzYpwjpsmMNiM_LiUsA8zYtwt1vPbpwBVvO5jicVH9xjWE-rPT6j_xPFeCs9W
9zYpwFqUs8dsB7gx1_O6UnQTxu6zqPv5htjWls3FedlxUHR-8WJMFkj0nsCCWjJcANnIi3ZhyM02FgdbRO1c7ByRlSk3CNoIoz40wLlu-emUF53q1NnpWHwC
xq4dVX6znOF2OSO0UeC7xSjdeKT1k06VZSwKf3Ry9dIM1qtmhUWS3_ZuL4GNdJpWuXjLN2QKdCC9-BgssmX45E2Jem8C4__l-lyfKO9_rs5G9kTgGGl-cE67
fHvWGt6XUFnTCnDG85-Pv17Uf3WVyOKQniSo-qm8FyJQPsJkzp7yOlhzyrFIGMTZHIpytlGB-S44ocqL7W5wq-yUByLdBvpncGJetFqkvfluWCa4Iven_5Bw
FUSenuLM0XPY9ClSjsR_juOU0lJHBovjpNzCjUuf0Gtq4yUzfVT_qdc7ZE3ZgTfj0gA2x67mIQI5OWy1wlGJwyFC1W50khadD2UfrcVoLLSWgslfVoyR3n12
UDanH7udA2aLjFG0P9dfTnY-1uf3djddzvrWxVwPswiC1QggJsHMgh5xV1UO-AjK4WhRf0y_fN-NGlDHt4NwxYS46FLbdrWZG5rzLEh14NrFIx3kmi1_Bx56
cSjQNLCWXlhu9KHf2sLMgKIqMFH1IWWWsKwrIW26-k1A1R5iDnh61bd6tNSXbhKIn2X-spgN-1Ie8JcrkaB0dohzXDnLDht1DvnYKIP0dNwEvPiwB4BGOzEF
gVjTsryl0T1MWchqWp37xV49KOO242PJy08Pj4bBYNGSc2ebg4Q_KrrnPF1y8vrQNX5vAUag3sK2L8gVmCCpVPiZSr10LqrJIO5iZNxoCDgufQDQjJ2tpjCO
W7s7n6_wAUMJYwl-E2cYR7UA-SE2eWBnUYyV1CBeI5XWpBOKfqJdndNeEQBUouaw29FmIJrjUChNW3xyNHhJ8zAWgsDGAQCqkOQzB_w-q1tmCGxwuGV9nfUc
3tzBB_ZKLmZ5pw_VP4ezdGw4e1T-Lr3r8Tr-2nmt6fWS_QaRVWVW6gnjIascstxtAS2jFYqK4CjPwlORO1L07ETUUVwL7_z4PgKuWNl5yvSFfJu12ieOzkTk
9X--giisTMxqqahfU0NtkVpGVd-YdCAzh0njHgzrvZEaTPGbQkbykcIetDiVjOV3lLSl1pCBFE1pkCUw-S3o-WsckgYRTOzvyt9r11vM6Ak1ESa1XtlSgv_y
P1SR2vKTpLbD3_lkYQvds_JJuMY2npt-vTS51q6jvGPszO79lMG_8npC5WZJidpMvQTgkNoYDlW13ZRV-tHTmDLqi4FtsYzWDVVcptJ0l-mC3lPmhu42B0xg
FdWU1yKTt6lXOCrKFpmh0ZKRWV_IArWtlNz7dMzUp780XHw67t60aCRXx-R0b1T0VU-lmceDakl-mY3WrczcuDST8EdQVqWtlXByvOWVHv6XV5DUm9KBXcOh
da2uQkDACxBmfxn_R9IApQuhD1Ih3NalwlWJNu1syzyIy5KA2TNnfxs0hUDTJy37r9nDnI-_ZQRyOGXgQCIVzG8ynOEEb7-LUiDg_gUz_u_lc-OT_shyd_S1
WWCc4mwPFBu_Yd22e2lu4p-0S5sOanm_xf1VlvUYm8B9-DSSzFBhrDVN6vT_mYZ5HVszwmCKufsltVRz3ItgFdXEAUBWt_W1ab7wJloN_Hq-FXpx0kmR7Sz_
_FtRi0FLn_y3
}

sprite $k_proxy [128x125/16z] {
pLk9igGW35GW1s-tQlx_RvS0Aju4VEEcQlULWsN7q7J2uUVJRFx7P_kyO7vbxw9_smD_QE-YVyi3Vsdlel-s1xxAtaN_BG-yojv5VzW5tsZledl_nx-9_aGC
_0FsBdgx1_v1UnTTxu7_1NiNlTu3_ulsBlgz1_uBzYwwsC-xy2SXyFvT1neUms0jybluvCmOhCM31_39ZPCPu7xyPlGc3_hmoOvRCq3VmiSzUlJ0qHVm-GGz
Mhq7ZVXRTEEGC0q3dGSNYndLw1OeiOwfSA7I0_th7xtxX0zbayLVmD_r--0OmO74tm6H6NKUwF0FM3Uu5FdK2spMhRUYg88_udp45o5A3ffj-vq7zVXqEEBk
yEzweHQVtV5OlySVHtW07yTc_C5m9VxVy_lSqFx-uuKM_AqClpbNMvxnwKIKiR83BiXthlOnwme-kUi-wi67ySeCaYCu3r4j0VJTFoCOSzLCLVZwxhVXzs7b
HWy1TDrlH7BBd3DTcrO2Q4Q_MNGryMv9k8nx5UO-_7ttXsmNFM19V244rkKyBEdGDH7m8aRxSIsH3Zw0m7eOWiR632o_4LCJ0LJquwGtgU2E-6aYHCTqWIxy
0_gbWEPEd_0zml7zW-t2XrxyAWAer4U9Nw507ZNgiyN76_np0f1lKHygy3d49oaCkXEvg50WPUqHqwx3kIoCp8_uXwNIFG6qoKVIRdZ_9Uk6Yu3FO9fIq9Nw
36Tfry7gNOFyu5aUl5EWXkHdntgx9O2wzd7tLO4c1QbBNxokofG4_D7HRqX5TU2QNHZWq5quS4q0LVAppcRbOLhKMI9yqIFGYB-dNmebJKvGmR24V-J4JGfI
q2yz2GN6eCYDZJNO07EcCde2g98Vpb493uMWX6mpmMK189HcXofmfK1UHp-S1mLw1x7gajep_6E8dG9A0gZe9rqDCpvOdfTXJIw8l5Cga4xzmgDe3Yex9vLN
Rabv2BG4K9R-DBrXodTSlczefF4vVBR7Ki8XtYOcOUyOrqgBPuBT501p8cKSwlrGxIF0fe-GZXJ0SXl-uUH7TXpYgzim3zdSCTYZ6i2qmX-IMH80IMmertyR
g30jCjMZluK2QJnZUgkjHD1Ujz1t61qBAeGmqn4-x_2Txp8yJ-isrA2mw-eWXkO9xjsllmo3y7rJ6Zlp5FUkEBZmVTrAE3x6lHiEvdpCPYXvkU43-WUCp5Lb
LRIwRM_LSE_JmK4eruSDReDLmxsgdG-uA6n3ue_h7yYyIPgc3hvcvyMTXZ-8dSrJKUlM-n0rtAlT-ZdPyOkJi47Yp7QG2g3m56hXQnoWoqLEdee5OtJSgz_y
mXjyRCYvo_hVJuyEXb3pbY5LkgVR_NENYz0DkgVTVbHCka4Btyz1jUxfDs3nWGb_r_utTC_t-mvWN79GbVGQ3m2n7Nw3UneEtfbhXw-Am9trm7_f29RY_1q3
VXD-vm3rrkzA-Aq3p-Fh3c0-ZlzfmMTOzlmGMSgzMFe1aPD57_abBlumv8PmKrgFOKGb_cU77p8V58j2Lj9jd0F7NLWdc--IW6KrpCKxvN-NT13N0TGUm1Ny
5RotWmcbBaYI8JdYWIJjeGYETx7CIr4QCx1RbGBgyyS1VmtlyvMy7gKw8oC5QOnrc4KZmU5uoQPCXle3q2Hh_MvHFi6dAQwKKbsETFxhfWm4iJmlVV-qu4_v
7AEwaxTv3JZYsnIHl1UMLgTCNk-DhROCVyEdTG4V4wTgyIajqiNVET-XXfyZ80_WjDQnZJzC-AluXvjTBe1W12YAWQRp_t7yOLbHPVxPo3zR3B54k12iF0Y5
UtQfXTe-G4ZwuyhnNuu_cmlZUVn5LsbQ72egqKyFVdWWBkzlH6qi-mc_q9-Cd0E6nJoWyVDEnhJHiHnk3VqVr3QTW9YqDIeonVkctU3OllJRSn-WsFerdMNm
F_ZzJJL-OCJ4lYS_0Ah5bzaITC8VuMFbIMlPdFAz-1__ftlviEyBi6zKFF_nzs_T3jm-_Xy0
}

sprite $master [128x125/16z] {
rLjRakCW3CI099ZPgjp_jek0-8b1O2UkuMChiMVTGcfQ4ZYlr_3mFpwFrmF3RyQpwD-sm1V7i-ZVii1NnxFedxR0YyQpw9-om7UDPz5lDi4FZcVHlV_rJwBV
uGD_mtWMVTm2V-Du5htV0l-1yIowt0B_mV4iUji2_uNnB3gFdsVXJrpW_RC633p6WJRedi8dgwSmHYou0P_iz1uQt7NyOVGX2wxXavdsGmDz2n-FwD42Ir_0
ToVeSSWj6CIlelTOKDdCk83UOK7_z4NeIH0-W2z65qfI7tuNkiY2BlXUT8a5Sdogegj17aZndQrEKzUCWnlmiRNQIAiam0T3bNP2_7_dVsTL3VwTXxLr9LCh
Ml1Fw7uzjHtiA4qKzlTH680A-UeaJ_0k-tcFh-nbVAYppqNtwvJxd2dTluPV3Jy_FmTTOz5N9C8V3Ryo2wQcqbAH4M0q_E7nHYrhuOWl9C3WwWy-N_b7kuAp
ZBk6Nmi_SuvANEWbOCL7fivzxxRVKOyGO8n-QMfp_5EeSIG5TD1FxTSMRh_ISOLSmOT3jbivn4RPWsYJoXE54GAqwQVcXxaLWjOcz3snECcvlX2ljW9vR8N_
FMtOGIZ5ikE8U2LOOwpkgG782yCVCBW6IasUsyRt7M0C7qjhLQ10JVL9pCevTeiV79Fk6cjqPPcCuUVmRqBe5iMT35S_qS60ftLYYm1jzR6v1WVWcfRql0eZ
_rbYdNMdkRgbG0BruIaaQOjfrjfCj9JqjJ4wWXGhrIO11Ee3CnNKj5vea0faarRVYLYsKf0W-QtpNEPJf8QHvEe60N-Qz5DcazbmXUyaoQ9EW3Rz0ijNULX5
fwUY7tBrEvU_B06wBmMrwATZ7xV59m0J4q3iJ3KBPDGcD0Petp0rKb2BVeUy4iZ0V2FC9QzAl3Hq5eSw0Hh9Jy7kcLpcc1AKfhEYgQP0laK_isjjmjJ1pbfO
ckUX3O2nJU8t_QpbuCAiFq6Ag5YTGdcpeAf0ijgBdK2G38aJJD4swX3eKhkkHxQejt9YTyAaEAY71K_b7326lmbZVaHkT34vbGfAKohOn_pFYMw73wdHZpUC
6D-uCVmrlVIINtLCVZn_LqZrTDWGqgFmcuIAkt3p4jWlDErAzATX-0r0AB3M8NM5QljTfsXfzkcXW9gEKhTT0BC0mdNkrVjVizYd2ZE56xXNtNzPABKuA2fZ
N9-RdlpoKLsng0kj5rgBwGXkEVn0NfzWRk5UKOPMhTVSypb2JB94FPNFa0pLQ_kzzaYuznhbO662Etm9zqGd7r2VluES5x5RzuGdBsTRu766AHkuWnn8k2Sz
-YbtTgcmiCNMN5JqYC-UwBotpRTsMnCoxiaFlquugEsSRlGcFmYvbyVF5GuM4uJhcRxeyDFs73vH7_m53dQV-mmTmBLqS43t-WzWKNhovmRWN_uE3evmhuC2
8WxY6BoCW-eJtElXO6lOSNYH1rhZ2loNNi7wqFjtxZhy5GFGkklmumOuBQkrF_K2fX2__mLGH2xrGu77-nyfh_4dcrwlY9iYt8e6RUGzyDKkIVYFOB4R_xMN
76ruIz5WMDofnODK_jkK4lWgnkJ4Qvyxa7Y17MBsExI-_mNSa7Orkl1u3IxeBqDCXXnV8SO8_o1BVb2cq8GG_t5eWBaQOpEG-k6t1WHyzY74NKp7kGtJtXE4
wvJcX-1o_6rIVmWg7F07d7ym8E1JVkAAP67-9ksAPnwaM-4xiGW65yNFW_0x_BYhiS8dI4Szc0ybujvlmb-zUHBmtIZ-wcsqZB-QFyKc5vEhmzhGiUB8-1hI
mEE277i1_eXl9fYlnAudXqAxTNmE-8Fl_n_mytF3TGZkXuLkV3cHDLxVuO_-0A60FuKbngLGnC18HOfqNzRVjFV_y0yWCerM_iTu7cko5aGfWjGVyEBKxmjN
yTySH4mwI_CNbbYU9QxqDp9nUm7n4loTrSYV_FtDRGQy_Yp-o_zUtZwyzWkmHsV__E_VBXlGVFn_
}

sprite $etcd [128x125/16z] {
rPkBhjiW38OJ0xRfcPJtVziHalJaGeWnjEXOsjHDLJy3loy1Cargyo-_sjJ1_C7wqh_jWKzQN_gtFF1Pwql_j0TUP7tfd_B05rbVUcCNlDBwqht_yJtfBUR0
Dx2-TBq7lg7rfPTxu3zWVUbo3_m7hI_zsGF_1UjBd-tL5typ1RgVucOEQE1eZEDU_40VXt44Iptux61ShTo3QloE7gtKWph-cJwRmM_noLxfYmVy1VuTlSm3
BP_ic3Mf1vdDZ0fw30PPGb0CNq8NUr3CbzA57XJoSwfJUL24PpiMsvC7SdugszHx8EQZZXwZaUlv38EQFwAG_oyp_B72tFtl_XDElwl03qOeWCpNJCtuWMlv
33LygG1Ko__MvJ1e152v_62CjMusQmr0bG1oovyQcx58l5zQPi9aXfO9e6ZvmL7wHpbL9AYEJnTwji6ufcg900gMt_9-lC4m_Dal1HtZTR020MI-OeVaQ1ZT
JdC0nhuNvLGh9G8GBx_TddjW7txhv-qfX4sf03Byn5ZmFYCQkgOChE7ZTIrpzM28jCEavGImuL4cly6b0kBeG9mY8-i1o9TbdyXdyrnmZpdhKO1I-KL-jXS4
JEHCrFEFapsuNI-SICllhOWZ_oa3UMdn6znlvd7cC3K0TfULZwlsL8B4sMTmnsnFYB7-uQaOdSR_b874lS-Yl_n60oLg9cdvf-otn1_Osmeq9qQ-ylC2U8cB
tnh_GyYqU2d1ImCmZ5V-GmcI5xz3_fbB3k9S_SBVpcvoJ8q_Bm1vyJlclo7P2wRuUG5abjzanfzhkCzyLFAX3JzRWhoyzrAFt-WsYR4L7tJya_pq_15LVDEC
xrHyrtd-a_67vNmWhxDa_Y_dezSQNkDOq7-Tlc8h3ehSTN3P_ijTyuOo-BSOJCpatLxajjzc6sWlhS5DIV7nwxGRyEw_N1FjlPCm91hShV-QDn_c1en-sm5s
ZRHtauKV3dgedVPkqb1upCpqNsD3xQKr65suwx_AyzvKdWTt_HV5BOXT_oNjUtODQAa6i_rNeVQ49o-gFM29zgH7FufDO2C_1198eFW014hEe9GQp1aLuAUN
KeEgVUV23M2L1cqPlhK6JVa1P4iDWkByiwK6IO4N7G3BDEYyXjzCWrQ7RwL1mqgyJ8FmO1LuqGpmarNWltG3hD7zk_H8yV7gGQCBW6GelMN85VW21-oeuZUx
WAdZrru09MUN_Ky7evsNcj5QHqlt7JvnDNzwo3y0yqDLh0MXpeIKF9-3OQmE4F_1TVZySH0GCyuvBk32F32CZZauGS4r6puPmNc7tW6phBcTnnlN7vTixm0P
OjMb7B_s0ZJ7uNDunBGhtwwDLbY8nPFS-bTVmARzcKRactSGu5fsRGl-pMqq6i4jXWf-_GLu6irlwjtFFpjQv_y-_XlS_-Trk0xE-WjHyA2_9YyWRF6t3Dt6
D13Z3-RuCtGVVurUW5Zp3owzMA0k-MV-Zxazliy_LQztdlBlacv3fJtcNn_pBs4ZVCjkv4--VzFCWUdFyYV_KxrvLlS6MDVHzt__hTg1nv__3m00
}

sprite $node [128x125/16z] {
rPkBRgim38OXYI_PZjJtVzlZNA2KXX0dj6YMfcsbwcUIdzyceOz7T_WVd-DnG_YNk9V-xGnyCUwbVoi3NurxwP_Em3V5lVHFPU1LSI_zuXHyPznBz_xNtqc_
OWpy1N4llJy3Vs7SIzTdu3yGzzBRC_0VZ7lfvnduByIzz10_z-8FXi3xUnFe-1W6Qv7lufCpiqHF1XVmoSrB6E1nVZUzAuCnFjbv7mReMtnyfySC77s1pmVq
6EqPTFBtTEEGC5q6kWmgYndDT0kKLCUqIQ4n0_tfbyvzuSFsaCKFyD_cVNACu22ClmCYC-ioqF4BgfjS6laq2snUZvwQeWfVqdpa1oDA2PhzyRCCslbKlEBE
-6UpqCfdLxxMp_dp31VmSUxcJuOR-V-Et-Uc_lEVArxmht7upR7Ryigd0rF6nWceYE_OxMFL3NnozJaQuSDS2uFa28w7g5K0-kbV2SRK3bCJNp_zLbwVNj8O
4O1k-asmt6tDMVutlGBGNFtcwQj9Ty-2o_ZkmZp6Vvz-gNOn0mw5JuR0kbo7GpbqNGAiZD7xTHr6MdA0WFKmYSV62XnU8wOk0QZanyblKiCT-Ub6YCfoWI5-
GNvfGFEaBtoFK7x_P8VuCCfl4e3AVPJy1WVog76VFHzF-CS28D_ZFhJXiunFSXXq1tRHu43AtYEMNOThMnYL7_d5LkbS0DhY4ygkdF-pwie_mcSmNIL8vJwB
1pjuELUn7pogWsSEr57yxDmUfm9Gzpxkl2lGb21rwulrhamfm1-T_ARKL8lMx5C13bqbWRe0LFAppcRdONgwSnZXoen09_zTVcaeQKc2DWfB_58I9oL88R_q
IHWm1eFTsDY3JP2SE2Ie5u2g-E4wAlAX84x8DWiyB018QrPqWPe3UPtySBqeq3k8NLVeFUM78KuAA0MWSp-PQbZvO7bTXZMv8V9EwK0wzvEFedLGsRdGUUKZ
gGw1LW3Arf-MCqprZhVdAmTflexFjcmbBEDjOX7sZl7LQV78iBi6m1nO6Kk_Bzq-0kpc2Ada09Rx-CMRdx3Z44_Todt8xXsJBVK0fXTV57Ce01J6XlpgEbkK
t1QPvgk_HmBfUiPqLdkBe7VVGZyGL3PKa66c4f_V-CuF1HwNTIizABnDjPYXkK9xv-ilqnJqlckDdRbAUpKDFlN-UfHmlanx9nhCzPZDjDNbJW_eBmWojSvg
SzJjPwj5Uuy13S9sVTZWVh1QjDUqym6LnbOAVrp_GEPTqJHj-9QT5tSu_69sDj-AMlUw3z6YlTQjduCTltWJDeLnPZk53c2JARJYMnAWwY8dBys2CJhjjMz-
uGaVEshkS_tlPyG7PQXvhv0ctzFj_hdg8dI7xsct7nKttQ35ZsjGxNlw3LYyu8P_QFyRXk_tnnx0g6fGLVGw7m0Ib_k4zZGQF0lNZsyQWRCOmN_f4QoFF7y7
S06-Fm4shQtkPvv_REP_w07CLdx_0w0Cn67JAs7Y7bX--WN3gudFyM6K8VxZS3d4sh2-5jqTOirTMbxvqqRRfVXtnO867i2biDF0GWXtlxCXPipBCIxSyuLb
MKb5MX5v2uxW3nAWL5WmLDTCW3aiHzdqiXp5L7dbfI5yEO7ygIGCpZLEVWiJLlsvSFhn1fY7y6VyvGG353BV2j_M-w-khzOrydtYEqZ1O_ZI23IDVrwR7yON
4jZmN_LdLlr1rfyfT633Nq3OyWlNNrnxCVdwS-FuAl_5Vrpqd-X_8GsJToX7-NiDCjBcryv_WH6NlntwA_1NTYD_ylitboNm-BFyX_yTNZuS-mROhMT___VV
XXCu_VZ_
}

