sprite mdi-horse-variant <svg width="48" height="48"><g transform="scale(2)"><path d="M20 8V16L17 17L13.91 11.5C13.65 11.04 12.92 11.27 13 11.81L14 21L4 17L5.15 8.94C5.64 5.53 8.56 3 12 3H20L18.42 5.37C19.36 5.88 20 6.86 20 8Z" /></g></svg>

!define MA_HORSE_VARIANT(_color)                                 SPRITE_PUT(ma_horse_variant, _color)
!define MA_HORSE_VARIANT(_color, _scale)                         SPRITE_PUT(ma_horse_variant, _color, _scale)
!define MA_HORSE_VARIANT(_color, _scale, _alias)                 SPRITE_ENT(_alias, MA HORSE VARIANT, ma_horse_variant, _color, _scale)
!define MA_HORSE_VARIANT(_color, _scale, _alias, _shape)         SPRITE_ENT(_alias, MA HORSE VARIANT, ma_horse_variant, _color, _scale, _shape)
!define MA_HORSE_VARIANT(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA HORSE VARIANT, _label, ma_horse_variant, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA HORSE VARIANT>> White
