sprite $2_square_fill [50x50/16] {
0005BEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEB5000
00BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00
0BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0
5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5
BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB
EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFA5200149FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFC2000000001AFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB0000000000008FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFE10000587400000CFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF60001DFFFFC10004FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF1000BFFFFFF90000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFE0000FFFFFFFF0000DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFD4446FFFFFFFF0000DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFD0000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF70004FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFD0000CFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF30005FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF50002FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFF60001DFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF80000CFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFA0000AFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFB00009FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFC00007FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFD10005FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFE10004FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF20002EFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF30001EFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF50000011111111116FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000000000000005FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00000000000000005FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF7777777777777777AFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB
5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5
0BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0
00BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00
0005BEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEB5000
}

!define MA_ACCOUNT_MINUS(_color)                                 SPRITE_PUT(                                    ma_account_minus, _color)
!define MA_ACCOUNT_MINUS(_color, _scale)                         SPRITE_PUT(                                    ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale, _shape)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ACCOUNT_MINUS, _label, ma_account_minus, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ACCOUNT_MINUS>> White
