sprite $3_circle_fill [50x50/16] {
000000000000000000169BDEFFEDB951000000000000000000
00000000000000027DFFFFFFFFFFFFFFD72000000000000000
00000000000002AFFFFFFFFFFFFFFFFFFFFB30000000000000
000000000001AFFFFFFFFFFFFFFFFFFFFFFFFA100000000000
00000000005EFFFFFFFFFFFFFFFFFFFFFFFFFFE50000000000
0000000009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9000000000
00000000BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00000000
0000000CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0000000
000000BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB000000
000009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF900000
00005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF50000
0001EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1000
000AFFFFFFFFFFFFFFFFD7310125AFFFFFFFFFFFFFFFFFA000
003FFFFFFFFFFFFFFFF60000000002CFFFFFFFFFFFFFFFF200
00AFFFFFFFFFFFFFFF3000000000000BFFFFFFFFFFFFFFFA00
02FFFFFFFFFFFFFFF600002798400000EFFFFFFFFFFFFFFF10
07FFFFFFFFFFFFFFE00007FFFFFA00007FFFFFFFFFFFFFFF70
0DFFFFFFFFFFFFFFA0004FFFFFFF60003FFFFFFFFFFFFFFFD0
1FFFFFFFFFFFFFFFA555AFFFFFFFB0001FFFFFFFFFFFFFFFF1
6FFFFFFFFFFFFFFFFFFFFFFFFFFFC0002FFFFFFFFFFFFFFFF5
9FFFFFFFFFFFFFFFFFFFFFFFFFFF80006FFFFFFFFFFFFFFFF9
BFFFFFFFFFFFFFFFFFFFFFFFFFFD1000DFFFFFFFFFFFFFFFFB
DFFFFFFFFFFFFFFFFFFFFFEEED810009FFFFFFFFFFFFFFFFFD
EFFFFFFFFFFFFFFFFFFFFF00000002BFFFFFFFFFFFFFFFFFFE
FFFFFFFFFFFFFFFFFFFFFF0000004DFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF000000003DFFFFFFFFFFFFFFFFFF
EFFFFFFFFFFFFFFFFFFFFFBBBA710000CFFFFFFFFFFFFFFFFE
DFFFFFFFFFFFFFFFFFFFFFFFFFFF40002FFFFFFFFFFFFFFFFD
BFFFFFFFFFFFFFFFFFFFFFFFFFFFF1000AFFFFFFFFFFFFFFFB
9FFFFFFFFFFFFFFFFFFFFFFFFFFFF60006FFFFFFFFFFFFFFF9
6FFFFFFFFFFFFFFFFFFFFFFFFFFFF80005FFFFFFFFFFFFFFF5
1FFFFFFFFFFFFFFF5556FFFFFFFFF60006FFFFFFFFFFFFFFF1
0DFFFFFFFFFFFFFF2000CFFFFFFFE10009FFFFFFFFFFFFFFD0
07FFFFFFFFFFFFFF70001CFFFFFE30000EFFFFFFFFFFFFFF70
02FFFFFFFFFFFFFFE1000047995000008FFFFFFFFFFFFFFF10
00AFFFFFFFFFFFFFFB00000000000006FFFFFFFFFFFFFFFA00
003FFFFFFFFFFFFFFFC30000000001AFFFFFFFFFFFFFFFF200
000AFFFFFFFFFFFFFFFFB6210025AFFFFFFFFFFFFFFFFF9000
0001EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1000
00005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF50000
000009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF900000
000000BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB000000
0000000CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0000000
00000000BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00000000
0000000009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9000000000
00000000005EFFFFFFFFFFFFFFFFFFFFFFFFFFE50000000000
0000000000019FFFFFFFFFFFFFFFFFFFFFFFFA100000000000
00000000000002AFFFFFFFFFFFFFFFFFFFFB30000000000000
00000000000000017DFFFFFFFFFFFFFFD71000000000000000
000000000000000000159BDEFFEDB951000000000000000000
}

!define MA_ACCOUNT_MINUS(_color)                                 SPRITE_PUT(                                    ma_account_minus, _color)
!define MA_ACCOUNT_MINUS(_color, _scale)                         SPRITE_PUT(                                    ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale, _shape)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ACCOUNT_MINUS, _label, ma_account_minus, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ACCOUNT_MINUS>> White
