sprite $envelope_open_fill [50x50/16] {
00000000000000000000000255200000000000000000000000
0000000000000000000005CFFFFC5000000000000000000000
00000000000000000004CFFFFFFFFD50000000000000000000
000000000000000003BFFFFFFFFFFFFC300000000000000000
0000000000000002AFFFFFFFFFFFFFFFFB2000000000000000
000000000000019FFFFFFFFFFFFFFFFFFFFA20000000000000
0000000000018FFFFFFFFFFFFFFFFFFFFFFFF9100000000000
00000000007EFFFFFFFFFFFFFFFFFFFFFFFFFFF80000000000
000000006EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE700000000
0000005DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE6000000
00004CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD50000
001BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB100
03EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE30
1EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1
7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7
CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
2BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB2
004DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE500
00006FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF80000
300001AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA100003
FB100003DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD400001AF
FFF8000005EFFFFFFFFFFFFFFFFFFFFFFFFFFFFE6000006FFF
FFFFD5000019FFFFFFFFFFFFFFFFFFFFFFFFFFA100004DFFFF
FFFFFFB200003CFFFFFFFFFFFFFFFFFFFFFFC300002BFFFFFF
FFFFFFFF9000004EFFFFFFFFFFFFFFFFFFE5000008FFFFFFFF
FFFFFFFFFE5000008FFFFFFFFFFFFFFFF8000005EFFFFFFFFF
FFFFFFFFFFFC300002AFFFFB32BFFFFB200003CFFFFFFFFFFF
FFFFFFFFFFFFFA100004DD500004DD4000019FFFFFFFFFFFFF
FFFFFFFFFFFFFFE60000000000000000006EFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFD4000000330000004DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFA100002AFFB2000019FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFB3000018FFFFFF9100002BFFFFFFFFFFFFFF
FFFFFFFFFFFFD5000006EFFFFFFFFF8000004DFFFFFFFFFFFF
FFFFFFFFFFE6000005DFFFFFFFFFFFFE6000005EFFFFFFFFFF
FFFFFFFFF8000003CFFFFFFFFFFFFFFFFC4000007FFFFFFFFF
FFFFFFFA100002AFFFFFFFFFFFFFFFFFFFFB2000019FFFFFFF
FFFFFB3000018FFFFFFFFFFFFFFFFFFFFFFFF9100002BFFFFF
FFFD5000006FFFFFFFFFFFFFFFFFFFFFFFFFFFF8000004DFFF
FE6000005DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE6000005EF
8000003CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC3000008
00002AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB20000
0018FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9100
06FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF80
AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA
5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5
0BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0
00BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00
0005BEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEB5000
}

!define MA_ACCOUNT_MINUS(_color)                                 SPRITE_PUT(                                    ma_account_minus, _color)
!define MA_ACCOUNT_MINUS(_color, _scale)                         SPRITE_PUT(                                    ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale, _shape)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ACCOUNT_MINUS, _label, ma_account_minus, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ACCOUNT_MINUS>> White
