sprite $patch_exclamation_fill [50x50/16] {
00000000000000000000049DFFD94000000000000000000000
00000000000000000002CFFFFFFFFC20000000000000000000
0000000000000000004EFFFFFFFFFFE4000000000000000000
000000000000000003FFFFFFFFFFFFFF400000000000000000
00000000000034545FFFFFFFFFFFFFFFF54543000000000000
0000000003BFFFFFFFFFFFFFFFFFFFFFFFFFFFFB3000000000
00000000AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA00000000
0000000CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0000000
000000AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9000000
000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF300000
00000BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
00003FFFFFFFFFFFFFFFFFFE99EFFFFFFFFFFFFFFFFFF30000
00004FFFFFFFFFFFFFFFFFD1001DFFFFFFFFFFFFFFFFF40000
00005FFFFFFFFFFFFFFFFF500005FFFFFFFFFFFFFFFFF50000
00004FFFFFFFFFFFFFFFFF300003FFFFFFFFFFFFFFFFF40000
00005FFFFFFFFFFFFFFFFF400004FFFFFFFFFFFFFFFFF50000
0003FFFFFFFFFFFFFFFFFF600006FFFFFFFFFFFFFFFFFF4000
004FFFFFFFFFFFFFFFFFFF700007FFFFFFFFFFFFFFFFFFF400
02EFFFFFFFFFFFFFFFFFFF900009FFFFFFFFFFFFFFFFFFFE20
0BFFFFFFFFFFFFFFFFFFFFA0000AFFFFFFFFFFFFFFFFFFFFC0
4FFFFFFFFFFFFFFFFFFFFFC0000CFFFFFFFFFFFFFFFFFFFFF4
9FFFFFFFFFFFFFFFFFFFFFD0000EFFFFFFFFFFFFFFFFFFFFF9
DFFFFFFFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFD
FFFFFFFFFFFFFFFFFFFFFFF1001FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF2002FFFFFFFFFFFFFFFFFFFFFFF
DFFFFFFFFFFFFFFFFFFFFFF4004FFFFFFFFFFFFFFFFFFFFFFD
9FFFFFFFFFFFFFFFFFFFFFFA00BFFFFFFFFFFFFFFFFFFFFFF9
4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4
0BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0
02EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE20
004FFFFFFFFFFFFFFFFFFFFA55AFFFFFFFFFFFFFFFFFFFF400
0004FFFFFFFFFFFFFFFFFF800008FFFFFFFFFFFFFFFFFF4000
00005FFFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFFFFF50000
00004FFFFFFFFFFFFFFFFE000000EFFFFFFFFFFFFFFFF40000
00005FFFFFFFFFFFFFFFFF100001FFFFFFFFFFFFFFFFF50000
00004FFFFFFFFFFFFFFFFFB0000BFFFFFFFFFFFFFFFFF40000
00003FFFFFFFFFFFFFFFFFFD88DFFFFFFFFFFFFFFFFFF30000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
00000BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00000
000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF300000
000000AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9000000
0000000CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0000000
000000009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF900000000
0000000003BFFFFFFFFFFFFFFFFFFFFFFFFFFFFB3000000000
00000000000034545FFFFFFFFFFFFFFFF54543000000000000
000000000000000003FFFFFFFFFFFFFF400000000000000000
0000000000000000004EFFFFFFFFFFE4000000000000000000
00000000000000000002BFFFFFFFFB20000000000000000000
00000000000000000000049DFFD94000000000000000000000
}

!define MA_ACCOUNT_MINUS(_color)                                 SPRITE_PUT(                                    ma_account_minus, _color)
!define MA_ACCOUNT_MINUS(_color, _scale)                         SPRITE_PUT(                                    ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale, _shape)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ACCOUNT_MINUS, _label, ma_account_minus, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ACCOUNT_MINUS>> White
