sprite $r_square_fill [50x50/16] {
0005BEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEB5000
00BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00
0BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0
5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5
BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB
EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF988888888889CFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF300000000000018FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000000000000002DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF30000111110000001EFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFB300006FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFFF30000FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFFFC0000BFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFFFF00009FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFFFF10008FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFFFF0000AFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFFF90000DFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFFB00003FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF30006999997300000CFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF30000000000000009FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF300000000000002BFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF30001222210000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFE00008FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFF60001FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFD00008FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFF50001FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFD00008FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFF40001FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFFC00008FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFFF30001FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF3000AFFFFFFFFB00008FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF9777CFFFFFFFFF87778FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB
5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5
0BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0
00BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00
0005BEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEB5000
}

!define MA_ACCOUNT_MINUS(_color)                                 SPRITE_PUT(                                    ma_account_minus, _color)
!define MA_ACCOUNT_MINUS(_color, _scale)                         SPRITE_PUT(                                    ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale, _shape)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ACCOUNT_MINUS, _label, ma_account_minus, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ACCOUNT_MINUS>> White
