sprite $rss_fill [50x50/16] {
0005BEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEB5000
00BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00
0BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0
5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5
BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB
EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFEDEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFD200000258CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF2000000000005AFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFE0000000000000017EFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFE000000000000000006EFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFF30000000000000000019FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFE40000000000000000003EFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFEDCA840000000000001BFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFC6100000000009FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF910000000007FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF80000000007FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFE3000000009FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF700000000BFFFFFFFFFFFFFF
FFFFFFFFFA6568AEFFFFFFFFFFF900000001EFFFFFFFFFFFFF
FFFFFFFF7000000028EFFFFFFFFFB00000003FFFFFFFFFFFFF
FFFFFFFF000000000006EFFFFFFFFA00000009FFFFFFFFFFFF
FFFFFFFD00000000000009FFFFFFFF70000001EFFFFFFFFFFF
FFFFFFFF000000000000005FFFFFFFF30000006FFFFFFFFFFF
FFFFFFFF9000000000000003EFFFFFFE0000000EFFFFFFFFFF
FFFFFFFFFC764200000000003FFFFFFF80000007FFFFFFFFFF
FFFFFFFFFFFFFFD81000000005FFFFFFF1000001FFFFFFFFFF
FFFFFFFFFFFFFFFFF8000000009FFFFFF9000000AFFFFFFFFF
FFFFFFFFFFFFFFFFFFC10000000EFFFFFF1000005FFFFFFFFF
FFFFFFFFFFFFFFFFFFFE10000006FFFFFF6000000FFFFFFFFF
FFFFFFFFFFFFFFFFFFFFC0000000EFFFFFC000000CFFFFFFFF
FFFFFFFFFFFEDEFFFFFFF80000008FFFFFF0000008FFFFFFFF
FFFFFFFFFC30003CFFFFFF1000002FFFFFF4000005FFFFFFFF
FFFFFFFFC0000000CFFFFF8000000EFFFFF7000002FFFFFFFF
FFFFFFFF300000003FFFFFD000000AFFFFFA000000FFFFFFFF
FFFFFFFE000000000EFFFFF2000008FFFFFC000000FFFFFFFF
FFFFFFFD000000000DFFFFF4000006FFFFFD000000EFFFFFFF
FFFFFFFE000000000EFFFFF6000005FFFFFE000000DFFFFFFF
FFFFFFFF300000003FFFFFF8000005FFFFFF000000DFFFFFFF
FFFFFFFFC0000000CFFFFFFC00000AFFFFFF400002FFFFFFFF
FFFFFFFFFC30003CFFFFFFFF90008FFFFFFFE4003DFFFFFFFF
FFFFFFFFFFFEDEFFFFFFFFFFFFDFFFFFFFFFFFEEFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB
5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5
0BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0
00BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB00
0005BEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEB5000
}

!define MA_ACCOUNT_MINUS(_color)                                 SPRITE_PUT(                                    ma_account_minus, _color)
!define MA_ACCOUNT_MINUS(_color, _scale)                         SPRITE_PUT(                                    ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale, _shape)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ACCOUNT_MINUS, _label, ma_account_minus, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ACCOUNT_MINUS>> White
