sprite $safe_fill [50x50/16] {
000005CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD600
00009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB0
0005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6
000BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD
000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
399FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
278FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
000DFFFFFFFFFFFB8FFFFFFFFFFFFFFFFFFA9FFFFFFFFFFFFF
000DFFFFFFFFFFC003EFFFFFFFFFFFFFFF6008FFFFFFFFFFFF
000DFFFFFFFFFFB0003EFFFFCAABFFFFF60007FFFFFFFFFFFF
000DFFFFFFFFFFF60003ED60000004BF60003FFFFFFFFFFFFF
000DFFFFFFFFFFFF60002000000000020003FFFFFFFFFFFFFF
000DFFFFFFFFFFFFF600000002200000003FFFFFFEDFFFFFFF
000DFFFFFFFFFFFFFF400019FFFFA20001EFFFFFD008FFFFFF
000DFFFFFFFFFFFFFE0003EFFFFFFF4000AFFFFFA004FFFFFF
000DFFFFFFFFFFFFF7001EFFFFFFFFF2003FFFFF9004FFFFFF
000DFFFFFFFFFFFFF1009FFFFFFFFFFB000DFFFF9004FFFFFF
288FFFFFFFFFFFFFE000FFFFFFFFFFFF100AFFFF9004FFFFFF
EFFFFFFFFFFFFFFFC002FFFFFFFFFFFF3008FFFF9004FFFFFF
EFFFFFFFFFFFFFFFC002FFFFFFFFFFFF4008FFFF9004FFFFFF
288FFFFFFFFFFFFFE000FFFFFFFFFFFF100AFFFF9004FFFFFF
000DFFFFFFFFFFFFF100AFFFFFFFFFFC000DFFFF9004FFFFFF
000DFFFFFFFFFFFFF7002FFFFFFFFFF4003FFFFF9004FFFFFF
000DFFFFFFFFFFFFFE0005FFFFFFFF6000AFFFFFA004FFFFFF
000DFFFFFFFFFFFFFF40003BFFFFC40001FFFFFFD008FFFFFF
000DFFFFFFFFFFFFF600000014420000003FFFFFFEDFFFFFFF
000DFFFFFFFFFFFF60002000000000020003FFFFFFFFFFFFFF
000DFFFFFFFFFFF60003ED60000004BF60003FFFFFFFFFFFFF
000DFFFFFFFFFFB0003EFFFFCAABFFFFF60007FFFFFFFFFFFF
000DFFFFFFFFFFC003EFFFFFFFFFFFFFFF6008FFFFFFFFFFFF
000DFFFFFFFFFFFB8FFFFFFFFFFFFFFFFFFA9FFFFFFFFFFFFF
277EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
399FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
000DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
000BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD
0004FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6
00009FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA0
000005CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD600
}

!define MA_ACCOUNT_MINUS(_color)                                 SPRITE_PUT(                                    ma_account_minus, _color)
!define MA_ACCOUNT_MINUS(_color, _scale)                         SPRITE_PUT(                                    ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, MA ACCOUNT_MINUS,         ma_account_minus, _color, _scale, _shape)
!define MA_ACCOUNT_MINUS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, MA ACCOUNT_MINUS, _label, ma_account_minus, _color, _scale, _shape)
skinparam folderBackgroundColor<<MA ACCOUNT_MINUS>> White
