' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $application [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $applicationIMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAOBJREFUeNrt27ENgkAUBuATmcIhKK1cwBVMbBzMQoewtLGidAu38EwOg4WJBpq7+/7kBY6C8L4Ar7oQRKrOIh33sQ6V9X6MdW7SYherq6j5LvUc2tHFPta2EoDLcNIU0Mwt1a/rjzSh8rQF9LD5c/0VYB3rWtFPsJ/zE+hynSJzTYHhr5rLFClqCkwKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoMXPtGBk2S+Sy4+S9Y2Q5ehNWE274SJVLXs96inUPInXnCb4aFt3WBUTuAAAAAElFTkSuQmCC{scale="+$scale+"}>"
!endfunction

IBMEntityColoring(application)
!define application(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, application, application)
!define application(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, application, application)
!define applicationParticipant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, application, application)
!define applicationParticipant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, application, application)
