' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $identifyandresolveissues [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $identifyandresolveissuesIMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAZZJREFUeNrtm71KA0EUhSfr+hK26SxSio0Wdr5CwEZQH8K105dQsDAPYeNPkSaktLBPKfoQ3sEbWYZF4s7Pzr1zDhzITBLY78vswLDEGAQpOiNnfEI9Vc58T52tB5Xz5pQ6UQw/Ycbf1B0fWlKPlQp4dCeq0vcACIAACIAACIAACIAACIAAXTkqWcA19XlTCZVC+EvqDfWlNAFt+Ka0W6AXvBYBveE1CPCCly7AG16ygCDwUgUEg5coICi8NAHB4W1qj+/uU8/49R11IQ3eZwVY+Dn1kDvnOVHwPgLOqSvqLnfFc6LgQ+8BtTR4n4u+NT9Pkt95PKY+SYP3EWA3vAPeBLf5/H1B/QpwwcngfZftwtn5P1sX3EiAD33fXjnwTe7wMTauvhIGgY8hoI+EweBjCfiPhEHhYwrYRMLg8LEF/CUhC/gUArokmFzgUwlYSxgxuMkFPqUAdwVkAZ9aQFbgMU6DIgMBEAABEAABEAABEAABEAABZabrNLhHfVXKa/82t2xPbHWsiB3FP/gH9YH6ZhAEsfkGkKNZ73OzfBoAAAAASUVORK5CYII={scale="+$scale+"}>"
!endfunction

IBMEntityColoring(identifyandresolveissues)
!define identifyandresolveissues(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, identifyandresolveissues, identifyandresolveissues)
!define identifyandresolveissues(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, identifyandresolveissues, identifyandresolveissues)
!define identifyandresolveissuesParticipant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, identifyandresolveissues, identifyandresolveissues)
!define identifyandresolveissuesParticipant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, identifyandresolveissues, identifyandresolveissues)
