' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)
sprite $parisarcdetriomphe [64x64/16z] xS61400000CXXFdRpkElMXu0001m

!function $parisarcdetriompheIMG($scale=1)
!return "<img data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAEZ0FNQQAAsY58+1GTAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAhVJREFUeNrtmj9Lw0AYxtMqfgUprk4qoosuLhkrHQQ/g07qJA4WoSBKFReti+46ipN26+LkooguLoqi0g/QQaHoc/AWQzCpySWld31e+EEul7zcPXnvz3vEcWg0Gq2HLfPHvZrlfXa9hWzAQ+OCLRa5P5eCLRbYn2yvzwH9IXVTFs0HKvyvGQERI0AplrdoDnB0IqDdpNjt9Y6uAH67EjpZn9GsdzgHRJwDwmzG8HpuhNrlAq1t451F+4BWf1zOARwCjADmAlEjwJ9Pm1bWzgVa46dT5Sr4TrjMnSAF6OFlsMplkEMg2WxQx3JgFkyAQblXB7fgAnzYKsAY2ARzUn4BT3I9DZbk+hxsgHubBFgDW/KlV8AZePM9MwTm5dkbUAS7NghwDBbAIVgFnwHPKUEOwBHYAztgGCyaLMC6dF599co/31ECLYNHEeQZbJu4CoyAEtiP0HmvVeTdkvgyToAyeJexHNeK4qNsmgA5SUTUF2xo+GnIMMiLT2MEKIA+cJqArxPxVTBJALXmv8qyp2t18TWaRkPTOhVWjR2Q9dzVbKNqzyT4Ag8xfXT8VFiFbDNBf03xaUw6nHQ6reuP6XCcnaDOqXDgKayGpdIeRkBInc4fImkcp+m0h6fCFIACUAAKQAEoAAWgAMwFGAHMBRgBFIAC/Jr3VLjmmzWVxT0VTvpf4zTa44ZNgroNT/on625rjz32A6kvlFlYVF+0AAAAAElFTkSuQmCC{scale="+$scale+"}>"
!endfunction

IBMEntityColoring(parisarcdetriomphe)
!define parisarcdetriomphe(e_alias, e_label, e_techn) IBMEntity(e_alias, e_label, e_techn, #232F3E, parisarcdetriomphe, parisarcdetriomphe)
!define parisarcdetriomphe(e_alias, e_label, e_techn, e_descr) IBMEntity(e_alias, e_label, e_techn, e_descr, #232F3E, parisarcdetriomphe, parisarcdetriomphe)
!define parisarcdetriompheParticipant(p_alias, p_label, p_techn) IBMParticipant(p_alias, p_label, p_techn, #232F3E, parisarcdetriomphe, parisarcdetriomphe)
!define parisarcdetriompheParticipant(p_alias, p_label, p_techn, p_descr) IBMParticipant(p_alias, p_label, p_techn, p_descr, #232F3E, parisarcdetriomphe, parisarcdetriomphe)
