sprite $AzureStorSimple [70x70/16z] {
xTS73gGm38LXjpZEu_xdtM8o6aKB8jxUVlLH-EIXG-N-nymoOsOgno9gNwJ25S8kgacizj26mxRH8wEsaT93jXKz9BRaixOxYowCzuYn5drYCbVIHOCfO_6-
0gkahtNZKW7JJFs6wKrfnhXM3WYzq-OUCRM8S6z2x-muRfJZwB9vTe_ZLldSK7uqsf7TAjbemdS0IyjrZqg6Q2gyRAxcSyckCiFQaLKLN2Y_uIp_PudM-hVF
maJqpRC44L6VI5r1JyRoDf1AHrc143lWb3aGGeAgalSqfjcyoMfLQNHHgogWYr1KvZ3QcYoZL9MU2f2QfnLrHVCtn6V5pjF6gWeyHu3JESKvKaT5wKePG3C4
PThtbMNRB5wU_385YrTKmYXpDCfyNb3MQqSwJnV6oRHpAAwVkvBp0uW0e3dHLvwxUNS0EiyLPSLe9bAwZfwNeAeONMHLHN8hNV-Mr--x904CFbydyxxht_OC
S7nkVEFpQAHoVDkpKRxzEJqYnaH-Y_UNdpvBhyuIT95LPp6wAif_wDkPeBlQFc9q7pTiCKuFQNz2ej5ErWTkcE5AXLXR3xmwluA5wG_e8m
}

AzureEntityColoring(AzureStorSimple)
!define AzureStorSimple(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureStorSimple, AzureStorSimple)
!define AzureStorSimple(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureStorSimple, AzureStorSimple)
