sprite $AzureNetAppFiles [70x70/16z] {
xTO5hiGm34NHnbJO_tu_38FrPAlSvee3Pw3OvAhLMCSaV46i7vdzA_tegbALgjZeZgse95DFQT8vYkOLXOeeI89A6M0bfX1MQ7x5yWeyNmmh1i-NHorMMdiq
cwBt32il2ns5xidh1ykbxcL8w1Q75RuFEGffLA6zA3QRmbc5m-UBC_HO6By2d25mxevLy3Nj3E5hccSuqXjH62iSKqZitkDpzMK8A-7m5P2CFSKqsMRVWjhH
_Iiw5j5_fV38IfEgLli5
}

AzureEntityColoring(AzureNetAppFiles)
!define AzureNetAppFiles(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureNetAppFiles, AzureNetAppFiles)
!define AzureNetAppFiles(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureNetAppFiles, AzureNetAppFiles)
