sprite $AzureLogicApps [65x50/16z] {
tPS74jmW301LaSJ_7npZfaa0vuZJTveRYqwY7JIeU0J1vr24QJRGg54N1Qs5ddTSTnO53O4Tgnic20l8tiYXWSrceu_AYS20PWYymnbye_McZFIrdddZJH0C
7Pw2GEZ8PXC1ReAm3NyXs4FN5m9DmRyQWSc6lH2yAYDO2Xn-H41-j-SLGOBK7Cw4i2X8FAVPNoyW669p0Tq2pKAFneBtht8TqlEZIJVYMSHXTCrkKKSf85QB
g3iHfemuN5ZTXdtmDGf3zRAuVglWwKZJwxaI09V8pmO2Yvf5oFRXHQuHYApc_I_b_P7rIQGO9OuqiYAPH1gKKVB3RkH8NyP-89Lk7nY-eEbGBgUuGrFmC1U8
sl0bd4I0tn5WYMYtuTeD3MiltEHH8FKYk1js9_maAFL6kgtqf7meqEbM_JQ2zuB_F0USuu2wcPJckG34VCSOlaRZfC1Ky0pI3a8do6FU0ddCouFc0ddGp0EX
BSM0OZMxbKpxHsIr-ELnN_9UBTOYo3ySNm
}

AzureEntityColoring(AzureLogicApps)
!define AzureLogicApps(e_alias, e_label, e_techn) AzureEntity(e_alias, e_label, e_techn, AZURE_SYMBOL_COLOR, AzureLogicApps, AzureLogicApps)
!define AzureLogicApps(e_alias, e_label, e_techn, e_descr) AzureEntity(e_alias, e_label, e_techn, e_descr, AZURE_SYMBOL_COLOR, AzureLogicApps, AzureLogicApps)
