sprite $Cloud_TPU [64x64/16z] {
tPVPkXin28Cn1WJl_yBj9Eukd79x_elCgi-Cv2tonL2B2wPonnDNqkzov0VWqgF8Zq2b9Vv77zAnZ_mEjd0MaJCmC8y16pJFm1gRnotasOqovCtF2p3a0DZL
lBc5FjNx1_FYEwzVd7DgOM_U5jc__rujt4Ychzz_RyE0VBoAAF0eWUUSM739BfRynGgU8SzkaU6HHJ8asSNUAWJT6on3pJyvoGQm30yXSSoE_1CzsJ7z4m6U
aikqGFM8ansht_RhMQKlBvpwIOOak_EwYYxrLtWG4HJBq8Z-l8wLC7ttZqv_vAH-PAwezvUhi_eVIEl-iq-g5vRASblClqElt-fYfLw5LXzj_ULF2fKQbMZh
tvt_gFskGZHx_qq2ZVycI_RhtAlH8qIqgLzNlDqD4y-cVZt3X_YdMUyHLnLYVV-LnVL1DXr11x2Dn-_1c-chslc3pp9xE7yTZ4xVy_cJFQr7MR__aXP-uNpz
E4gsVcJSbqz4u8zVOjvi-MRP_MAe1zdxJTZz_cNU_CbmW0wsZuIOxn_xxEOPcd0mD8zaECvkdc58YuwpcrleSiD0uVBv_qTN-M9y0m
}

EntityColoring(Cloud_TPU)
!define Cloud_TPU(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, Cloud_TPU, Cloud_TPU)
!define Cloud_TPU(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, Cloud_TPU, Cloud_TPU)
!define Cloud_TPUParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, Cloud_TPU, Cloud_TPU)
!define Cloud_TPUParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, Cloud_TPU, Cloud_TPU)
