sprite $KubernetesKproxy [70x66/16z] {
rPO7Tbr124FfeFrlEEUFo_CXy4jwhdkJGMBcGVyH1Y3vfpKEfVJ3E0u_eyE1XhskaHXmUWKfBCJJHcjXu-d058z8UJRQ-vI-50jGHfABphEnfD8DQV9xy7dN
0FP1HvuG2NaNKDvqUboy3ORMLPHL_wMUxpPS5UuUHJJgD9NO1XI00qNKTCQMcccBog5sVt6Hz9KwAaaNlXeZ-y7LyjBLmlK-4cemxTq__W5hL1WJYLUvhiRS
jyKzAjn9tJFTPIhS7ze2b1P03dW0DXbJotsWBUIZaWdOql_OALDNiQQo_3hD9Kh2pn7ocuhFYLxQlCsHghwdPKmNip6st3qHDCAZCJaF00CcfnYzj7TZHcal
k2NEDx8TtXWovN7cz3HNNiaA66csoMX_eREvvu9BJy14hBusAqFrCGTNSShquhSldIw6cmfZS8hAg8WGekwmutjZbWkPoU5n-OtGonRqlv1zkt2EgpgWQFe3
NENr2Y-2wS2f_6xOfFBWMMNnhYRRyqz6bMfp6doh17ubEXGFT98k1A5P5TRwxxNO_VtjLWYAY6NRaTPjePy-xqCxdDzQVzIfE_-GWKxnjkFiQuCi3ZSSUvwB
m_7KvhXi7g_1ks_FezJ1w_X-iLlYIVBEwgw1voWQyGyLzrEKgmJSkL9KgnJG501IBPvXg3H2SKC5HMK2SC4LRg7GG4gFPmXAbO5qBtL0qXp5E6_2TPFGwF5q
Zeh4hW9Elk9P442Zk73aJaV-qP5v2k1YBPu1WoL2ZueTTmCuxgO25W1LYsSFQeyyj3axatTLL6gvV5uzKKPFm2-TdXt7JWdzutm3
}

KubernetesEntityColoring(KubernetesKproxy)
!define KubernetesKproxy(e_alias, e_label, e_techn) KubernetesEntity(e_alias, e_label, e_techn, KUBERNETES_SYMBOL_COLOR, KubernetesKproxy, KubernetesKproxy)
!define KubernetesKproxy(e_alias, e_label, e_techn, e_descr) KubernetesEntity(e_alias, e_label, e_techn, e_descr, KUBERNETES_SYMBOL_COLOR, KubernetesKproxy, KubernetesKproxy)
